#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Apr 30 16:22:59 CDT 2023
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=ComplementaryShaders_v4.7_pre2.zip
enableShaders=false
