[general]
giveBookOnStartup = false
mimicreamRepair = false
mimicreamBlacklist = ["alexsmobs:blood_sprayer"]
seagullStealingBlacklist = [
	"artifacts:eternal_steak",
	"artifacts:everlasting_beef"
]

[general.spawning]
roadrunnerSpawnWeight = 10
roadrunnerSpawnRolls = 0
boneSerpentSpawnWeight = 2
boneSeprentSpawnRolls = 50
crocodileSpawnWeight = 20
flySpawnWeight = 1
flySpawnRolls = 3
orcaSpawnRolls = 50
crimsonMosquitoSpawnWeight = 11
crimsonMosquitoSpawnRolls = 20
rattlesnakeSpawnWeight = 3
caveCentipedeSpawnWeight = 0
mooseSpawnWeight = 15
mimicubeSpawnWeight = 0
raccoonSpawnWeight = 3
sealSpawnWeight = 10
sealSpawnRolls = 10
cockroachSpawnWeight = 0
crowSpawnWeight = 3
gusterSpawnWeight = 10
straddlerSpawnWeight = 8
kangarooSpawnWeight = 8
enderiophageSpawnRolls = 3
baldEagleSpawnWeight = 0
