[general]
dimensionBlacklist = [
	"compactmachines:compact_world",
	"atum:atum",
	"mythicbotany:alfheim",
	"undergarden:undergarden"
]
genOre = false
spawnBook = false
wguardianWeight = 8
wstalkerWeight = 8
whunterWeight = 8
hunterHuntsAnimals = false
crystallizer_output = "emendatusenigmatica:arcane_gem"
