orechidPriorityMods = [
  "emendatusenigmatica",
  "minecraft",
  "immersiveengineering",
  "create",
  "mekanism",
  "jaopca",
  "kubejs",
  "refinedstorage",
  "pneumaticcraft",
  "occultism",
  "tmechworks",
  "industrialforegoing",
  "botania",
  "quark",
  "pedestals"
]
