["Coal Config"]

["Coal Config"."The Nether"]
nether_size = 17
nether_biome_list_invert = true
nether_spread = 60
nether_base = 70
nether_count = 4
generate_in_the_nether = true
nether_biome_blacklist = ["byg:embur_bog", "byg:weeping_mire"]
nether_use_spread = true

["Coal Config".Overworld]
overworld_base = 80
overworld_count = 20
overworld_biome_blacklist = []
overworld_biome_list_invert = false
overworld_spread = 100
overworld_size = 17
generate_in_the_overworld = true
overworld_use_spread = true

["Coal Config"."The End"]
generate_in_the_end = false

["Iron Config"]

["Iron Config"."The Nether"]
generate_in_the_nether = false

["Iron Config".Overworld]
overworld_base = 75
overworld_count = 28
overworld_biome_blacklist = []
overworld_biome_list_invert = false
overworld_spread = 70
overworld_size = 11
generate_in_the_overworld = true
overworld_use_spread = true

["Iron Config"."The End"]
end_base = 52
end_spread = 32
end_biome_list_invert = true
end_biome_blacklist = ["byg:viscal_isles", "byg:ivis_fields"]
generate_in_the_end = true
end_count = 2
end_size = 19
end_use_spread = true

["Gold Config"]

["Gold Config"."The Nether"]
nether_size = 13
nether_biome_list_invert = false
nether_spread = 32
nether_base = 46
nether_count = 6
generate_in_the_nether = true
nether_biome_blacklist = []
nether_use_spread = true

["Gold Config".Overworld]
overworld_base = 16
overworld_count = 4
overworld_biome_blacklist = []
overworld_biome_list_invert = false
overworld_spread = 16
overworld_size = 10
generate_in_the_overworld = true
overworld_use_spread = true

["Gold Config"."The End"]
generate_in_the_end = false

["Diamond Config"]

["Diamond Config"."The Nether"]
generate_in_the_nether = false

["Diamond Config".Overworld]
overworld_base = 8
overworld_count = 3
overworld_biome_blacklist = []
overworld_biome_list_invert = false
overworld_spread = 8
overworld_size = 8
generate_in_the_overworld = true
overworld_use_spread = true

["Diamond Config"."The End"]
end_base = 28
end_spread = 8
end_biome_list_invert = true
end_biome_blacklist = [
	"byg:purpur_peaks",
	"byg:ethereal_islands",
	"betterendforge:crystal_mountains",
	"betterendforge:umbrella_jungle"
]
generate_in_the_end = true
end_count = 3
end_size = 8
end_use_spread = true

["Emerald Config"]

["Emerald Config"."The Nether"]
generate_in_the_nether = false

["Emerald Config".Overworld]
overworld_base = 156
overworld_count = 3
overworld_biome_blacklist = []
overworld_biome_list_invert = false
overworld_spread = 56
overworld_size = 4
generate_in_the_overworld = true
overworld_use_spread = true

["Emerald Config"."The End"]
end_base = 176
end_spread = 56
end_biome_list_invert = true
end_biome_blacklist = [
	"byg:shulkren_forest",
	"byg:ethereal_islands",
	"betterendforge:blossoming_spires",
	"betterendforge:crystal_mountains"
]
generate_in_the_end = true
end_count = 2
end_size = 11
end_use_spread = true

["Lapis Lazuli Config"]

["Lapis Lazuli Config"."The Nether"]
generate_in_the_nether = false

["Lapis Lazuli Config".Overworld]
overworld_base = 8
overworld_count = 4
overworld_biome_blacklist = []
overworld_biome_list_invert = false
overworld_spread = 8
overworld_size = 7
generate_in_the_overworld = true
overworld_use_spread = true

["Lapis Lazuli Config"."The End"]
end_base = 28
end_spread = 8
end_biome_list_invert = true
end_biome_blacklist = [
	"byg:shattered_desert",
	"byg:bulbis_gardens",
	"betterendforge:megalake",
	"betterendforge:megalake_grove"
]
generate_in_the_end = true
end_count = 3
end_size = 14
end_use_spread = true

["Redstone Config"]

["Redstone Config"."The Nether"]
nether_size = 15
nether_biome_list_invert = true
nether_spread = 18
nether_base = 38
nether_count = 5
generate_in_the_nether = true
nether_biome_blacklist = ["byg:glowstone_gardens", "minecraft:crimson_forest"]
nether_use_spread = true

["Redstone Config".Overworld]
overworld_base = 8
overworld_count = 8
overworld_biome_blacklist = []
overworld_biome_list_invert = false
overworld_spread = 8
overworld_size = 11
generate_in_the_overworld = true
overworld_use_spread = true

["Redstone Config"."The End"]
generate_in_the_end = false

["Copper Config"]

["Copper Config"."The Nether"]
nether_size = 14
nether_biome_list_invert = true
nether_spread = 8
nether_base = 82
nether_count = 5
generate_in_the_nether = true
nether_biome_blacklist = [
	"byg:sythian_torrids",
	"byg:withering_woods",
	"minecraft:warped_forest"
]
nether_use_spread = true

["Copper Config".Overworld]
overworld_base = 90
overworld_count = 28
overworld_biome_blacklist = []
overworld_biome_list_invert = false
overworld_spread = 90
overworld_size = 8
generate_in_the_overworld = true
overworld_use_spread = true

["Copper Config"."The End"]
generate_in_the_end = false

["Aluminum Config"]

["Aluminum Config"."The Nether"]
generate_in_the_nether = false

["Aluminum Config".Overworld]
overworld_base = 60
overworld_count = 8
overworld_biome_blacklist = []
overworld_biome_list_invert = false
overworld_spread = 10
overworld_size = 9
generate_in_the_overworld = true
overworld_use_spread = true

["Aluminum Config"."The End"]
end_base = 40
end_spread = 10
end_biome_list_invert = true
end_biome_blacklist = ["betterendforge:chorus_forest", "byg:ivis_fields"]
generate_in_the_end = true
end_count = 3
end_size = 9
end_use_spread = true

["Silver Config"]

["Silver Config"."The Nether"]
generate_in_the_nether = false

["Silver Config".Overworld]
overworld_base = 34
overworld_count = 8
overworld_biome_blacklist = []
overworld_biome_list_invert = false
overworld_spread = 4
overworld_size = 5
generate_in_the_overworld = true
overworld_use_spread = true

["Silver Config"."The End"]
end_base = 54
end_spread = 4
end_biome_list_invert = true
end_biome_blacklist = ["byg:ethereal_islands", "betterendforge:amber_land"]
generate_in_the_end = true
end_count = 3
end_size = 13
end_use_spread = true

["Lead Config"]

["Lead Config"."The Nether"]
nether_size = 13
nether_biome_list_invert = true
nether_spread = 20
nether_base = 66
nether_count = 4
generate_in_the_nether = true
nether_biome_blacklist = [
	"byg:magma_wastes",
	"byg:wailing_garth",
	"minecraft:nether_wastes"
]
nether_use_spread = true

["Lead Config".Overworld]
overworld_base = 36
overworld_count = 8
overworld_biome_blacklist = []
overworld_biome_list_invert = false
overworld_spread = 4
overworld_size = 5
generate_in_the_overworld = true
overworld_use_spread = true

["Lead Config"."The End"]
generate_in_the_end = false

["Nickel Config"]

["Nickel Config"."The Nether"]
generate_in_the_nether = false

["Nickel Config".Overworld]
overworld_base = 32
overworld_count = 8
overworld_biome_blacklist = []
overworld_biome_list_invert = false
overworld_spread = 8
overworld_size = 4
generate_in_the_overworld = true
overworld_use_spread = true

["Nickel Config"."The End"]
end_base = 52
end_spread = 8
end_biome_list_invert = true
end_biome_blacklist = ["byg:cryptic_wastes", "betterendforge:shadow_forest"]
generate_in_the_end = true
end_count = 3
end_size = 11
end_use_spread = true

["Uranium Config"]

["Uranium Config"."The Nether"]
nether_size = 13
nether_biome_list_invert = true
nether_spread = 12
nether_base = 62
nether_count = 5
generate_in_the_nether = true
nether_biome_blacklist = [
	"byg:magma_wastes",
	"byg:wailing_garth",
	"minecraft:nether_wastes"
]
nether_use_spread = true

["Uranium Config".Overworld]
overworld_base = 12
overworld_count = 6
overworld_biome_blacklist = []
overworld_biome_list_invert = false
overworld_spread = 8
overworld_size = 6
generate_in_the_overworld = true
overworld_use_spread = true

["Uranium Config"."The End"]
generate_in_the_end = false

["Osmium Config"]

["Osmium Config"."The Nether"]
nether_size = 11
nether_biome_list_invert = true
nether_spread = 12
nether_base = 62
nether_count = 4
generate_in_the_nether = true
nether_biome_blacklist = ["byg:subzero_hypogeal", "minecraft:soul_sand_valley"]
nether_use_spread = true

["Osmium Config".Overworld]
overworld_base = 32
overworld_count = 15
overworld_biome_blacklist = []
overworld_biome_list_invert = false
overworld_spread = 12
overworld_size = 6
generate_in_the_overworld = true
overworld_use_spread = true

["Osmium Config"."The End"]
generate_in_the_end = false

["Tin Config"]

["Tin Config"."The Nether"]
generate_in_the_nether = false

["Tin Config".Overworld]
overworld_base = 80
overworld_count = 23
overworld_biome_blacklist = []
overworld_biome_list_invert = false
overworld_spread = 50
overworld_size = 8
generate_in_the_overworld = true
overworld_use_spread = true

["Tin Config"."The End"]
end_base = 67
end_spread = 7
end_biome_list_invert = true
end_biome_blacklist = ["byg:viscal_isles", "byg:cryptic_wastes"]
generate_in_the_end = true
end_count = 3
end_size = 16
end_use_spread = true

["Zinc Config"]

["Zinc Config"."The Nether"]
generate_in_the_nether = false

["Zinc Config".Overworld]
overworld_base = 64
overworld_count = 9
overworld_biome_blacklist = []
overworld_biome_list_invert = false
overworld_spread = 20
overworld_size = 5
generate_in_the_overworld = true
overworld_use_spread = true

["Zinc Config"."The End"]
end_base = 62
end_spread = 8
end_biome_list_invert = true
end_biome_blacklist = [
	"byg:nightshade_forest",
	"byg:cryptic_wastes",
	"betterendforge:dust_wastelands"
]
generate_in_the_end = true
end_count = 5
end_size = 13
end_use_spread = true

["Certus Quartz Config"]

["Certus Quartz Config"."The Nether"]
generate_in_the_nether = false

["Certus Quartz Config".Overworld]
generate_in_the_overworld = false

["Certus Quartz Config"."The End"]
generate_in_the_end = false

["Charged Certus Quartz Config"]

["Charged Certus Quartz Config"."The Nether"]
generate_in_the_nether = false

["Charged Certus Quartz Config".Overworld]
generate_in_the_overworld = false

["Charged Certus Quartz Config"."The End"]
generate_in_the_end = false

["Fluorite Config"]

["Fluorite Config"."The Nether"]
nether_size = 8
nether_biome_list_invert = true
nether_spread = 16
nether_base = 36
nether_count = 3
generate_in_the_nether = true
nether_biome_blacklist = ["byg:glowstone_gardens", "minecraft:warped_forest"]
nether_use_spread = true

["Fluorite Config".Overworld]
overworld_base = 16
overworld_count = 2
overworld_biome_blacklist = []
overworld_biome_list_invert = false
overworld_spread = 16
overworld_size = 14
generate_in_the_overworld = true
overworld_use_spread = true

["Fluorite Config"."The End"]
generate_in_the_end = false

["Bitumen Config"]

["Bitumen Config"."The Nether"]
nether_size = 18
nether_biome_list_invert = true
nether_spread = 20
nether_base = 128
nether_count = 2
generate_in_the_nether = true
nether_biome_blacklist = ["byg:embur_bog", "byg:weeping_mire"]
nether_use_spread = true

["Bitumen Config".Overworld]
overworld_base = 100
overworld_count = 2
overworld_biome_blacklist = []
overworld_biome_list_invert = false
overworld_spread = 60
overworld_size = 18
generate_in_the_overworld = true
overworld_use_spread = true

["Bitumen Config"."The End"]
generate_in_the_end = false

["Cinnabar Config"]

["Cinnabar Config"."The Nether"]
generate_in_the_nether = false

["Cinnabar Config".Overworld]
generate_in_the_overworld = false

["Cinnabar Config"."The End"]
generate_in_the_end = false

["Apatite Config"]

["Apatite Config"."The Nether"]
generate_in_the_nether = false

["Apatite Config".Overworld]
overworld_base = 96
overworld_count = 2
overworld_biome_blacklist = []
overworld_biome_list_invert = false
overworld_spread = 32
overworld_size = 22
generate_in_the_overworld = true
overworld_use_spread = true

["Apatite Config"."The End"]
end_base = 116
end_spread = 32
end_biome_list_invert = true
end_biome_blacklist = [
	"byg:shattered_desert",
	"byg:bulbis_gardens",
	"betterendforge:foggy_mushroomland"
]
generate_in_the_end = true
end_count = 1
end_size = 29
end_use_spread = true

["Sulfur Config"]

["Sulfur Config"."The Nether"]
generate_in_the_nether = false

["Sulfur Config".Overworld]
generate_in_the_overworld = false

["Sulfur Config"."The End"]
generate_in_the_end = false

["Potassium Nitrate Config"]

["Potassium Nitrate Config"."The Nether"]
nether_size = 12
nether_biome_list_invert = true
nether_spread = 7
nether_base = 55
nether_count = 1
generate_in_the_nether = true
nether_biome_blacklist = ["minecraft:basalt_deltas"]
nether_use_spread = true

["Potassium Nitrate Config".Overworld]
overworld_base = 25
overworld_count = 1
overworld_biome_blacklist = []
overworld_biome_list_invert = false
overworld_spread = 7
overworld_size = 12
generate_in_the_overworld = true
overworld_use_spread = true

["Potassium Nitrate Config"."The End"]
generate_in_the_end = false

["Arcane Config"]

["Arcane Config"."The Nether"]
generate_in_the_nether = false

["Arcane Config".Overworld]
overworld_base = 33
overworld_count = 5
overworld_biome_blacklist = []
overworld_biome_list_invert = false
overworld_spread = 13
overworld_size = 6
generate_in_the_overworld = true
overworld_use_spread = true

["Arcane Config"."The End"]
end_base = 53
end_spread = 13
end_biome_list_invert = true
end_biome_blacklist = [
	"byg:purpur_peaks",
	"byg:bulbis_gardens",
	"betterendforge:blossoming_spires"
]
generate_in_the_end = true
end_count = 3
end_size = 12
end_use_spread = true

["Dimensional Shard Config"]

["Dimensional Shard Config"."The Nether"]
nether_size = 3
nether_biome_list_invert = false
nether_spread = 40
nether_base = 60
nether_count = 8
generate_in_the_nether = true
nether_biome_blacklist = []
nether_use_spread = true

["Dimensional Shard Config".Overworld]
overworld_base = 10
overworld_count = 2
overworld_biome_blacklist = []
overworld_biome_list_invert = false
overworld_spread = 10
overworld_size = 2
generate_in_the_overworld = true
overworld_use_spread = true

["Dimensional Shard Config"."The End"]
end_base = 50
end_spread = 40
end_biome_list_invert = false
end_biome_blacklist = []
generate_in_the_end = true
end_count = 7
end_size = 8
end_use_spread = true

["Nether Quartz Config"]

["Nether Quartz Config"."The Nether"]
nether_size = 14
nether_biome_list_invert = false
nether_spread = 50
nether_base = 60
nether_count = 16
generate_in_the_nether = true
nether_biome_blacklist = []
nether_use_spread = true

["Nether Quartz Config".Overworld]
generate_in_the_overworld = false

["Nether Quartz Config"."The End"]
generate_in_the_end = false

["Stratum Config: minecraft_stone"]
active = true

["Stratum Config: minecraft_andesite"]
active = true

["Stratum Config: minecraft_granite"]
active = false

["Stratum Config: minecraft_diorite"]
active = false

["Stratum Config: minecraft_sand"]
active = false

["Stratum Config: minecraft_gravel"]
active = false

["Stratum Config: minecraft_netherrack"]
active = true

["Stratum Config: minecraft_blackstone"]
active = true

["Stratum Config: minecraft_basalt"]
active = true

["Stratum Config: minecraft_soul_soil"]
active = true

["Stratum Config: minecraft_end_stone"]
active = true

["Stratum Config: create_gabbro"]
active = true

["Stratum Config: create_limestone"]
active = true

["Stratum Config: create_scoria"]
active = true

["Stratum Config: create_weathered_limestone"]
active = true

["Stratum Config: quark_jasper"]
active = true

["Stratum Config: quark_marble"]
active = false

["Stratum Config: quark_slate"]
active = true

["Stratum Config: byg_mossy_stone"]
active = true

["Stratum Config: byg_brimstone"]
active = true

["Stratum Config: byg_subzero_ash"]
active = true

["Stratum Config: byg_blue_netherrack"]
active = true

["Stratum Config: byg_nylium_soul_soil"]
active = true

["Stratum Config: byg_ether_stone"]
active = true

["Stratum Config: byg_cryptic_stone"]
active = true

["Stratum Config: betterend_flavolite"]
active = true

["Stratum Config: betterend_sulphuric_rock"]
active = true

["Stratum Config: betterend_violecite"]
active = true

["Stratum Config: astral_marble"]
active = true

["Cobalt Config"]

["Cobalt Config"."The Nether"]
nether_size = 3
nether_biome_list_invert = false
nether_spread = 64
nether_base = 32
nether_count = 14
generate_in_the_nether = true
nether_biome_blacklist = []
nether_use_spread = true

["Cobalt Config".Overworld]
generate_in_the_overworld = false

["Cobalt Config"."The End"]
generate_in_the_end = false

["Stratum Config: quark_deepslate"]
active = true

["Ruby Config"]

["Ruby Config".Overworld]
generate_in_the_overworld = false

["Ruby Config"."The Nether"]
generate_in_the_nether = false

["Ruby Config"."The End"]
generate_in_the_end = false

["Sapphire Config"]

["Sapphire Config".Overworld]
generate_in_the_overworld = false

["Sapphire Config"."The Nether"]
generate_in_the_nether = false

["Sapphire Config"."The End"]
generate_in_the_end = false

["Iridium Config"]

["Iridium Config".Overworld]
generate_in_the_overworld = false

["Iridium Config"."The Nether"]
generate_in_the_nether = false

["Iridium Config"."The End"]
generate_in_the_end = false

["Peridot Config"]

["Peridot Config".Overworld]
generate_in_the_overworld = false

["Peridot Config"."The Nether"]
generate_in_the_nether = false

["Peridot Config"."The End"]
generate_in_the_end = false
