[client]

[client.control_options]
blacklist = [
	"sophisticatedbackpacks:netherite_backpack",
	"sophisticatedbackpacks:diamond_backpack",
	"sophisticatedbackpacks:gold_backpack",
	"sophisticatedbackpacks:iron_backpack",
	"sophisticatedbackpacks:backpack"
]
