[Generation]

[Generation.Ores]
"Generate Copper Ore" = false
"Generate Silver Ore" = false
"Generate Sapphire Ore" = false

[Dragons]

[Dragons.Griefing]
"Dragon Griefing" = 2

[Mobs]

[Mobs.Pixies]
"Pixies Steal Items" = false
