preferredOres = [
  "emendatusenigmatica",
  "minecraft",
  "thermal",
  "immersiveengineering",
  "create",
  "mekanism",
  "kubejs",
  "appliedenergistics2",
  "pneumaticcraft",
  "occultism",
  "industrialforegoing",
  "botania",
  "quark"
]
