[client]

[client.custom_borders]

[client.custom_borders.definitions]
level0_entries = [
	"@overloaded",
	"@minecraft",
	"@gobber2",
	"@extendedcrafting",
	"@chancecubes",
	"@bhc",
	"@advancedperipherals",
	"@computercraft",
	"@artifacts",
	"@emendatusenigmatica",
	"@ftbquests"
]
level1_entries = [
	"@botanicalmachinery",
	"@mythicbotany",
	"@woot",
	"@xreliquary",
	"@psipherals",
	"@psi",
	"@mana-and-artifice",
	"@forbidden_arcanus",
	"@druidcraft",
	"@auraaddons",
	"@occultism",
	"@eidolon",
	"@bloodmagic",
	"@astralsorcery",
	"@losttrinkets",
	"@naturesaura",
	"@botania",
	"@apotheosis"
]
level2_entries = [
	"@iceandfire",
	"@dimdungeons",
	"@doom",
	"@gateways",
	"@twilightforest",
	"@alexsmobs",
	"@darkutils",
	"@aquaculture"
]
level3_entries = [
	"@create",
	"@createaddition",
	"@thermal",
	"@mekanism",
	"@immersiveengineering",
	"@immersivepetroleum",
	"@draconicevolution",
	"@routerreborn",
	"@envirotech",
	"@envirocore",
	"@biggerreactors",
	"@tconstruct",
	"@fluxnetworks",
	"@industrialforegoing",
	"@rftoolspower",
	"@xnet",
	"@rftoolsutility",
	"@rftoolscontrol",
	"@rftoolsbuilder",
	"@rftoolsbase",
	"@pneumaticcraft",
	"@mininggadgets",
	"@mekanismgenerators"
]
level4_entries = [
	"@ae2extras",
	"@storagenetwork",
	"@refinedstorage",
	"@quantumstorage",
	"@compactstorage",
	"@extrastorage",
	"@storagedrawers",
	"@rftoolsstorage",
	"@appliedenergistics2",
	"@extradisks",
	"@compactmachines",
	"@modularrouters",
	"@rsgauges"
]
level5_entries = [
	"@simplefarming",
	"@farmingforblockheads",
	"@farmersdelight",
	"@pamhc2crops",
	"@pamhc2foodcore",
	"@pamhc2foodextended",
	"@pamhc2trees",
	"@nethers_delight",
	"@sushigocrafting",
	"@abnormals_delight",
	"@cookingforblockheads",
	"@botanyports",
	"@agricraft",
	"@ftb-power-pots"
]
level6_entries = [
	"@macawsbridgesbyg",
	"@chisel",
	"@chiselandbits",
	"@chipped",
	"@zycraft",
	"@woodenutilities",
	"@structurize",
	"@dustrial_decor",
	"@prefab",
	"@minecolonies",
	"@mcwlights",
	"@mcwfurnitures",
	"@morecfm",
	"@cfm",
	"@environmental",
	"@constructionwand",
	"@architects_palette",
	"@mcwfences",
	"@upgrade_aquatic",
	"@betterendforge",
	"@supplementaries",
	"@mcwtrpdoors",
	"@pitg",
	"@quark",
	"@valhelsia_structures",
	"@masonry",
	"@mcwwindows",
	"@mcwroofs",
	"@mcwdoors",
	"@mcwbridges",
	"@glassential",
	"@engineersdecor",
	"@decorative_blocks",
	"@connectedglass"
]
level7_entries = [
	"@matc",
	"@mysticalagriculture",
	"@industrialagriculture",
	"@mysticalagradditions",
	"@growablecells"
]
level8_entries = ["@wormhole", "@waystones"]
level9_entries = [
	"@ironfurnaces",
	"@speedyladders",
	"@speedyhoppers",
	"@refinedpipes",
	"@ironcoals",
	"@inventorypets",
	"@engineerstools",
	"@cyclic",
	"@compressium",
	"@cabletiers",
	"@blue_skies",
	"@materialis",
	"@atum",
	"@smallships",
	"@ironjetpacks",
	"@undergarden",
	"@sophisticatedbackpacks",
	"@byg",
	"@rangedpumps",
	"@elevatorid",
	"@comforts"
]
