[power]

[power.mining_gadget]
maxPower = 500000
baseCost = 1000

[power.upgrades]
upgradeSilkCost = 5000
upgradeMagnet = 250
upgradeVoid = 100
upgradeFortune1 = 1000
upgradeFortune2 = 4000
upgradeFortune3 = 6000
upgradeEfficiency1 = 100
upgradeEfficiency2 = 200
upgradeEfficiency3 = 450
upgradeEfficiency4 = 1200
upgradeEfficiency5 = 3500
upgradeLight = 500
upgradeFreeze = 500
battery1 = 4800000
battery2 = 19200000
battery3 = 76800000
