[general]
oreExceptions = [
	"emendatusenigmatica:iridium_ore",
	"create:copper_ore",
	"create:zinc_ore",
	"eidolon:lead_ore",
	"immersiveengineering:ore_aluminum",
	"immersiveengineering:ore_copper",
	"immersiveengineering:ore_lead",
	"immersiveengineering:ore_nickel",
	"immersiveengineering:ore_silver",
	"immersiveengineering:ore_uranium",
	"mapperbase:bitumen_ore",
	"mekanism:copper_ore",
	"mekanism:fluorite_ore",
	"mekanism:lead_ore",
	"mekanism:osmium_ore",
	"mekanism:tin_ore",
	"mekanism:uranium_ore",
	"thermal:apatite_ore",
	"thermal:copper_ore",
	"thermal:nickel_ore",
	"thermal:lead_ore",
	"thermal:ruby_ore",
	"thermal:sapphire_ore",
	"thermal:silver_ore",
	"thermal:sulfur_ore",
	"thermal:tin_ore",
	"tmechworks:aluminum_ore",
	"tmechworks:copper_ore",
	"undergarden:coal_ore",
	"undergarden:diamond_ore",
	"undergarden:gold_ore",
	"undergarden:iron_ore"
]
additionalOres = [
	"forge:ores/nether/gold->1000->nether",
	"forge:ores/netherite_scrap->1->nether",
	"forge:ores/bitumen->1000->overworld",
	"forge:ores/fluorite->50->overworld",
	"forge:ores/potassium_nitrate->500->overworld",
	"forge:ores/mana->500->overworld",
	"forge:ores/sulfur->300->overworld"
]
auraTypeOverrides = [
	"undergarden:undergarden->naturesaura:end",
	"atum:atum->naturesaura:overworld"
]
fieldCreatorRange = 10
