[general]
"Enable 'q' Button" = false
"Ignored Screens" = [
	"com.tfar.craftingstation.client.CraftingStationScreen",
	"com.refinedmods.refinedstorage.screen.grid.GridScreen",
	"appeng.client.gui.implementations.CraftingTermScreen",
	"appeng.client.gui.implementations.PatternTermScreen",
	"blusunrize.immersiveengineering.client.gui.CraftingTableScreen",
	"wile.engineersdecor.blocks.EdCraftingTable$CraftingTableGui",
	"me.desht.pneumaticcraft.client.gui.semiblock.GuiLogisticsRequester",
	"me.desht.pneumaticcraft.client.gui.semiblock.GuiLogisticsStorage",
	"me.desht.pneumaticcraft.client.gui.semiblock.GuiLogisticsProvider",
	"me.desht.modularrouters.client.gui.filter.GuiFilterScreen",
	"com.resourcefulbees.resourcefulbees.client.gui.screen.CentrifugeScreen",
	"com.resourcefulbees.resourcefulbees.client.gui.screen.MechanicalCentrifugeScreen",
	"com.resourcefulbees.resourcefulbees.client.gui.screen.CentrifugeMultiblockScreen",
	"com.refinedmods.refinedstorage.screen.FilterScreen",
	"slimeknights.tconstruct.tables.client.inventory.table.CraftingStationScreen",
	"slimeknights.tconstruct.tables.client.inventory.TinkerChestScreen",
	"slimeknights.tconstruct.smeltery.client.inventory.HeatingStructureScreen",
	"team.chisel.client.gui.GuiChisel",
	"team.chisel.client.gui.GuiHitechChisel",
	"me.desht.modularrouters.client.gui.filter.GuiBulkItemFilter",
	"link.infra.demagnetize.blocks.DemagnetizerContainer",
	"com.simibubi.create.content.logistics.block.inventories.AdjustableCrateScreen",
	"com.ticticboooom.mods.mm.client.screen.PortBlockContainerScreen"
]

[categories]
Oddities = false

[automation]
"Pistons Move Tile Entities" = false

[automation.pistons_move_tile_entities]
"Movement Blacklist" = [
	"minecraft:spawner",
	"integrateddynamics:cable",
	"randomthings:blockbreaker",
	"minecraft:ender_chest",
	"minecraft:enchanting_table",
	"minecraft:trapped_chest",
	"quark:spruce_trapped_chest",
	"quark:birch_trapped_chest",
	"quark:jungle_trapped_chest",
	"quark:acacia_trapped_chest",
	"quark:dark_oak_trapped_chest"
]

[building]

[building.variant_chests]
"Replace Worldgen Chests" = false

[building.tallow_and_candles]
"Max Drop" = 0
"Enchant Power" = 0.5
"Min Drop" = 0

[management]
"Inventory Sorting" = false

[management.inventory_sorting]
"Enable Chests" = false
"Enable Player Inventory In Chests" = false
"Enable Player Inventory" = false

[tools]
"Seed Pouch" = false

[tools.trowel]
"Trowel Max Durability" = 255

[tools.color_runes]
"Apply Cost" = 15

[tweaks]
"Compasses Work Everywhere" = false
"Glass Shard" = false
"Lava Bucket As Trash" = false

[tweaks.sign_editing]
"Requires Empty Hand" = true

[tweaks.utility_recipes]
"Dye Any Wool" = false
"Bone Meal Utility" = false

[tweaks.improved_sleeping]
"Percent Req" = 0.25

[world]
Crevices = false
Biotite = false
"Big Stone Clusters" = false
"Cave Roots" = false

[world.monster_box]
"Search Range" = 4

[world.new_stone_types]

[world.new_stone_types.marble]

[world.new_stone_types.marble.oregen]
"Cluster Size" = 32
"Cluster Count" = 3

[world.new_stone_types.limestone]

[world.new_stone_types.limestone.oregen]
"Cluster Count" = 0
"Cluster Size" = 32

[world.new_stone_types.voidstone]

[world.new_stone_types.voidstone.oregen]
"Cluster Count" = 0

[world.new_stone_types.voidstone.dimensions]
Dimensions = ["minecraft:the_nether"]

[world.new_stone_types.slate]

[world.new_stone_types.slate.oregen]
"Cluster Count" = 3
"Cluster Size" = 32

[world.new_stone_types.jasper]

[world.new_stone_types.jasper.oregen]
"Cluster Count" = 3
"Cluster Size" = 32

[world.blossom_trees]

[world.blossom_trees.orange]
Rarity = 200

[world.blossom_trees.pink]
Rarity = 200

[world.blossom_trees.lavender]
Rarity = 200

[mobs]

[mobs.toretoise]

[mobs.toretoise.spawn_config]
"Spawn Weight" = 40

[mobs.foxhound]

[mobs.foxhound.spawn_config]
"Spawn Weight" = 10

[mobs.frogs]

[mobs.frogs.spawn_config]
"Spawn Weight" = 3

[client]

[client.improved_tooltips]
"Food Tooltips" = false
"Enchanting Tooltips" = false

[client.greener_grass]
"Block List" = [
	"minecraft:large_fern",
	"minecraft:tall_grass",
	"minecraft:grass_block",
	"minecraft:fern",
	"minecraft:grass",
	"minecraft:potted_fern",
	"minecraft:sugar_cane"
]
"Leaves List" = [
	"minecraft:spruce_leaves",
	"minecraft:birch_leaves",
	"minecraft:oak_leaves",
	"minecraft:jungle_leaves",
	"minecraft:acacia_leaves",
	"minecraft:dark_oak_leaves",
	"minecraft:vine"
]
