[scaffoldingpower]

[scaffoldingpower.ladder]
autoBuildRange = 16

[scaffoldingpower.rails]
autoBuildRange = 16

[scaffoldingpower.redstone]
autoBuildRange = 16

[scaffoldingpower.doors]
doubleOpen = false
