[steam]
HuPerFuelTick = 24

[flywheel]

[flywheel.bronze_flywheel]
bronzeFlywheelCapacity = 512

[flywheel.cast_iron_flywheel]
castIronFlywheelCapacity = 1024

[flywheel.steel_flywheel]
steelFlywheelCapacity = 2048
