[initialization]

[initialization.general]
custom_configured_screen = false

[initialization.blocks]
sack = false
amethyst_arrow = true
stone_lamp = false
crank = false
pedestal = false
blackboard = false
turn_table = false
