[structures]

[structures.global]
flatness_delta = 3
blacklisted_dimensions = [
	"minecraft:the_nether",
	"minecraft:the_end",
	"undergarden:undergarden",
	"atum:atum",
	"compactmachines:compact_world",
	"mythicbotany:alfheim"
]
