[common]

[common.villagegen]

[common.villagegen.worldgen]
worldGenDimensionAllowList = []

[common.villagegen.namegen]
customWaystoneNames = [
	"Sandy City",
	"Chocolate Island",
	"Sahara",
	"The Perimeter",
	"Pacific"
]
