["When Configurations Arise"]

["When Configurations Arise"."Campsite Structures"]

["When Configurations Arise"."Fortified Structures"."Thornborn Towers Spawning Settings"]
thornbornTowersSize = 50

["When Configurations Arise"."Enigmatic Structures"."Small Blimp Spawning Settings"]
smallBlimpSize = 50

["When Configurations Arise"."Fungi Structures"."Mushroom Mines Spawning Settings"]
mushroomMinesGenerates = false

["When Configurations Arise"."Haunted Structures"]

["When Configurations Arise"."Haunted Structures"."Infested Temple Spawning Settings"]
infestedTempleGenerates = false

["When Configurations Arise"."Haunted Structures"."Plague Asylum Spawning Settings"]
plagueAsylumGenerates = false

["When Configurations Arise"."Eerie Structures"]

["When Configurations Arise"."Eerie Structures"."Heavenly Rider Spawning Settings"]
heavenlyRiderGenerates = false

["When Configurations Arise"."Eerie Structures"."Heavenly Conqueror Spawning Settings"]
heavenlyConquerorGenerates = false

["When Configurations Arise"."Eerie Structures"."Heavenly Challenger Spawning Settings"]
heavenlyChallengerGenerates = false

["When Configurations Arise"."Underworld Structures"]

["When Configurations Arise"."Underworld Structures"."Mining System Spawning Settings"]
miningSystemGenerates = false

["When Configurations Arise"."Underworld Structures"."Scorched Mines Spawning Settings"]
scorchedMinesGenerates = false

["When Configurations Arise"."Underworld Structures"."Foundry Spawning Settings"]
foundrySeparation = 40
