[MachineGeneratorConfig]

[MachineGeneratorConfig.BioReactorConfig]
maxProgress = 7200
powerPerOperation = 2000000
maxStoredPower = 20000000

[MachineGeneratorConfig.BiofuelGeneratorConfig]
powerPerTick = 500
maxStoredPower = 500000
