[MachineMiscConfig]

[MachineMiscConfig.StasisChamberConfig]
powerPerOperation = 1500000
maxStoredPower = 300000000

[MachineMiscConfig.EnchantmentFactoryConfig]
powerPerTick = 50000
maxStoredPower = 5000000

[MachineMiscConfig.EnchantmentSorterConfig]
powerPerTick = 150

[MachineMiscConfig.EnchantmentExtractorConfig]
powerPerTick = 5000
maxStoredPower = 5000000

[MachineMiscConfig.EnchantmentApplicatorConfig]
powerPerTick = 5000
maxStoredPower = 5000000
