[MachineResourceProductionConfig]

[MachineResourceProductionConfig.MaterialStoneWorkFactoryConfig]
powerPerTick = 2000
maxStoredPower = 200000

[MachineResourceProductionConfig.ResourcefulFurnaceConfig]
powerPerTick = 800

[MachineResourceProductionConfig.MechanicalDirtConfig]
powerPerOperation = 8000
maxStoredPower = 800000

[MachineResourceProductionConfig.SludgeRefinerConfig]
powerPerTick = 2500
maxStoredPower = 50000
maxSludgeTankSize = 16000

[MachineResourceProductionConfig.FluidCollectorConfig]
powerPerOperation = 100

[MachineResourceProductionConfig.WashingFactoryConfig]
maxProgress = 90
powerPerTick = 400
maxStoredPower = 20000
maxOutputSize = 16000

[MachineResourceProductionConfig.MarineFisherConfig]
powerPerOperation = 20000
maxStoredPower = 2000000

[MachineResourceProductionConfig.SporeRecreatorConfig]
powerPerTick = 1000
maxStoredPower = 100000
maxWaterTankSize = 8000

[MachineResourceProductionConfig.LaserDrillConfig]
maxProgress = 100
powerPerOperation = 500000
maxStoredPower = 50000000

[MachineResourceProductionConfig.OreLaserBaseConfig]
maxProgress = 200

[MachineResourceProductionConfig.FermentationStationConfig]
powerPerTick = 400
maxStoredPower = 20000
ticksFor2XProduction = 300
ticksFor3XProduction = 600
ticksFor4XProduction = 3600

[MachineResourceProductionConfig.FluidSievingMachineConfig]
maxProgress = 90
powerPerTick = 400

[MachineResourceProductionConfig.HydroponicBedConfig]
powerPerOperation = 500
maxStoredPower = 50000
