[MachineAgricultureHusbandryConfig]

[MachineAgricultureHusbandryConfig.MobCrusherConfig]
powerPerOperation = 50000
maxStoredPower = 5000000

[MachineAgricultureHusbandryConfig.MobDuplicatorConfig]
maxProgress = 50
powerPerOperation = 2500000
maxStoredPower = 250000000

[MachineAgricultureHusbandryConfig.WitherBuilderConfig]
maxProgress = 100
powerPerOperation = 500000
maxStoredPower = 50000000
