onEvent('recipes', event => {
    event.smelting('minecraft:black_stained_glass', 'minecraft:black_concrete_powder').id('monumental:black_stained_glass')
    event.smelting('minecraft:blue_stained_glass', 'minecraft:blue_concrete_powder').id('monumental:blue_stained_glass')
    event.smelting('minecraft:brown_stained_glass', 'minecraft:brown_concrete_powder').id('monumental:brown_stained_glass')
    event.smelting('minecraft:cyan_stained_glass', 'minecraft:cyan_concrete_powder').id('monumental:cyan_stained_glass')
    event.smelting('minecraft:gray_stained_glass', 'minecraft:gray_concrete_powder').id('monumental:gray_stained_glass')
    event.smelting('minecraft:green_stained_glass', 'minecraft:green_concrete_powder').id('monumental:green_stained_glass')
    event.smelting('minecraft:light_blue_stained_glass', 'minecraft:light_blue_concrete_powder').id('monumental:light_blue_stained_glass')
    event.smelting('minecraft:light_gray_stained_glass', 'minecraft:light_gray_concrete_powder').id('monumental:light_gray_stained_glass')
    event.smelting('minecraft:lime_stained_glass', 'minecraft:lime_concrete_powder').id('monumental:lime_stained_glass')
    event.smelting('minecraft:magenta_stained_glass', 'minecraft:magenta_concrete_powder').id('monumental:magenta_stained_glass')
    event.smelting('minecraft:orange_stained_glass', 'minecraft:orange_concrete_powder').id('monumental:orange_stained_glass')
    event.smelting('minecraft:pink_stained_glass', 'minecraft:pink_concrete_powder').id('monumental:pink_stained_glass')
    event.smelting('minecraft:purple_stained_glass', 'minecraft:purple_concrete_powder').id('monumental:purple_stained_glass')
    event.smelting('minecraft:red_stained_glass', 'minecraft:red_concrete_powder').id('monumental:red_stained_glass')
    event.smelting('minecraft:yellow_stained_glass', 'minecraft:yellow_concrete_powder').id('monumental:yellow_stained_glass')
    event.smelting('minecraft:white_stained_glass', 'minecraft:white_concrete_powder').id('monumental:white_stained_glass')
    event.smelting('#forge:nuggets/iron', 'dustrial_decor:rusty_iron_nugget').id('monumental:dustrial_decor_to_iron_nugget')
    event.smelting('#forge:ingots/iron', 'dustrial_decor:rusty_iron_ingot').id('monumental:dustrial_decor_to_iron_ingot')
    event.smelting('#forge:plates/iron', 'dustrial_decor:rusty_sheet_metal').id('monumental:dustrial_decor_to_iron_plate')
    event.smelting('7x emendatusenigmatica:tin_nugget', 'aquaculture:tin_can').id('monumental:tin_can_to_iron_nugget')
    event.smelting('1x emendatusenigmatica:charged_certus_quartz_gem', '#forge:chunks/charged_certus_quartz').id('appliedenergistics2:charged_certus_to_crystal')
    event.smelting('1x emendatusenigmatica:certus_quartz_gem', '#forge:chunks/certus_quartz').id('appliedenergistics2:certus_to_crystal')
    event.smelting('1x emendatusenigmatica:cinnabar_gem', '#forge:chunks/cinnabar').id('emendatusenigmatica:cinnabar_chunks_to_gem')
    event.smelting('1x emendatusenigmatica:apatite_gem', '#forge:chunks/apatite').id('emendatusenigmatica:apatite_chunks_to_gem')
    event.smelting('1x emendatusenigmatica:sulfur_gem', '#forge:chunks/sulfur').id('emendatusenigmatica:sulfur_chunks_to_gem')
    event.smelting('1x emendatusenigmatica:dimensional_gem', '#forge:chunks/dimensional').id('emendatusenigmatica:dimensional_chunks_to_gem')
})