[gear]

[gear.mekasuit]
energyUsageGravitationalModulation = "250000"
energyUsageMagicReduce = "250000"
baseJumpEnergyUsage = "50000"
energyUsageVisionEnhancement = "7000"
solarRechargingRate = "7000"
energyUsageItemAttraction = "25000"
energyUsageSprintBoost = "25000"
jetpackMaxStorage = 256000
jetpackTransferRate = 512
energyUsagePotionTick = "250000"
baseEnergyCapacity = "8000000"
energyUsageDamage = "250000"
nutritionalTransferRate = 512
energyUsageNutritionalInjection = "50000"

[gear.atomic_disassembler]
veinMining = true

[gear.electric_bow]
energyUsage = "1200"

[gear.jetpack]

[gear.jetpack.armored]
armor = 7
toughness = 0.0
