[generators]
advancedSolarGeneration = "640"
energyPerFusionFuel = "550000"
solarGeneration = "80"

[generators.wind_generator]
windGenerationMaxY = 90
windGenerationMax = "300"
windGenerationMinY = 40

[generators.fusion_reactor]
thermocoupleEfficiency = 0.014
