[general]
cardboardModBlacklist = [
	"refinedstorage",
	"tetra",
	"storagedrawers",
	"lootr",
	"extrastorage",
	"astralsorcery",
	"waystones",
	"powah",
	"pneumaticcraft",
	"bloodmagic",
	"occultism",
	"eidolon"
]

[general.thermal_evaporation]
tempMultiplier = 0.8

[general.energy_conversion]
maxEnergyPerSteam = "4"

[general.security]
opsBypassRestrictions = true

[general.radiation]
radiationEnabled = false
radioactiveWasteBarrelProcessTicks = 1200
radioactiveWasteBarrelDecayAmount = 100
