[usage]
digitalMiner = "5000"
energizedSmelter = "160"
laser = "500000"
modificationStation = "2000"
chemicalInjectionChamber = "4000"
crusher = "2000"
pressurizedReactionBase = "500"
formulaicAssemblicator = "50"
precisionSawmill = "2000"
metallurgicInfuser = "2000"
purificationChamber = "2000"
chemicalCrystallizer = "2000"
fluidicPlenisher = "50"
electricPump = "50"
enrichmentChamber = "2000"
chemicalDissolutionChamber = "4000"
chemicalWasher = "640"

[usage.teleporter]
teleporterDistance = "50"
teleporterDimensionPenalty = "50000"
teleporterBase = "5000"
