[storage]
rotaryCondensentrator = "400000"
nutritionalLiquifier = "400000"
digitalMiner = "5000000"
energizedSmelter = "400000"
seismicVibrator = "400000"
isotopicCentrifuge = "800000"
laser = "5000000"
modificationStation = "400000"
chemicalInjectionChamber = "400000"
crusher = "400000"
pressurizedReactionBase = "400000"
chemicalInfuser = "800000"
formulaicAssemblicator = "400000"
osmiumCompressor = "400000"
precisionSawmill = "400000"
metallurgicInfuser = "400000"
purificationChamber = "800000"
oxidationChamber = "800000"
chemicalCrystallizer = "400000"
fluidicPlenisher = "400000"
chargePad = "5000000"
electrolyticSeparator = "400000"
electricPump = "400000"
enrichmentChamber = "400000"
chemicalDissolutionChamber = "400000"
chemicalWasher = "800000"
