ServerEvents.tags('item', e => {
  //#region ADDITIONS
  //e.add('chipped:glowstone', /rechiseled:glowstone_/)
  //e.add('forge:beach_grass', 'upgrade_aquatic:beachgrass')
  e.add('forge:plastic', 'pneumaticcraft:plastic')
  e.add('forge:sheetmetals/copper', 'createdeco:copper_sheet_metal')
  e.add('forge:nuggets/ender_pearl', 'extendedcrafting:ender_nugget')
  e.add('forge:blocks/quartz', [/rechiseled:quartz_block/, /chipped:quartz_block/])
  //e.add('forge:blood', ['betteranimalsplus:horseshoe_crab_blood', 'mythicbotany:kvasir_blood', 'twilightforest:fiery_blood'])
  //e.add('forge:bones/wither', 'tconstruct:necrotic_bone')
  e.add('forge:bricks/nether', [/rechiseled:nether_bricks/, /chipped:nether_bricks/])
  //e.add('forge:candles', [/quark:[a-z_]*_candle/, 'eidolon:candle', 'eidolon:candlestick', 'occultism:candle_white', 'supplementaries:candelabra', 'supplementaries:candelabra_silver', 'supplementaries:candle_holder'])
  e.add('forge:cauldron', ['minecraft:cauldron', 'reliquary:apothecary_cauldron'])
  e.add('forge:chains', ['minecraft:chain', 'decorative_blocks:chain'])
  e.add('forge:bowls', ['minecraft:bowl', 'occultism:sacrificial_bowl'])
  e.add('minecraft:beds', 'undergarden:depthrock_bed')
  e.add('forge:chunks/coal', 'ironcoals:base_coal_chunk')
  e.add('forge:clocks', ['create:cuckoo_clock', 'rftoolsutility:clock_module'])
  e.add('forge:corals', [/\w+:(?!dead)(\w+)_coral$/])
  e.add('forge:coral_blocks', [/\w+:(?!dead)(\w+)_coral_block$/])
  e.add('forge:coral_fans', [/\w+:(?!dead)(\w+)_coral_fan$/])
  e.add('forge:dead_corals', [/dead_\w+coral$/])
  e.add('forge:dead_coral_blocks', [/dead_\w+coral_block$/])
  e.add('forge:dead_coral_fans', [/dead_\w+coral_fan$/])
  e.add('forge:end_stones', /rechiseled:end_stone/)
  e.add('forge:furnace', [/minecraft:.+_furnace/, /engineersdecor:small_.+_furnace/, 'ironfurnaces:item_spooky', 'ironfurnaces:item_xmas', 'mysticalagriculture:inferium_furnace', 'mysticalagriculture:prudentium_furnace', 'mysticalagriculture:tertium_furnace', 'mysticalagriculture:imperium_furnace', 'mysticalagriculture:supremium_furnace'])
  e.add('forge:hopper', ['minecraft:hopper', 'cyclic:hopper_fluid', 'cyclic:hopper_gold', 'naturesaura:grated_chute', 'pneumaticcraft:omnidirectional_hopper', 'pneumaticcraft:liquid_hopper'])
  e.add('forge:mushroom_caps', ['undergarden:blood_mushroom_cap', 'undergarden:ink_mushroom_cap', 'undergarden:veil_mushroom_cap', 'undergarden:indigo_mushroom_cap'])
  e.add('forge:mushroom_colonies/brown', 'aquaculture:brown_shrooma')
  e.add('forge:mushroom_colonies/red', 'aquaculture:red_shrooma')
  e.add('forge:netherbricks/red', 'quark:netherrack_bricks', /rechiseled:red_nether_bricks/)
  e.add('forge:netherrack', [/rechiseled:netherrack_/])
  e.add('forge:piston', ['minecraft:sticky_piston', 'minecraft:piston', 'create:mechanical_piston', 'create:sticky_mechanical_piston', 'multipiston:multipistonblock'])
  e.add('forge:sandstone/red', /rechiseled:red_sandstone/)
  e.add('forge:sandstone/colorless', /rechiseled:sandstone_/)
  e.add('forge:eyes', ['minecraft:ender_eye', 'greater_eye:greater_eye', 'greater_eye:greater_eye_nether', 'greater_eye:greater_eye_end', 'cyclic:ender_eye_reuse', 'reliquary:salamander_eye', 'alexsmobs:void_worm_eye', 'alexsmobs:guster_eye', 'naturesaura:outpost_finder', 'naturesaura:fortress_finder', 'naturesaura:eye', 'naturesaura:end_city_finder'])
  e.add('forge:stone', /rechiseled:stone_/)
  e.add('forge:cobblestone', /rechiseled:cobblestone_/)
  //e.add('forge:slime_block', ['#tconstruct:slime_block', '#quark:slime_blocks'])
  //e.add('forge:tallow', ['quark:tallow', 'eidolon:tallow', 'occultism:tallow'])
  e.add('forge:tanks/empty', ['naturesaura:color_changer', 'forbidden_arcanus:edelwood_bucket', 'blue_skies:ventium_bucket'])
  e.add('forge:buckets/empty', ['naturesaura:color_changer', 'forbidden_arcanus:edelwood_bucket', 'blue_skies:ventium_bucket'])
  e.add('forge:tools/hammer', ['alltheores:copper_ore_hammer', 'alltheores:iron_ore_hammer', 'alltheores:bronze_ore_hammer', 'alltheores:invar_ore_hammer', 'alltheores:platinum_ore_hammer', 'framedblocks:framed_hammer', 'mcwroofs:roofing_hammer', 'blue_skies:crushing_hammer', 'gobber2:gobber2_hammer_nether', 'gobber2:gobber2_hammer_end', 'doom:sentinelhammer'])
  e.add('forge:tools/pickaxes', /blue_skies:.*_pickaxe/, /mysticalagriculture:.*_pickaxe/, /create_sa:.*_pickaxe/)
  e.add('forge:tools/hoes', [/naturesaura:.*_hoe/, /blue_skies:.*_hoe/, /mysticalagriculture:.*_hoe/, /aquaculture:.*_hoe/, /ae2:.*_hoe/, /forbidden_arcanus:.*_hoe/, /create_sa:.*_hoe/])
  e.add('forge:tools/swords', /blue_skies:.*_sword/, /mysticalagriculture:.*_sword/, /create_sa:.*_sword/, /forbidden_arcanus:.*_sword/, /ae2:.*_sword/, /immersiveengineering:.*sword_/)
  e.add('forge:tools/wrench', ['refinedstorage:wrench'])
  e.add('forge:workbenches', ['minecraft:crafting_table', /blue_skies:\w+_crafting_table/])
  e.add('forge:workbench', ['minecraft:crafting_table', /blue_skies:\w+_crafting_table/])
  //e.add('upgrade_aquatic:driftwood_logs', 'aquaculture:driftwood')

  //let realms = ['asgard', 'vanaheim', 'alfheim', 'midgard', 'joetunheim', 'muspelheim', 'niflheim', 'nidavellir', 'helheim']
  //realms.forEach(realm => e.add(`botania:runes/${realm}`, `mythicbotany:${realm}_rune`))
  //#endregion

  //#region REMOVALS
  e.remove('forge:string', 'undergarden:twistytwig')
  //#endregion
})
