onEvent('recipes', event => {    
    //Atum

    event.smithing(Item.of('atum:limestone_hoe'), 'minecraft:stone_hoe', 'atum:limestone_cracked')
    event.smithing(Item.of('atum:limestone_sword'), 'minecraft:stone_sword', 'atum:limestone_cracked')
    event.smithing(Item.of('atum:stoneguard_sword'), 'minecraft:stone_sword', '#forge:ingots/khnumite')
    event.smithing(Item.of('atum:stoneguard_greatsword'), 'atum:stoneguard_sword', '#forge:ingots/khnumite')
    event.smithing(Item.of('atum:desert_chest_iron'), 'atum:wanderer_chest', 'minecraft:iron_chestplate')
    event.smithing(Item.of('atum:desert_chest_gold'), 'atum:wanderer_chest', 'minecraft:golden_chestplate')
    event.smithing(Item.of('atum:desert_chest_diamond'), 'atum:wanderer_chest', 'minecraft:diamond_chestplate')
    event.smithing(Item.of('atum:desert_helmet_iron'), 'atum:wanderer_helmet', 'minecraft:iron_helmet')
    event.smithing(Item.of('atum:desert_helmet_gold'), 'atum:wanderer_helmet', 'minecraft:golden_helmet')
    event.smithing(Item.of('atum:desert_helmet_diamond'), 'atum:wanderer_helmet', 'minecraft:diamond_helmet')
    event.smithing(Item.of('atum:desert_legs_iron'), 'atum:wanderer_legs', 'minecraft:iron_leggings')
    event.smithing(Item.of('atum:desert_legs_gold'), 'atum:wanderer_legs', 'minecraft:golden_leggings')
    event.smithing(Item.of('atum:desert_legs_diamond'), 'atum:wanderer_legs', 'minecraft:diamond_leggings')
    event.smithing(Item.of('atum:desert_boots_iron'), 'atum:wanderer_boots', 'minecraft:iron_boots')
    event.smithing(Item.of('atum:desert_boots_gold'), 'atum:wanderer_boots', 'minecraft:golden_boots')
    event.smithing(Item.of('atum:desert_boots_diamond'), 'atum:wanderer_boots', 'minecraft:diamond_boots')

    // Aiot Botania
    
    event.smithing(Item.of('aiotbotania:livingwood_axe'), 'minecraft:wooden_axe', '#botania:livingwood')
    event.smithing(Item.of('aiotbotania:livingrock_axe'), 'minecraft:stone_axe', '#botania:livingrock')
    event.smithing(Item.of('aiotbotania:livingwood_shovel'), 'minecraft:wooden_shovel', '#botania:livingwood')
    event.smithing(Item.of('aiotbotania:livingrock_shovel'), 'minecraft:stone_shovel', '#botania:livingrock')
    event.smithing(Item.of('aiotbotania:livingwood_hoe'), 'minecraft:wooden_hoe', '#botania:livingwood')
    event.smithing(Item.of('aiotbotania:livingrock_hoe'), 'minecraft:stone_hoe', '#botania:livingrock')
    event.smithing(Item.of('aiotbotania:livingwood_sword'), 'minecraft:wooden_sword', '#botania:livingwood')
    event.smithing(Item.of('aiotbotania:livingrock_sword'), 'minecraft:stone_sword', '#botania:livingrock')
    event.smithing(Item.of('aiotbotania:livingwood_pickaxe'), 'minecraft:wooden_pickaxe', '#botania:livingwood')
    event.smithing(Item.of('aiotbotania:livingrock_pickaxe'), 'minecraft:stone_pickaxe', '#botania:livingrock')
    event.smithing(Item.of('aiotbotania:terra_hoe'), 'minecraft:netherite_hoe', '#forge:ingots/terrasteel')

    //Aquaculture
    
    event.smithing(Item.of('aquaculture:neptunium_pickaxe'), 'minecraft:netherite_pickaxe', '#forge:ingots/neptunium')
    event.smithing(Item.of('aquaculture:neptunium_chestplate'), 'minecraft:netherite_chestplate', '#forge:ingots/neptunium')
    event.smithing(Item.of('aquaculture:neptunium_sword'), 'minecraft:netherite_sword', '#forge:ingots/neptunium')
    event.smithing(Item.of('aquaculture:neptunium_axe'), 'minecraft:netherite_axe', '#forge:ingots/neptunium')
    event.smithing(Item.of('aquaculture:neptunium_shovel'), 'minecraft:netherite_shovel', '#forge:ingots/neptunium')
    event.smithing(Item.of('aquaculture:neptunium_hoe'), 'minecraft:netherite_hoe', '#forge:ingots/neptunium')
    event.smithing(Item.of('aquaculture:neptunium_helmet'), 'minecraft:netherite_helmet', '#forge:ingots/neptunium')
    event.smithing(Item.of('aquaculture:neptunium_leggings'), 'minecraft:netherite_leggings', '#forge:ingots/neptunium')
    event.smithing(Item.of('aquaculture:neptunium_boots'), 'minecraft:netherite_boots', '#forge:ingots/neptunium')
    event.smithing(Item.of('aquaculture:neptunium_bow'), '#forge:string', '#forge:ingots/neptunium')

    //Appliedenergistics2
    
    event.smithing(Item.of('appliedenergistics2:certus_quartz_axe'), 'minecraft:iron_axe', '#forge:gems/certus_quartz')
    event.smithing(Item.of('appliedenergistics2:nether_quartz_axe'), 'minecraft:iron_axe', '#forge:gems/quartz')
    event.smithing(Item.of('appliedenergistics2:certus_quartz_shovel'), 'minecraft:iron_shovel', '#forge:gems/certus_quartz')
    event.smithing(Item.of('appliedenergistics2:nether_quartz_shovel'), 'minecraft:iron_shovel', '#forge:gems/quartz')
    event.smithing(Item.of('appliedenergistics2:certus_quartz_hoe'), 'minecraft:iron_hoe', '#forge:gems/certus_quartz')
    event.smithing(Item.of('appliedenergistics2:nether_quartz_hoe'), 'minecraft:iron_hoe', '#forge:gems/quartz')
    event.smithing(Item.of('appliedenergistics2:certus_quartz_sword'), 'minecraft:iron_sword', '#forge:gems/certus_quartz')
    event.smithing(Item.of('appliedenergistics2:nether_quartz_sword'), 'minecraft:iron_sword', '#forge:gems/quartz')
    event.smithing(Item.of('appliedenergistics2:certus_quartz_pickaxe'), 'minecraft:iron_pickaxe', '#forge:gems/certus_quartz')
    event.smithing(Item.of('appliedenergistics2:nether_quartz_pickaxe'), 'minecraft:iron_pickaxe', '#forge:gems/quartz')
    
    //Blue Skies

    event.smithing(Item.of('blue_skies:horizonite_boots'), 'minecraft:diamond_boots', '#blue_skies:ingots/horizonite')
    event.smithing(Item.of('blue_skies:charoite_boots'), 'minecraft:diamond_boots', '#blue_skies:gems/charoite')
    event.smithing(Item.of('blue_skies:diopside_boots'), 'minecraft:netherite_boots', '#blue_skies:gems/diopside')
    event.smithing(Item.of('blue_skies:aquite_boots'), 'minecraft:diamond_boots', '#blue_skies:gems/aquite')
    event.smithing(Item.of('blue_skies:pyrope_boots'), 'minecraft:iron_boots', '#blue_skies:gems/pyrope')
    event.smithing(Item.of('blue_skies:shadow_boots'), 'minecraft:golden_boots', '#forge:ingots/shadow_steel')
    event.smithing(Item.of('blue_skies:horizonite_axe'), 'minecraft:diamond_axe', '#blue_skies:ingots/horizonite')
    event.smithing(Item.of('blue_skies:charoite_axe'), 'minecraft:diamond_axe', '#blue_skies:gems/charoite')
    event.smithing(Item.of('blue_skies:diopside_axe'), 'minecraft:netherite_axe', '#blue_skies:gems/diopside')
    event.smithing(Item.of('blue_skies:aquite_axe'), 'minecraft:diamond_axe', '#blue_skies:gems/aquite')
    event.smithing(Item.of('blue_skies:pyrope_axe'), 'minecraft:iron_axe', '#blue_skies:gems/pyrope')
    event.smithing(Item.of('blue_skies:lunar_stone_axe'), 'minecraft:stone_axe', 'blue_skies:lunar_cobblestone')
    event.smithing(Item.of('blue_skies:turquoise_stone_axe'), 'minecraft:stone_axe', 'blue_skies:turquoise_cobblestone')
    event.smithing(Item.of('blue_skies:cherry_axe'), 'minecraft:wooden_axe', 'blue_skies:cherry_planks')
    event.smithing(Item.of('blue_skies:maple_axe'), 'minecraft:wooden_axe', 'blue_skies:maple_planks')
    event.smithing(Item.of('blue_skies:frostbright_axe'), 'minecraft:wooden_axe', 'blue_skies:frostbright_planks')
    event.smithing(Item.of('blue_skies:dusk_axe'), 'minecraft:wooden_axe', 'blue_skies:dusk_planks')
    event.smithing(Item.of('blue_skies:starlit_axe'), 'minecraft:wooden_axe', 'blue_skies:starlit_planks')
    event.smithing(Item.of('blue_skies:lunar_axe'), 'minecraft:wooden_axe', 'blue_skies:lunar_planks')
    event.smithing(Item.of('blue_skies:bluebright_axe'), 'minecraft:wooden_axe', 'blue_skies:bluebright_planks')
    event.smithing(Item.of('blue_skies:horizonite_shovel'), 'minecraft:diamond_shovel', '#blue_skies:ingots/horizonite')
    event.smithing(Item.of('blue_skies:charoite_shovel'), 'minecraft:diamond_shovel', '#blue_skies:gems/charoite')
    event.smithing(Item.of('blue_skies:diopside_shovel'), 'minecraft:netherite_shovel', '#blue_skies:gems/diopside')
    event.smithing(Item.of('blue_skies:aquite_shovel'), 'minecraft:diamond_shovel', '#blue_skies:gems/aquite')
    event.smithing(Item.of('blue_skies:pyrope_shovel'), 'minecraft:iron_shovel', '#blue_skies:gems/pyrope')
    event.smithing(Item.of('blue_skies:lunar_stone_shovel'), 'minecraft:stone_shovel', 'blue_skies:lunar_cobblestone')
    event.smithing(Item.of('blue_skies:turquoise_stone_shovel'), 'minecraft:stone_shovel', 'blue_skies:turquoise_cobblestone')
    event.smithing(Item.of('blue_skies:cherry_shovel'), 'minecraft:wooden_shovel', 'blue_skies:cherry_planks')
    event.smithing(Item.of('blue_skies:maple_shovel'), 'minecraft:wooden_shovel', 'blue_skies:maple_planks')
    event.smithing(Item.of('blue_skies:frostbright_shovel'), 'minecraft:wooden_shovel', 'blue_skies:frostbright_planks')
    event.smithing(Item.of('blue_skies:dusk_shovel'), 'minecraft:wooden_shovel', 'blue_skies:dusk_planks')
    event.smithing(Item.of('blue_skies:starlit_shovel'), 'minecraft:wooden_shovel', 'blue_skies:starlit_planks')
    event.smithing(Item.of('blue_skies:lunar_shovel'), 'minecraft:wooden_shovel', 'blue_skies:lunar_planks')
    event.smithing(Item.of('blue_skies:bluebright_shovel'), 'minecraft:wooden_shovel', 'blue_skies:bluebright_planks')
    event.smithing(Item.of('blue_skies:horizonite_hoe'), 'minecraft:diamond_hoe', '#blue_skies:ingots/horizonite')
    event.smithing(Item.of('blue_skies:charoite_hoe'), 'minecraft:diamond_hoe', '#blue_skies:gems/charoite')
    event.smithing(Item.of('blue_skies:diopside_hoe'), 'minecraft:netherite_hoe', '#blue_skies:gems/diopside')
    event.smithing(Item.of('blue_skies:aquite_hoe'), 'minecraft:diamond_hoe', '#blue_skies:gems/aquite')
    event.smithing(Item.of('blue_skies:pyrope_hoe'), 'minecraft:iron_hoe', '#blue_skies:gems/pyrope')
    event.smithing(Item.of('blue_skies:lunar_stone_hoe'), 'minecraft:stone_hoe', 'blue_skies:lunar_cobblestone')
    event.smithing(Item.of('blue_skies:turquoise_stone_hoe'), 'minecraft:stone_hoe', 'blue_skies:turquoise_cobblestone')
    event.smithing(Item.of('blue_skies:cherry_hoe'), 'minecraft:wooden_hoe', 'blue_skies:cherry_planks')
    event.smithing(Item.of('blue_skies:maple_hoe'), 'minecraft:wooden_hoe', 'blue_skies:maple_planks')
    event.smithing(Item.of('blue_skies:frostbright_hoe'), 'minecraft:wooden_hoe', 'blue_skies:frostbright_planks')
    event.smithing(Item.of('blue_skies:dusk_hoe'), 'minecraft:wooden_hoe', 'blue_skies:dusk_planks')
    event.smithing(Item.of('blue_skies:starlit_hoe'), 'minecraft:wooden_hoe', 'blue_skies:starlit_planks')
    event.smithing(Item.of('blue_skies:lunar_hoe'), 'minecraft:wooden_hoe', 'blue_skies:lunar_planks')
    event.smithing(Item.of('blue_skies:bluebright_hoe'), 'minecraft:wooden_hoe', 'blue_skies:bluebright_planks')
    event.smithing(Item.of('blue_skies:horizonite_sword'), 'minecraft:diamond_sword', '#blue_skies:ingots/horizonite')
    event.smithing(Item.of('blue_skies:charoite_sword'), 'minecraft:diamond_sword', '#blue_skies:gems/charoite')
    event.smithing(Item.of('blue_skies:diopside_sword'), 'minecraft:netherite_sword', '#blue_skies:gems/diopside')
    event.smithing(Item.of('blue_skies:aquite_sword'), 'minecraft:diamond_sword', '#blue_skies:gems/aquite')
    event.smithing(Item.of('blue_skies:pyrope_sword'), 'minecraft:iron_sword', '#blue_skies:gems/pyrope')
    event.smithing(Item.of('blue_skies:lunar_stone_sword'), 'minecraft:stone_sword', 'blue_skies:lunar_cobblestone')
    event.smithing(Item.of('blue_skies:turquoise_stone_sword'), 'minecraft:stone_sword', 'blue_skies:turquoise_cobblestone')
    event.smithing(Item.of('blue_skies:cherry_sword'), 'minecraft:wooden_sword', 'blue_skies:cherry_planks')
    event.smithing(Item.of('blue_skies:maple_sword'), 'minecraft:wooden_sword', 'blue_skies:maple_planks')
    event.smithing(Item.of('blue_skies:frostbright_sword'), 'minecraft:wooden_sword', 'blue_skies:frostbright_planks')
    event.smithing(Item.of('blue_skies:dusk_sword'), 'minecraft:wooden_sword', 'blue_skies:dusk_planks')
    event.smithing(Item.of('blue_skies:starlit_sword'), 'minecraft:wooden_sword', 'blue_skies:starlit_planks')
    event.smithing(Item.of('blue_skies:lunar_sword'), 'minecraft:wooden_sword', 'blue_skies:lunar_planks')
    event.smithing(Item.of('blue_skies:bluebright_sword'), 'minecraft:wooden_sword', 'blue_skies:bluebright_planks')
    event.smithing(Item.of('blue_skies:horizonite_chestplate'), 'minecraft:diamond_chestplate', '#blue_skies:ingots/horizonite')
    event.smithing(Item.of('blue_skies:charoite_chestplate'), 'minecraft:diamond_chestplate', '#blue_skies:gems/charoite')
    event.smithing(Item.of('blue_skies:diopside_chestplate'), 'minecraft:netherite_chestplate', '#blue_skies:gems/diopside')
    event.smithing(Item.of('blue_skies:aquite_chestplate'), 'minecraft:diamond_chestplate', '#blue_skies:gems/aquite')
    event.smithing(Item.of('blue_skies:pyrope_chestplate'), 'minecraft:iron_chestplate', '#blue_skies:gems/pyrope')
    event.smithing(Item.of('blue_skies:shadow_chestplate'), 'minecraft:netherite_chestplate', '#forge:ingots/shadow_steel')
    event.smithing(Item.of('blue_skies:horizonite_helmet'), 'minecraft:diamond_helmet', '#blue_skies:ingots/horizonite')
    event.smithing(Item.of('blue_skies:charoite_helmet'), 'minecraft:diamond_helmet', '#blue_skies:gems/charoite')
    event.smithing(Item.of('blue_skies:diopside_helmet'), 'minecraft:netherite_helmet', '#blue_skies:gems/diopside')
    event.smithing(Item.of('blue_skies:aquite_helmet'), 'minecraft:diamond_helmet', '#blue_skies:gems/aquite')
    event.smithing(Item.of('blue_skies:pyrope_helmet'), 'minecraft:iron_helmet', '#blue_skies:gems/pyrope')
    event.smithing(Item.of('blue_skies:shadow_helmet'), 'minecraft:netherite_helmet', '#forge:ingots/shadow_steel')
    event.smithing(Item.of('blue_skies:horizonite_leggings'), 'minecraft:diamond_leggings', '#blue_skies:ingots/horizonite')
    event.smithing(Item.of('blue_skies:charoite_leggings'), 'minecraft:diamond_leggings', '#blue_skies:gems/charoite')
    event.smithing(Item.of('blue_skies:diopside_leggings'), 'minecraft:netherite_leggings', '#blue_skies:gems/diopside')
    event.smithing(Item.of('blue_skies:aquite_leggings'), 'minecraft:diamond_leggings', '#blue_skies:gems/aquite')
    event.smithing(Item.of('blue_skies:pyrope_leggings'), 'minecraft:iron_leggings', '#blue_skies:gems/pyrope')
    event.smithing(Item.of('blue_skies:shadow_leggings'), 'minecraft:netherite_leggings', '#forge:ingots/shadow_steel')
    event.smithing(Item.of('blue_skies:horizonite_pickaxe'), 'minecraft:diamond_pickaxe', '#blue_skies:ingots/horizonite')
    event.smithing(Item.of('blue_skies:charoite_pickaxe'), 'minecraft:diamond_pickaxe', '#blue_skies:gems/charoite')
    event.smithing(Item.of('blue_skies:diopside_pickaxe'), 'minecraft:netherite_pickaxe', '#blue_skies:gems/diopside')
    event.smithing(Item.of('blue_skies:aquite_pickaxe'), 'minecraft:diamond_pickaxe', '#blue_skies:gems/aquite')
    event.smithing(Item.of('blue_skies:pyrope_pickaxe'), 'minecraft:iron_pickaxe', '#blue_skies:gems/pyrope')
    event.smithing(Item.of('blue_skies:lunar_stone_pickaxe'), 'minecraft:stone_pickaxe', 'blue_skies:lunar_cobblestone')
    event.smithing(Item.of('blue_skies:turquoise_stone_pickaxe'), 'minecraft:stone_pickaxe', 'blue_skies:turquoise_cobblestone')
    event.smithing(Item.of('blue_skies:cherry_pickaxe'), 'minecraft:wooden_pickaxe', 'blue_skies:cherry_planks')
    event.smithing(Item.of('blue_skies:maple_pickaxe'), 'minecraft:wooden_pickaxe', 'blue_skies:maple_planks')
    event.smithing(Item.of('blue_skies:frostbright_pickaxe'), 'minecraft:wooden_pickaxe', 'blue_skies:frostbright_planks')
    event.smithing(Item.of('blue_skies:dusk_pickaxe'), 'minecraft:wooden_pickaxe', 'blue_skies:dusk_planks')
    event.smithing(Item.of('blue_skies:starlit_pickaxe'), 'minecraft:wooden_pickaxe', 'blue_skies:starlit_planks')
    event.smithing(Item.of('blue_skies:lunar_pickaxe'), 'minecraft:wooden_pickaxe', 'blue_skies:lunar_planks')
    event.smithing(Item.of('blue_skies:bluebright_pickaxe'), 'minecraft:wooden_pickaxe', 'blue_skies:bluebright_planks')

    // Botania
    
    event.smithing(Item.of('botania:livingwood_bow'), 'botania:mana_string', 'botania:livingwood_twig')
    event.smithing(Item.of('botania:terrasteel_boots'), 'minecraft:netherite_boots', '#forge:ingots/terrasteel')
    event.smithing(Item.of('botania:manasteel_hoe'), 'minecraft:iron_hoe', '#forge:ingots/manasteel')
    event.smithing(Item.of('botania:elementium_hoe'), 'minecraft:iron_hoe', '#forge:ingots/elementium')
    event.smithing(Item.of('botania:manasteel_pick'), 'minecraft:iron_pickaxe', '#forge:ingots/manasteel')
    event.smithing(Item.of('botania:elementium_pickaxe'), 'minecraft:iron_pickaxe', '#forge:ingots/elementium')
    event.smithing(Item.of('botania:manasteel_axe'), 'minecraft:iron_axe', '#forge:ingots/manasteel')
    event.smithing(Item.of('botania:elementium_axe'), 'minecraft:iron_axe', '#forge:ingots/elementium')
    event.smithing(Item.of('botania:manasteel_shovel'), 'minecraft:iron_shovel', '#forge:ingots/manasteel')
    event.smithing(Item.of('botania:elementium_shovel'), 'minecraft:iron_shovel', '#forge:ingots/elementium')
    event.smithing(Item.of('botania:mana_ring'), 'botania:mana_tablet', '#forge:ingots/manasteel')
    event.smithing(Item.of('botania:aura_ring'), 'botania:rune_mana', '#forge:ingots/manasteel')
    event.smithing(Item.of('botania:magnet_ring'), 'botania:lens_magnet', '#forge:ingots/manasteel')
    event.smithing(Item.of('botania:water_ring'), 'minecraft:heart_of_the_sea', '#forge:ingots/manasteel')
    event.smithing(Item.of('botania:dodge_ring'), 'botania:rune_air', '#forge:ingots/manasteel')
    event.smithing(Item.of('botania:mining_ring'), 'botania:rune_earth', '#forge:ingots/manasteel')
    event.smithing(Item.of('botania:pixie_ring'), 'botania:pixie_dust', '#forge:ingots/elementium')
    event.smithing(Item.of('botania:reach_ring'), 'botania:rune_pride', '#forge:ingots/elementium')
    event.smithing(Item.of('botania:swap_ring'), '#forge:storage_blocks/clay', '#forge:ingots/manasteel')
    event.smithing(Item.of('botania:aura_ring_greater'), '#forge:ingots/terrasteel', 'botania:aura_ring')
    event.smithing(Item.of('botania:mana_ring_greater'), '#forge:ingots/terrasteel', 'botania:mana_ring')
    event.smithing(Item.of('botania:magnet_ring_greater'), '#forge:ingots/terrasteel', 'botania:magnet_ring')
    event.smithing(Item.of('botania:manasteel_boots'), 'minecraft:iron_boots', '#forge:ingots/manasteel')
    event.smithing(Item.of('botania:elementium_boots'), 'minecraft:iron_boots', '#forge:ingots/elementium')
    event.smithing(Item.of('botania:terrasteel_leggings'), 'minecraft:netherite_leggings', '#forge:ingots/terrasteel')
    event.smithing(Item.of('botania:manasteel_leggings'), 'minecraft:iron_leggings', '#forge:ingots/manasteel')
    event.smithing(Item.of('botania:elementium_leggings'), 'minecraft:iron_leggings', '#forge:ingots/elementium')
    event.smithing(Item.of('botania:manasteel_helmet'), 'minecraft:iron_helmet', '#forge:ingots/manasteel')
    event.smithing(Item.of('botania:elementium_helmet'), 'minecraft:iron_helmet', '#forge:ingots/elementium')
    event.smithing(Item.of('botania:manasteel_chestplate'), 'minecraft:iron_chestplate', '#forge:ingots/manasteel')
    event.smithing(Item.of('botania:elementium_chestplate'), 'minecraft:iron_chestplate', '#forge:ingots/elementium')
    event.smithing(Item.of('botania:manasteel_sword'), 'minecraft:iron_sword', '#forge:ingots/manasteel')
    event.smithing(Item.of('botania:elementium_sword'), 'minecraft:iron_sword', '#forge:ingots/elementium')
    event.smithing(Item.of('botania:terrasteel_helmet'), 'minecraft:netherite_helmet', '#forge:ingots/terrasteel')
    event.smithing(Item.of('botania:terrasteel_chestplate'), 'minecraft:netherite_chestplate', '#forge:ingots/terrasteel')

    //Cyclic
    event.smithing(Item.of('cyclic:netherbrick_pickaxe'), 'minecraft:iron_pickaxe', '#forge:bricks/nether')
    event.smithing(Item.of('cyclic:sandstone_pickaxe'), 'minecraft:stone_pickaxe', '#forge:sandstone')
    event.smithing(Item.of('cyclic:emerald_pickaxe'), 'minecraft:diamond_pickaxe', '#forge:gems/emerald')
    event.smithing(Item.of('cyclic:crystal_pickaxe'), 'minecraft:netherite_pickaxe', '#forge:gems/diamond')
    event.smithing(Item.of('cyclic:netherbrick_hoe'), 'minecraft:iron_hoe', '#forge:bricks/nether')
    event.smithing(Item.of('cyclic:sandstone_hoe'), 'minecraft:stone_hoe', '#forge:sandstone')
    event.smithing(Item.of('cyclic:emerald_hoe'), 'minecraft:diamond_hoe', '#forge:gems/emerald')
    event.smithing(Item.of('cyclic:crystal_hoe'), 'minecraft:netherite_hoe', '#forge:gems/diamond')
    event.smithing(Item.of('cyclic:netherbrick_axe'), 'minecraft:iron_axe', '#forge:bricks/nether')
    event.smithing(Item.of('cyclic:sandstone_axe'), 'minecraft:stone_axe', '#forge:sandstone')
    event.smithing(Item.of('cyclic:emerald_axe'), 'minecraft:diamond_axe', '#forge:gems/emerald')
    event.smithing(Item.of('cyclic:crystal_axe'), 'minecraft:netherite_axe', '#forge:gems/diamond')
    event.smithing(Item.of('cyclic:netherbrick_shovel'), 'minecraft:iron_shovel', '#forge:bricks/nether')
    event.smithing(Item.of('cyclic:sandstone_shovel'), 'minecraft:stone_shovel', '#forge:sandstone')
    event.smithing(Item.of('cyclic:emerald_shovel'), 'minecraft:diamond_shovel', '#forge:gems/emerald')
    event.smithing(Item.of('cyclic:crystal_shovel'), 'minecraft:netherite_shovel', '#forge:gems/diamond')
    event.smithing(Item.of('cyclic:netherbrick_sword'), 'minecraft:iron_sword', '#forge:bricks/nether')
    event.smithing(Item.of('cyclic:sandstone_sword'), 'minecraft:stone_sword', '#forge:sandstone')
    event.smithing(Item.of('cyclic:emerald_sword'), 'minecraft:diamond_sword', '#forge:gems/emerald')
    event.smithing(Item.of('cyclic:crystal_sword'), 'minecraft:netherite_sword', '#forge:gems/diamond')
    event.smithing(Item.of('cyclic:emerald_chestplate'), 'minecraft:diamond_chestplate', '#forge:gems/emerald')
    event.smithing(Item.of('cyclic:crystal_chestplate'), 'minecraft:netherite_chestplate', '#forge:gems/diamond')
    event.smithing(Item.of('cyclic:emerald_helmet'), 'minecraft:diamond_helmet', '#forge:gems/emerald')
    event.smithing(Item.of('cyclic:crystal_helmet'), 'minecraft:netherite_helmet', '#forge:gems/diamond')
    event.smithing(Item.of('cyclic:emerald_leggings'), 'minecraft:diamond_leggings', '#forge:gems/emerald')
    event.smithing(Item.of('cyclic:crystal_leggings'), 'minecraft:netherite_leggings', '#forge:gems/diamond')
    event.smithing(Item.of('cyclic:emerald_boots'), 'minecraft:diamond_boots', '#forge:gems/emerald')
    event.smithing(Item.of('cyclic:crystal_boots'), 'minecraft:netherite_boots', '#forge:gems/diamond')    

    //DruidCraft
    event.smithing(Item.of('druidcraft:moonstone_sword'), 'minecraft:netherite_sword', '#forge:gems/moonstone')
    event.smithing(Item.of('druidcraft:bone_sword'), 'minecraft:stone_sword', '#forge:bones')
    event.smithing(Item.of('druidcraft:moonstone_chestplate'), 'minecraft:netherite_chestplate', '#forge:gems/moonstone')
    event.smithing(Item.of('druidcraft:chitin_chestplate'), 'minecraft:iron_chestplate', 'druidcraft:chitin')
    event.smithing(Item.of('druidcraft:bone_chestplate'), 'minecraft:chainmail_chestplate', '#forge:bones')
    event.smithing(Item.of('druidcraft:moonstone_helmet'), 'minecraft:netherite_helmet', '#forge:gems/moonstone')
    event.smithing(Item.of('druidcraft:chitin_helmet'), 'minecraft:iron_helmet', 'druidcraft:chitin')
    event.smithing(Item.of('druidcraft:bone_helmet'), 'minecraft:chainmail_helmet', '#forge:bones')
    event.smithing(Item.of('druidcraft:moonstone_leggings'), 'minecraft:netherite_leggings', '#forge:gems/moonstone')
    event.smithing(Item.of('druidcraft:chitin_leggings'), 'minecraft:iron_leggings', 'druidcraft:chitin')
    event.smithing(Item.of('druidcraft:bone_leggings'), 'minecraft:chainmail_leggings', '#forge:bones')
    event.smithing(Item.of('druidcraft:moonstone_boots'), 'minecraft:netherite_boots', '#forge:gems/moonstone')
    event.smithing(Item.of('druidcraft:chitin_boots'), 'minecraft:iron_boots', 'druidcraft:chitin')
    event.smithing(Item.of('druidcraft:bone_boots'), 'minecraft:chainmail_boots', '#forge:bones')
    event.smithing(Item.of('druidcraft:bone_shield', '{AS_Amulet_Holder:[I;955663911,-1640609137,-1846237562,1038191077],Damage:0}'), '#minecraft:planks', '#forge:bones')
    event.smithing(Item.of('druidcraft:chitin_shield', '{AS_Amulet_Holder:[I;955663911,-1640609137,-1846237562,1038191077],Damage:0}'), '#forge:nuggets/iron', 'druidcraft:chitin')
    event.smithing(Item.of('druidcraft:moonstone_shield', '{AS_Amulet_Holder:[I;955663911,-1640609137,-1846237562,1038191077],Damage:0}'), '#forge:ingots/iron', '#forge:gems/moonstone')
    event.smithing(Item.of('druidcraft:moonstone_axe'), 'minecraft:netherite_axe', '#forge:gems/moonstone')
    event.smithing(Item.of('druidcraft:bone_axe'), 'minecraft:stone_axe', '#forge:bones')
    event.smithing(Item.of('druidcraft:moonstone_shovel'), 'minecraft:netherite_shovel', '#forge:gems/moonstone')
    event.smithing(Item.of('druidcraft:bone_shovel'), 'minecraft:stone_shovel', '#forge:bones')
    event.smithing(Item.of('druidcraft:moonstone_hoe'), 'minecraft:netherite_hoe', '#forge:gems/moonstone')
    event.smithing(Item.of('druidcraft:moonstone_pickaxe'), 'minecraft:netherite_pickaxe', '#forge:gems/moonstone')
    event.smithing(Item.of('druidcraft:bone_pickaxe'), 'minecraft:stone_pickaxe', '#forge:bones')

    //Explorer's Compass
    event.smithing(Item.of('explorerscompass:explorerscompass'), 'minecraft:compass', 'minecraft:cracked_stone_bricks')
    
    //Forbidden Arcanus

    event.smithing(Item.of('forbidden_arcanus:reinforced_arcane_golden_pickaxe'), 'minecraft:netherite_pickaxe', 'forbidden_arcanus:edelwood_stick')
    event.smithing(Item.of('forbidden_arcanus:arcane_golden_pickaxe'), 'minecraft:netherite_pickaxe', '#forge:ingots/arcane_gold')
    event.smithing(Item.of('forbidden_arcanus:slimec_pickaxe'), 'minecraft:diamond_pickaxe', 'forbidden_arcanus:golden_feather')
    event.smithing(Item.of('forbidden_arcanus:arcane_gold_leggings'), 'minecraft:netherite_leggings', '#forge:ingots/arcane_gold')
    event.smithing(Item.of('forbidden_arcanus:arcane_gold_boots'), 'minecraft:netherite_boots', '#forge:ingots/arcane_gold')
    event.smithing(Item.of('forbidden_arcanus:reinforced_arcane_golden_axe'), 'minecraft:netherite_axe', 'forbidden_arcanus:edelwood_stick')
    event.smithing(Item.of('forbidden_arcanus:arcane_golden_axe'), 'minecraft:netherite_axe', '#forge:ingots/arcane_gold')
    event.smithing(Item.of('forbidden_arcanus:reinforced_arcane_golden_shovel'), 'minecraft:netherite_shovel', 'forbidden_arcanus:edelwood_stick')
    event.smithing(Item.of('forbidden_arcanus:arcane_golden_shovel'), 'minecraft:netherite_shovel', '#forge:ingots/arcane_gold')
    event.smithing(Item.of('forbidden_arcanus:reinforced_arcane_golden_hoe'), 'minecraft:netherite_hoe', 'forbidden_arcanus:edelwood_stick')
    event.smithing(Item.of('forbidden_arcanus:arcane_golden_hoe'), 'minecraft:netherite_hoe', '#forge:ingots/arcane_gold')
    event.smithing(Item.of('forbidden_arcanus:reinforced_arcane_golden_sword'), 'minecraft:netherite_sword', 'forbidden_arcanus:edelwood_stick')
    event.smithing(Item.of('forbidden_arcanus:arcane_golden_sword'), 'minecraft:netherite_sword', '#forge:ingots/arcane_gold')
    event.smithing(Item.of('forbidden_arcanus:arcane_gold_chestplate'), 'minecraft:netherite_chestplate', '#forge:ingots/arcane_gold')
    event.smithing(Item.of('forbidden_arcanus:arcane_gold_helmet'), 'minecraft:netherite_helmet', '#forge:ingots/arcane_gold')
    event.smithing(Item.of('forbidden_arcanus:draco_arcanus_pickaxe'), 'minecraft:netherite_pickaxe', '#forge:dragon_scales')
    
    //Gobber Armor
    event.smithing(Item.of('gobber2:gobber2_helmet_end'), 'minecraft:netherite_helmet', 'gobber2:gobber2_ingot_end')
    event.smithing(Item.of('gobber2:gobber2_helmet_nether'), 'minecraft:netherite_helmet', 'gobber2:gobber2_ingot_nether')
    event.smithing(Item.of('gobber2:gobber2_helmet'), 'minecraft:netherite_helmet', 'gobber2:gobber2_ingot')
    event.smithing(Item.of('gobber2:gobber2_boots_end'), 'minecraft:netherite_boots', 'gobber2:gobber2_ingot_end')
    event.smithing(Item.of('gobber2:gobber2_boots_nether'), 'minecraft:netherite_boots', 'gobber2:gobber2_ingot_nether')
    event.smithing(Item.of('gobber2:gobber2_boots'), 'minecraft:netherite_boots', 'gobber2:gobber2_ingot')
    event.smithing(Item.of('gobber2:gobber2_chestplate_end'), 'minecraft:netherite_chestplate', 'gobber2:gobber2_ingot_end')
    event.smithing(Item.of('gobber2:gobber2_chestplate_nether'), 'minecraft:netherite_chestplate', 'gobber2:gobber2_ingot_nether')
    event.smithing(Item.of('gobber2:gobber2_chestplate'), 'minecraft:netherite_chestplate', 'gobber2:gobber2_ingot')
    event.smithing(Item.of('gobber2:gobber2_leggings_end'), 'minecraft:netherite_leggings', 'gobber2:gobber2_ingot_end')
    event.smithing(Item.of('gobber2:gobber2_leggings_nether'), 'minecraft:netherite_leggings', 'gobber2:gobber2_ingot_nether')
    event.smithing(Item.of('gobber2:gobber2_leggings'), 'minecraft:netherite_leggings', 'gobber2:gobber2_ingot')

    //Gobber Rings
    event.smithing(Item.of('gobber2:gobber2_ring_phoenix'), 'gobber2:gobber2_ring_nether', 'minecraft:magma_cream')

    //Gobber Tools

    event.smithing(Item.of('gobber2:gobber2_pickaxe_end'), 'minecraft:netherite_pickaxe', 'gobber2:gobber2_ingot_end')
    event.smithing(Item.of('gobber2:gobber2_pickaxe_nether'), 'minecraft:netherite_pickaxe', 'gobber2:gobber2_ingot_nether')
    event.smithing(Item.of('gobber2:gobber2_pickaxe'), 'minecraft:netherite_pickaxe', 'gobber2:gobber2_ingot')
    event.smithing(Item.of('gobber2:gobber2_paxel_stars'), 'gobber2:gobber2_paxel_end', 'gobber2:gobber2_staff_stars')
    event.smithing(Item.of('gobber2:gobber2_sword_sniper'), 'gobber2:gobber2_sword_end', 'gobber2:gobber2_staff_sniper')
    event.smithing(Item.of('gobber2:gobber2_sword_traveler'), 'gobber2:gobber2_sword_end', 'gobber2:gobber2_ring_traveler')
    event.smithing(Item.of('gobber2:gobber2_bow'), '#forge:string', 'gobber2:gobber2_rod')
    event.smithing(Item.of('gobber2:gobber2_bow_nether'), '#forge:string', 'gobber2:gobber2_rod_nether')
    event.smithing(Item.of('gobber2:gobber2_bow_end'), '#forge:string', 'gobber2:gobber2_rod_end')
    event.smithing(Item.of('gobber2:gobber2_axe_end'), 'minecraft:netherite_axe', 'gobber2:gobber2_ingot_end')
    event.smithing(Item.of('gobber2:gobber2_axe_nether'), 'minecraft:netherite_axe', 'gobber2:gobber2_ingot_nether')
    event.smithing(Item.of('gobber2:gobber2_axe'), 'minecraft:netherite_axe', 'gobber2:gobber2_ingot')
    event.smithing(Item.of('gobber2:gobber2_shovel_end'), 'minecraft:netherite_shovel', 'gobber2:gobber2_ingot_end')
    event.smithing(Item.of('gobber2:gobber2_excavator_end'), 'minecraft:netherite_shovel', 'gobber2:gobber2_rod_end')
    event.smithing(Item.of('gobber2:gobber2_shovel_nether'), 'minecraft:netherite_shovel', 'gobber2:gobber2_ingot_nether')
    event.smithing(Item.of('gobber2:gobber2_excavator_nether'), 'minecraft:netherite_shovel', 'gobber2:gobber2_rod_nether')
    event.smithing(Item.of('gobber2:gobber2_shovel'), 'minecraft:netherite_shovel', 'gobber2:gobber2_ingot')
    event.smithing(Item.of('gobber2:gobber2_excavator'), 'minecraft:netherite_shovel', 'gobber2:gobber2_rod')
    event.smithing(Item.of('gobber2:gobber2_hoe_end'), 'minecraft:netherite_hoe', 'gobber2:gobber2_ingot_end')
    event.smithing(Item.of('gobber2:gobber2_hoe_nether'), 'minecraft:netherite_hoe', 'gobber2:gobber2_ingot_nether')
    event.smithing(Item.of('gobber2:gobber2_hoe'), 'minecraft:netherite_hoe', 'gobber2:gobber2_ingot')
    event.smithing(Item.of('gobber2:gobber2_sword_end'), 'minecraft:netherite_sword', 'gobber2:gobber2_ingot_end')
    event.smithing(Item.of('gobber2:gobber2_sword_nether'), 'minecraft:netherite_sword', 'gobber2:gobber2_ingot_nether')
    event.smithing(Item.of('gobber2:gobber2_sword'), 'minecraft:netherite_sword', 'gobber2:gobber2_ingot')  
    
    //Immersive Engineering

    event.smithing(Item.of('immersiveengineering:axe_steel'), 'minecraft:iron_axe', '#forge:ingots/steel')
    event.smithing(Item.of('immersiveengineering:shovel_steel'), 'minecraft:iron_shovel', '#forge:ingots/steel')
    event.smithing(Item.of('immersiveengineering:hoe_steel'), 'minecraft:iron_hoe', '#forge:ingots/steel')
    event.smithing(Item.of('immersiveengineering:sword_steel'), 'minecraft:iron_sword', '#forge:ingots/steel')
    event.smithing(Item.of('immersiveengineering:armor_steel_chest'), 'minecraft:iron_chestplate', '#forge:plates/steel')
    event.smithing(Item.of('immersiveengineering:armor_faraday_chest'), 'minecraft:leather_chestplate', '#forge:plates/aluminum')
    event.smithing(Item.of('immersiveengineering:armor_steel_head'), 'minecraft:iron_helmet', '#forge:plates/steel')
    event.smithing(Item.of('immersiveengineering:armor_faraday_head'), 'minecraft:leather_helmet', '#forge:plates/aluminum')
    event.smithing(Item.of('immersiveengineering:armor_steel_legs'), 'minecraft:iron_leggings', '#forge:plates/steel')
    event.smithing(Item.of('immersiveengineering:armor_faraday_legs'), 'minecraft:leather_leggings', '#forge:plates/aluminum')
    event.smithing(Item.of('immersiveengineering:armor_steel_feet'), 'minecraft:iron_boots', '#forge:plates/steel')
    event.smithing(Item.of('immersiveengineering:armor_faraday_feet'), 'minecraft:leather_boots', '#forge:plates/aluminum')
    event.smithing(Item.of('immersiveengineering:shield'), 'minecraft:shield', '#forge:treated_wood')
    event.smithing(Item.of('immersiveengineering:sword_steel'), 'minecraft:iron_sword', '#forge:ingots/steel')
    event.smithing(Item.of('immersiveengineering:pickaxe_steel'), 'minecraft:iron_pickaxe', '#forge:ingots/steel')

    //Ice and Fire
    event.smithing(Item.of('iceandfire:dragonbone_bow'), '#forge:string', '#forge:bones/wither')
    event.smithing(Item.of('iceandfire:dragonsteel_lightning_boots'), 'minecraft:netherite_boots', '#forge:ingots/dragonsteel_lightning')
    event.smithing(Item.of('iceandfire:dragonsteel_ice_boots'), 'minecraft:netherite_boots', '#forge:ingots/dragonsteel_ice')
    event.smithing(Item.of('iceandfire:dragonsteel_fire_boots'), 'minecraft:netherite_boots', '#forge:ingots/dragonsteel_fire')
    event.smithing(Item.of('iceandfire:myrmex_jungle_boots'), 'minecraft:iron_boots', 'iceandfire:myrmex_jungle_chitin')
    event.smithing(Item.of('iceandfire:myrmex_desert_boots'), 'minecraft:iron_boots', 'iceandfire:myrmex_desert_chitin')
    event.smithing(Item.of('iceandfire:dragonsteel_lightning_leggings'), 'minecraft:netherite_leggings', '#forge:ingots/dragonsteel_lightning')
    event.smithing(Item.of('iceandfire:dragonsteel_ice_leggings'), 'minecraft:netherite_leggings', '#forge:ingots/dragonsteel_ice')
    event.smithing(Item.of('iceandfire:dragonsteel_fire_leggings'), 'minecraft:netherite_leggings', '#forge:ingots/dragonsteel_fire')
    event.smithing(Item.of('iceandfire:myrmex_jungle_leggings'), 'minecraft:iron_leggings', 'iceandfire:myrmex_jungle_chitin')
    event.smithing(Item.of('iceandfire:myrmex_desert_leggings'), 'minecraft:iron_leggings', 'iceandfire:myrmex_desert_chitin')
    event.smithing(Item.of('iceandfire:dragonsteel_lightning_pickaxe'), 'minecraft:netherite_sword', '#forge:ingots/dragonsteel_lightning')
    event.smithing(Item.of('iceandfire:dragonsteel_ice_sword'), 'minecraft:netherite_sword', '#forge:ingots/dragonsteel_ice')
    event.smithing(Item.of('iceandfire:dragonsteel_fire_sword'), 'minecraft:netherite_sword', '#forge:ingots/dragonsteel_fire')
    event.smithing(Item.of('iceandfire:myrmex_jungle_sword'), 'minecraft:iron_sword', 'iceandfire:myrmex_jungle_chitin')
    event.smithing(Item.of('iceandfire:myrmex_desert_sword'), 'minecraft:iron_sword', 'iceandfire:myrmex_desert_chitin')
    event.smithing(Item.of('iceandfire:dragonbone_sword'), 'minecraft:netherite_sword', '#forge:bones/dragon')
    event.smithing(Item.of('iceandfire:dragonbone_sword_lightning'), 'iceandfire:dragonbone_sword', 'iceandfire:lightning_dragon_blood')
    event.smithing(Item.of('iceandfire:dragonbone_sword_ice'), 'iceandfire:dragonbone_sword', 'iceandfire:ice_dragon_blood')
    event.smithing(Item.of('iceandfire:dragonbone_sword_fire'), 'iceandfire:dragonbone_sword', 'iceandfire:fire_dragon_blood')
    event.smithing(Item.of('iceandfire:hippogryph_sword'), 'minecraft:netherite_sword', 'iceandfire:hippogryph_talon')
    event.smithing(Item.of('iceandfire:dragonsteel_lightning_chestplate'), 'minecraft:netherite_chestplate', '#forge:ingots/dragonsteel_lightning')
    event.smithing(Item.of('iceandfire:dragonsteel_ice_chestplate'), 'minecraft:netherite_chestplate', '#forge:ingots/dragonsteel_ice')
    event.smithing(Item.of('iceandfire:dragonsteel_fire_chestplate'), 'minecraft:netherite_chestplate', '#forge:ingots/dragonsteel_fire')
    event.smithing(Item.of('iceandfire:myrmex_jungle_chestplate'), 'minecraft:iron_chestplate', 'iceandfire:myrmex_jungle_chitin')
    event.smithing(Item.of('iceandfire:myrmex_desert_chestplate'), 'minecraft:iron_chestplate', 'iceandfire:myrmex_desert_chitin')
    event.smithing(Item.of('iceandfire:dragonsteel_lightning_helmet'), 'minecraft:netherite_helmet', '#forge:ingots/dragonsteel_lightning')
    event.smithing(Item.of('iceandfire:dragonsteel_ice_helmet'), 'minecraft:netherite_helmet', '#forge:ingots/dragonsteel_ice')
    event.smithing(Item.of('iceandfire:dragonsteel_fire_helmet'), 'minecraft:netherite_helmet', '#forge:ingots/dragonsteel_fire')
    event.smithing(Item.of('iceandfire:myrmex_jungle_helmet'), 'minecraft:iron_helmet', 'iceandfire:myrmex_jungle_chitin')
    event.smithing(Item.of('iceandfire:myrmex_desert_helmet'), 'minecraft:iron_helmet', 'iceandfire:myrmex_desert_chitin')
    event.smithing(Item.of('iceandfire:dragonsteel_lightning_axe'), 'minecraft:netherite_axe', '#forge:ingots/dragonsteel_lightning')
    event.smithing(Item.of('iceandfire:dragonsteel_ice_axe'), 'minecraft:netherite_axe', '#forge:ingots/dragonsteel_ice')
    event.smithing(Item.of('iceandfire:dragonsteel_fire_axe'), 'minecraft:netherite_axe', '#forge:ingots/dragonsteel_fire')
    event.smithing(Item.of('iceandfire:myrmex_jungle_axe'), 'minecraft:iron_axe', 'iceandfire:myrmex_jungle_chitin')
    event.smithing(Item.of('iceandfire:myrmex_desert_axe'), 'minecraft:iron_axe', 'iceandfire:myrmex_desert_chitin')
    event.smithing(Item.of('iceandfire:dragonbone_axe'), 'minecraft:netherite_axe', '#forge:bones/dragon')
    event.smithing(Item.of('iceandfire:dragonsteel_lightning_shovel'), 'minecraft:netherite_shovel', '#forge:ingots/dragonsteel_lightning')
    event.smithing(Item.of('iceandfire:dragonsteel_ice_shovel'), 'minecraft:netherite_shovel', '#forge:ingots/dragonsteel_ice')
    event.smithing(Item.of('iceandfire:dragonsteel_fire_shovel'), 'minecraft:netherite_shovel', '#forge:ingots/dragonsteel_fire')
    event.smithing(Item.of('iceandfire:myrmex_jungle_shovel'), 'minecraft:iron_shovel', 'iceandfire:myrmex_jungle_chitin')
    event.smithing(Item.of('iceandfire:myrmex_desert_shovel'), 'minecraft:iron_shovel', 'iceandfire:myrmex_desert_chitin')
    event.smithing(Item.of('iceandfire:dragonbone_shovel'), 'minecraft:netherite_shovel', '#forge:bones/dragon')
    event.smithing(Item.of('iceandfire:dragonsteel_lightning_hoe'), 'minecraft:netherite_hoe', '#forge:ingots/dragonsteel_lightning')
    event.smithing(Item.of('iceandfire:dragonsteel_ice_hoe'), 'minecraft:netherite_hoe', '#forge:ingots/dragonsteel_ice')
    event.smithing(Item.of('iceandfire:dragonsteel_fire_hoe'), 'minecraft:netherite_hoe', '#forge:ingots/dragonsteel_fire')
    event.smithing(Item.of('iceandfire:myrmex_jungle_hoe'), 'minecraft:iron_hoe', 'iceandfire:myrmex_jungle_chitin')
    event.smithing(Item.of('iceandfire:myrmex_desert_hoe'), 'minecraft:iron_hoe', 'iceandfire:myrmex_desert_chitin')
    event.smithing(Item.of('iceandfire:dragonbone_hoe'), 'minecraft:netherite_hoe', '#forge:bones/dragon')
    event.smithing(Item.of('iceandfire:dragonsteel_lightning_pickaxe'), 'minecraft:netherite_pickaxe', '#forge:ingots/dragonsteel_lightning')
    event.smithing(Item.of('iceandfire:dragonsteel_ice_pickaxe'), 'minecraft:netherite_pickaxe', '#forge:ingots/dragonsteel_ice')
    event.smithing(Item.of('iceandfire:dragonsteel_fire_pickaxe'), 'minecraft:netherite_pickaxe', '#forge:ingots/dragonsteel_fire')
    event.smithing(Item.of('iceandfire:myrmex_jungle_pickaxe'), 'minecraft:iron_pickaxe', 'iceandfire:myrmex_jungle_chitin')
    event.smithing(Item.of('iceandfire:myrmex_desert_pickaxe'), 'minecraft:iron_pickaxe', 'iceandfire:myrmex_desert_chitin')
    event.smithing(Item.of('iceandfire:dragonbone_pickaxe'), 'minecraft:netherite_pickaxe', '#forge:bones/dragon')  

    //Minecraft

    event.smithing(Item.of('minecraft:shield'), '#minecraft:planks', '#forge:ingots/iron')
    event.smithing(Item.of('minecraft:compass'), '#forge:plates/iron', 'extendedcrafting:redstone_ingot')
    event.smithing(Item.of('minecraft:bow', '{Damage:0}'), '#forge:rods/wooden', '#forge:string')
    event.smithing(Item.of('minecraft:crossbow', '{Damage:0}'), 'minecraft:tripwire_hook', '#forge:ingots/iron')

    //Mystical Agriculture Furnace

    event.smithing(Item.of('mysticalagriculture:inferium_furnace'), '#forge:furnace', 'mysticalagriculture:inferium_block')
    event.smithing(Item.of('mysticalagriculture:prudentium_furnace'), 'mysticalagriculture:inferium_furnace', 'mysticalagriculture:prudentium_block')
    event.smithing(Item.of('mysticalagriculture:tertium_furnace'), 'mysticalagriculture:prudentium_furnace', 'mysticalagriculture:tertium_block')
    event.smithing(Item.of('mysticalagriculture:imperium_furnace'), 'mysticalagriculture:tertium_furnace', 'mysticalagriculture:imperium_block')
    event.smithing(Item.of('mysticalagriculture:supremium_furnace'), 'mysticalagriculture:imperium_furnace', 'mysticalagriculture:supremium_block')

    //Mystical Agriculture helmet

    event.smithing(Item.of('mysticalagriculture:inferium_helmet'), 'minecraft:diamond_helmet', 'mysticalagriculture:inferium_gemstone')
    event.smithing(Item.of('mysticalagriculture:prudentium_helmet'), 'mysticalagriculture:inferium_helmet', 'mysticalagriculture:prudentium_gemstone')
    event.smithing(Item.of('mysticalagriculture:tertium_helmet'), 'mysticalagriculture:prudentium_helmet', 'mysticalagriculture:tertium_gemstone')
    event.smithing(Item.of('mysticalagriculture:imperium_helmet', '{Damage:0}'), Item.of('mysticalagriculture:tertium_helmet', '{Damage:0}'), 'mysticalagriculture:imperium_gemstone')
    event.smithing(Item.of('mysticalagriculture:supremium_helmet', '{Damage:0}'), Item.of('mysticalagriculture:imperium_helmet', '{Damage:0}'), 'mysticalagriculture:supremium_gemstone')

    //Mystical Agriculture Chestplates

    event.smithing(Item.of('mysticalagriculture:inferium_chestplate'), 'minecraft:diamond_chestplate', 'mysticalagriculture:inferium_gemstone')
    event.smithing(Item.of('mysticalagriculture:supremium_chestplate', '{Damage:0}'), Item.of('mysticalagriculture:imperium_chestplate', '{Damage:0}'), 'mysticalagriculture:supremium_gemstone')
    event.smithing(Item.of('mysticalagriculture:imperium_chestplate', '{Damage:0}'), Item.of('mysticalagriculture:tertium_chestplate', '{Damage:0}'), 'mysticalagriculture:imperium_gemstone')
    event.smithing(Item.of('mysticalagriculture:tertium_chestplate', '{Damage:0}'), Item.of('mysticalagriculture:prudentium_chestplate', '{Damage:0}'), 'mysticalagriculture:tertium_gemstone')
    event.smithing(Item.of('mysticalagriculture:prudentium_chestplate', '{Damage:0}'), Item.of('mysticalagriculture:inferium_chestplate', '{Damage:0}'), 'mysticalagriculture:prudentium_gemstone')
    
    //Mystical Agriculture Leggings

    event.smithing(Item.of('mysticalagriculture:inferium_leggings'), 'minecraft:diamond_leggings', 'mysticalagriculture:inferium_gemstone')
    event.smithing(Item.of('mysticalagriculture:prudentium_leggings'), 'mysticalagriculture:inferium_leggings', 'mysticalagriculture:prudentium_gemstone')
    event.smithing(Item.of('mysticalagriculture:tertium_leggings'), 'mysticalagriculture:prudentium_leggings', 'mysticalagriculture:tertium_gemstone')
    event.smithing(Item.of('mysticalagriculture:imperium_leggings', '{Damage:0}'), Item.of('mysticalagriculture:tertium_leggings', '{Damage:0}'), 'mysticalagriculture:imperium_gemstone')
    event.smithing(Item.of('mysticalagriculture:supremium_leggings', '{Damage:0}'), Item.of('mysticalagriculture:imperium_leggings', '{Damage:0}'), 'mysticalagriculture:supremium_gemstone')
    
    //Mystical Agriculture Boots

    event.smithing(Item.of('mysticalagriculture:inferium_boots'), 'minecraft:diamond_boots', 'mysticalagriculture:inferium_gemstone')
    event.smithing(Item.of('mysticalagriculture:prudentium_boots'), 'mysticalagriculture:inferium_boots', 'mysticalagriculture:prudentium_gemstone')
    event.smithing(Item.of('mysticalagriculture:tertium_boots'), 'mysticalagriculture:prudentium_boots', 'mysticalagriculture:tertium_gemstone')
    event.smithing(Item.of('mysticalagriculture:imperium_boots', '{Damage:0}'), Item.of('mysticalagriculture:tertium_boots', '{Damage:0}'), 'mysticalagriculture:imperium_gemstone')
    event.smithing(Item.of('mysticalagriculture:supremium_boots', '{Damage:0}'), Item.of('mysticalagriculture:imperium_boots', '{Damage:0}'), 'mysticalagriculture:supremium_gemstone')
    
    //Mystical Agriculture Tools

    event.smithing(Item.of('mysticalagriculture:inferium_axe'), 'minecraft:diamond_axe', 'mysticalagriculture:inferium_gemstone')
    event.smithing(Item.of('mysticalagriculture:inferium_pickaxe'), 'minecraft:diamond_pickaxe', 'mysticalagriculture:inferium_gemstone')
    event.smithing(Item.of('mysticalagriculture:prudentium_pickaxe'), 'mysticalagriculture:inferium_pickaxe', 'mysticalagriculture:prudentium_gemstone')
    event.smithing(Item.of('mysticalagriculture:tertium_pickaxe'), 'mysticalagriculture:prudentium_pickaxe', 'mysticalagriculture:tertium_gemstone')
    event.smithing(Item.of('mysticalagriculture:imperium_pickaxe'), 'mysticalagriculture:tertium_pickaxe', 'mysticalagriculture:imperium_gemstone')
    event.smithing(Item.of('mysticalagriculture:supremium_pickaxe'), 'mysticalagriculture:imperium_pickaxe', 'mysticalagriculture:supremium_gemstone')
    event.smithing(Item.of('mysticalagriculture:inferium_shovel'), 'minecraft:diamond_shovel', 'mysticalagriculture:inferium_gemstone')
    event.smithing(Item.of('mysticalagriculture:prudentium_shovel'), 'mysticalagriculture:inferium_shovel', 'mysticalagriculture:prudentium_gemstone')
    event.smithing(Item.of('mysticalagriculture:inferium_hoe'), 'minecraft:diamond_hoe', 'mysticalagriculture:inferium_gemstone')
    event.smithing(Item.of('mysticalagriculture:inferium_sword'), 'minecraft:diamond_sword', 'mysticalagriculture:inferium_gemstone')
    
    //Modular Routers
    event.smithing(Item.of('modularrouters:breaker_module', '{modularrouters:{ModuleFilter:{},Direction:"NONE"}}'), 'modularrouters:blank_module', '#forge:tools/pickaxe')
    event.smithing(Item.of('modularrouters:extruder_module_1', '{modularrouters:{ModuleFilter:{},Direction:"NONE"}}'), 'modularrouters:breaker_module', 'modularrouters:blank_module')

    //Nature's Aura

    event.smithing(Item.of('naturesaura:infused_iron_axe'), 'minecraft:iron_axe', 'naturesaura:infused_iron')
    event.smithing(Item.of('naturesaura:sky_axe'), 'minecraft:diamond_axe', 'naturesaura:sky_ingot')
    event.smithing(Item.of('naturesaura:infused_iron_sword'), 'minecraft:iron_sword', 'naturesaura:infused_iron')
    event.smithing(Item.of('naturesaura:sky_sword'), 'minecraft:diamond_sword', 'naturesaura:sky_ingot')
    event.smithing(Item.of('naturesaura:infused_iron_hoe'), 'minecraft:iron_hoe', 'naturesaura:infused_iron')
    event.smithing(Item.of('naturesaura:sky_hoe'), 'minecraft:diamond_hoe', 'naturesaura:sky_ingot')
    event.smithing(Item.of('naturesaura:infused_iron_chest'), 'minecraft:iron_chestplate', 'naturesaura:infused_iron')
    event.smithing(Item.of('naturesaura:sky_chest'), 'minecraft:diamond_chestplate', 'naturesaura:sky_ingot')
    event.smithing(Item.of('naturesaura:infused_iron_helmet'), 'minecraft:iron_helmet', 'naturesaura:infused_iron')
    event.smithing(Item.of('naturesaura:sky_helmet'), 'minecraft:diamond_helmet', 'naturesaura:sky_ingot')
    event.smithing(Item.of('naturesaura:infused_iron_pants'), 'minecraft:iron_leggings', 'naturesaura:infused_iron')
    event.smithing(Item.of('naturesaura:sky_pants'), 'minecraft:diamond_leggings', 'naturesaura:sky_ingot')
    event.smithing(Item.of('naturesaura:infused_iron_shoes'), 'minecraft:iron_boots', 'naturesaura:infused_iron')
    event.smithing(Item.of('naturesaura:sky_shoes'), 'minecraft:diamond_boots', 'naturesaura:sky_ingot')
    event.smithing(Item.of('naturesaura:infused_iron_shovel'), 'minecraft:iron_shovel', 'naturesaura:infused_iron')
    event.smithing(Item.of('naturesaura:sky_shovel'), 'minecraft:diamond_shovel', 'naturesaura:sky_ingot')
    event.smithing(Item.of('naturesaura:infused_iron_pickaxe'), 'minecraft:iron_pickaxe', 'naturesaura:infused_iron')
    event.smithing(Item.of('naturesaura:sky_pickaxe'), 'minecraft:diamond_pickaxe', 'naturesaura:sky_ingot')

    //Nature's Compass

    event.smithing(Item.of('naturescompass:naturescompass'), 'minecraft:compass', '#minecraft:saplings')

    //Occultism

    event.smithing(Item.of('occultism:iesnium_pickaxe'), 'minecraft:diamond_pickaxe', '#forge:ingots/iesnium')

    //Pneumaticcraft
    event.smithing(Item.of('pneumaticcraft:compressed_iron_boots'), 'minecraft:iron_boots', 'kubejs:compressed_iron_plate')
    event.smithing(Item.of('pneumaticcraft:compressed_iron_leggings'), 'minecraft:iron_leggings', 'kubejs:compressed_iron_plate')
    event.smithing(Item.of('pneumaticcraft:compressed_iron_helmet'), 'minecraft:iron_helmet', 'kubejs:compressed_iron_plate')
    event.smithing(Item.of('pneumaticcraft:compressed_iron_chestplate'), 'minecraft:iron_chestplate', 'kubejs:compressed_iron_plate')

    //PSI
    event.smithing(Item.of('psi:psimetal_pickaxe'), 'minecraft:diamond_pickaxe', '#forge:gems/psigem')
    event.smithing(Item.of('psipherals:psimetal_bow'), '#forge:string', '#forge:gems/psigem')
    event.smithing(Item.of('psi:psimetal_exosuit_boots'), 'minecraft:diamond_boots', '#forge:gems/psigem')
    event.smithing(Item.of('psi:psimetal_exosuit_leggings'), 'minecraft:diamond_leggings', '#forge:gems/psigem')
    event.smithing(Item.of('psi:psimetal_exosuit_helmet'), 'minecraft:diamond_helmet', '#forge:gems/psigem')
    event.smithing(Item.of('psi:psimetal_exosuit_chestplate'), 'minecraft:diamond_chestplate', '#forge:gems/psigem')
    event.smithing(Item.of('psi:psimetal_sword'), 'minecraft:diamond_sword', '#forge:gems/psigem')
    event.smithing(Item.of('psi:psimetal_shovel'), 'minecraft:diamond_shovel', '#forge:gems/psigem')
    event.smithing(Item.of('psi:psimetal_axe'), 'minecraft:diamond_axe', '#forge:gems/psigem')
    
    
    //Sophisticated Backpacks

    event.smithing(Item.of('sophisticatedbackpacks:iron_backpack'), '#forge:ingots/iron', 'sophisticatedbackpacks:backpack')
    event.smithing(Item.of('sophisticatedbackpacks:gold_backpack'), '#forge:ingots/gold', 'sophisticatedbackpacks:iron_backpack')
    event.smithing(Item.of('sophisticatedbackpacks:diamond_backpack'), '#forge:gems/diamond', 'sophisticatedbackpacks:gold_backpack')
    
    //Twilight Forest

    event.smithing(Item.of('twilightforest:ironwood_hoe'), 'minecraft:iron_hoe', '#forge:ingots/ironwood')
    event.smithing(Item.of('twilightforest:steeleaf_hoe'), 'minecraft:diamond_hoe', '#forge:ingots/steeleaf')
    event.smithing(Item.of('twilightforest:ironwood_hoe'), 'minecraft:iron_hoe', '#forge:ingots/ironwood')
    event.smithing(Item.of('twilightforest:steeleaf_hoe'), 'minecraft:diamond_hoe', '#forge:ingots/steeleaf')
    event.smithing(Item.of('twilightforest:ironwood_sword'), 'minecraft:iron_sword', '#forge:ingots/ironwood')
    event.smithing(Item.of('twilightforest:steeleaf_sword'), 'minecraft:diamond_sword', '#forge:ingots/steeleaf')
    event.smithing(Item.of('twilightforest:knightmetal_sword'), 'minecraft:diamond_sword', '#forge:ingots/knightmetal')
    event.smithing(Item.of('twilightforest:fiery_sword'), 'minecraft:netherite_sword', '#forge:ingots/fiery')
    event.smithing(Item.of('twilightforest:ironwood_chestplate'), 'minecraft:iron_chestplate', '#forge:ingots/ironwood')
    event.smithing(Item.of('twilightforest:steeleaf_chestplate'), 'minecraft:diamond_chestplate', '#forge:ingots/steeleaf')
    event.smithing(Item.of('twilightforest:fiery_chestplate'), 'minecraft:netherite_chestplate', '#forge:ingots/fiery')
    event.smithing(Item.of('twilightforest:knightmetal_chestplate'), 'minecraft:netherite_chestplate', '#forge:ingots/knightmetal')
    event.smithing(Item.of('twilightforest:ironwood_helmet'), 'minecraft:iron_helmet', '#forge:ingots/ironwood')
    event.smithing(Item.of('twilightforest:steeleaf_helmet'), 'minecraft:diamond_helmet', '#forge:ingots/steeleaf')
    event.smithing(Item.of('twilightforest:fiery_helmet'), 'minecraft:netherite_helmet', '#forge:ingots/fiery')
    event.smithing(Item.of('twilightforest:knightmetal_helmet'), 'minecraft:netherite_helmet', '#forge:ingots/knightmetal')
    event.smithing(Item.of('twilightforest:ironwood_leggings'), 'minecraft:iron_leggings', '#forge:ingots/ironwood')
    event.smithing(Item.of('twilightforest:steeleaf_leggings'), 'minecraft:diamond_leggings', '#forge:ingots/steeleaf')
    event.smithing(Item.of('twilightforest:fiery_leggings'), 'minecraft:netherite_leggings', '#forge:ingots/fiery')
    event.smithing(Item.of('twilightforest:knightmetal_leggings'), 'minecraft:diamond_leggings', '#forge:ingots/knightmetal')
    event.smithing(Item.of('twilightforest:ironwood_boots'), 'minecraft:iron_boots', '#forge:ingots/ironwood')
    event.smithing(Item.of('twilightforest:steeleaf_boots'), 'minecraft:diamond_boots', '#forge:ingots/steeleaf')
    event.smithing(Item.of('twilightforest:fiery_boots'), 'minecraft:netherite_boots', '#forge:ingots/fiery')
    event.smithing(Item.of('twilightforest:knightmetal_boots'), 'minecraft:diamond_boots', '#forge:ingots/knightmetal')
    event.smithing(Item.of('twilightforest:knightmetal_shield'), '#twilightforest:towerwood', '#forge:ingots/knightmetal')
    event.smithing(Item.of('twilightforest:ironwood_axe'), 'minecraft:iron_axe', '#forge:ingots/ironwood')
    event.smithing(Item.of('twilightforest:steeleaf_axe'), 'minecraft:diamond_axe', '#forge:ingots/steeleaf')
    event.smithing(Item.of('twilightforest:knightmetal_axe'), 'minecraft:netherite_axe', '#forge:ingots/knightmetal')
    event.smithing(Item.of('twilightforest:ironwood_shovel'), 'minecraft:iron_shovel', '#forge:ingots/ironwood')
    event.smithing(Item.of('twilightforest:steeleaf_shovel'), 'minecraft:diamond_shovel', '#forge:ingots/steeleaf')
    event.smithing(Item.of('twilightforest:giant_pickaxe'), 'twilightforest:giant_cobblestone', 'twilightforest:giant_log')
    event.smithing(Item.of('twilightforest:knightmetal_pickaxe'), 'minecraft:diamond_pickaxe', '#forge:ingots/knightmetal')
    event.smithing(Item.of('twilightforest:steeleaf_pickaxe'), 'minecraft:diamond_pickaxe', '#forge:ingots/steeleaf')
    event.smithing(Item.of('twilightforest:fiery_pickaxe'), 'minecraft:netherite_pickaxe', '#forge:ingots/fiery')
    event.smithing(Item.of('twilightforest:ironwood_pickaxe'), 'minecraft:iron_pickaxe', '#forge:ingots/ironwood')
    
    //Undergrden

    event.smithing(Item.of('undergarden:cloggrum_pickaxe'), 'minecraft:stone_pickaxe', '#forge:ingots/cloggrum')
    event.smithing(Item.of('undergarden:froststeel_pickaxe'), 'minecraft:iron_pickaxe', '#forge:ingots/froststeel')
    event.smithing(Item.of('undergarden:utheric_pickaxe'), 'minecraft:diamond_pickaxe', '#forge:ingots/utherium')
    event.smithing(Item.of('undergarden:cloggrum_hoe'), 'minecraft:stone_hoe', '#forge:ingots/cloggrum')
    event.smithing(Item.of('undergarden:froststeel_hoe'), 'minecraft:iron_hoe', '#forge:ingots/froststeel')
    event.smithing(Item.of('undergarden:utheric_hoe'), 'minecraft:diamond_hoe', '#forge:ingots/utherium')
    event.smithing(Item.of('undergarden:cloggrum_sword'), 'minecraft:stone_sword', '#forge:ingots/cloggrum')
    event.smithing(Item.of('undergarden:froststeel_sword'), 'minecraft:iron_sword', '#forge:ingots/froststeel')
    event.smithing(Item.of('undergarden:utheric_sword'), 'minecraft:diamond_sword', '#forge:ingots/utherium')
    event.smithing(Item.of('undergarden:cloggrum_chestplate'), 'minecraft:iron_chestplate', '#forge:ingots/cloggrum')
    event.smithing(Item.of('undergarden:froststeel_chestplate'), 'minecraft:iron_chestplate', '#forge:ingots/froststeel')
    event.smithing(Item.of('undergarden:utheric_chestplate'), 'minecraft:netherite_chestplate', '#forge:ingots/utherium')
    event.smithing(Item.of('undergarden:masticated_chestplate'), 'minecraft:iron_chestplate', 'undergarden:masticator_scales')
    event.smithing(Item.of('undergarden:cloggrum_helmet'), 'minecraft:iron_helmet', '#forge:ingots/cloggrum')
    event.smithing(Item.of('undergarden:froststeel_helmet'), 'minecraft:iron_helmet', '#forge:ingots/froststeel')
    event.smithing(Item.of('undergarden:utheric_helmet'), 'minecraft:netherite_helmet', '#forge:ingots/utherium')
    event.smithing(Item.of('undergarden:cloggrum_leggings'), 'minecraft:iron_leggings', '#forge:ingots/cloggrum')
    event.smithing(Item.of('undergarden:froststeel_leggings'), 'minecraft:iron_leggings', '#forge:ingots/froststeel')
    event.smithing(Item.of('undergarden:utheric_leggings'), 'minecraft:netherite_leggings', '#forge:ingots/utherium')
    event.smithing(Item.of('undergarden:cloggrum_boots'), 'minecraft:iron_boots', '#forge:ingots/cloggrum')
    event.smithing(Item.of('undergarden:froststeel_boots'), 'minecraft:iron_boots', '#forge:ingots/froststeel')
    event.smithing(Item.of('undergarden:utheric_boots'), 'minecraft:netherite_boots', '#forge:ingots/utherium')
    event.smithing(Item.of('undergarden:cloggrum_shield'), '#minecraft:planks', '#forge:ingots/cloggrum')
    event.smithing(Item.of('undergarden:cloggrum_axe'), 'minecraft:stone_axe', '#forge:ingots/cloggrum')
    event.smithing(Item.of('undergarden:froststeel_axe'), 'minecraft:iron_axe', '#forge:ingots/froststeel')
    event.smithing(Item.of('undergarden:utheric_axe'), 'minecraft:diamond_axe', '#forge:ingots/utherium')
    event.smithing(Item.of('undergarden:cloggrum_shovel'), 'minecraft:stone_shovel', '#forge:ingots/cloggrum')
    event.smithing(Item.of('undergarden:froststeel_shovel'), 'minecraft:iron_shovel', '#forge:ingots/froststeel')
    event.smithing(Item.of('undergarden:utheric_shovel'), 'minecraft:diamond_shovel', '#forge:ingots/utherium')
})