ServerEvents.recipes(e => {
  gear.forEach((material) => {
  plates.forEach((material) => {

  removeRecipeByID(e, [
    `thermal:parts/${material}_gear`,
    `allthecompatibility:ad_astra/hammering/${material}`,
    `ad_astra:hammering/steel_plate`,

    //Apotheosis
    `apotheosis:book`,

    //Ae2
    `ae2:misc/vanilla_daylight_detector`,
    `ae2:network/parts/formation_plane_alt2`,
    `ae2:network/parts/formation_plane_alt`,
    `ae2:network/parts/annihilation_plane_alt2`,
    `ae2:network/parts/annihilation_plane_alt`,
    `ae2:inscriber/calculation_processor_press`,
    `ae2:inscriber/engineering_processor_press`,
    `ae2:tools/fluix_axe`,
    `ae2:tools/fluix_hoe`,
    `ae2:tools/fluix_shovel`,
    `ae2:tools/fluix_pickaxe`,
    `ae2:tools/fluix_sword`,
    `ae2:tools/certus_quartz_wrench`,
    `ae2:tools/nether_quartz_wrench`,
    `ae2:network/wireless_booster`,
    `ae2:charger/meteorite_compass`,
    `ae2:misc/meteors_sky_compass`,
    `ae2:misc/vanilla_comparator`,
    `ae2:misc/grindstone_woodengear`,
    `ae2:misc/grindstone`,
    `ae2:inscriber/logic_processor_press`,
    `ae2:inscriber/calculation_processor_print`,
    `ae2:inscriber/logic_processor_print`,
    `ae2:inscriber/engineering_processor_print`,
    `ae2:tools/certus_quartz_pickaxe`,
    `ae2:tools/certus_quartz_axe`,
    `ae2:tools/certus_quartz_spade`,
    `ae2:tools/certus_quartz_hoe`,
    `ae2:tools/certus_quartz_sword`,
    `ae2:tools/nether_quartz_pickaxe`,
    `ae2:tools/nether_quartz_axe`,
    `ae2:tools/nether_quartz_spade`,
    `ae2:tools/nether_quartz_hoe`,
    `ae2:tools/nether_quartz_sword`,
    `ae2:inscriber/engineering_processor`,
    `ae2:inscriber/silicon_press`,
    `ae2:inscriber/calculation_processor`,
    `ae2:inscriber/logic_processor`,
    `ae2:network/blocks/crystal_processing_quartz_growth_accelerator`,
    `ae2:network/blocks/quantum_ring`,
    `ae2:network/crafting/cpu_crafting_unit`,
    `ae2:network/crafting/patterns_blank`,
    `ae2:network/parts/import_bus`,
    `ae2:network/parts/export_bus`,
    `ae2:network/parts/planes_annihilation`,
    `ae2:network/parts/planes_annihilation_alt`,
    `ae2:network/parts/planes_formation`,
    `ae2:network/parts/planes_formation_alt`,
    `ae2:network/parts/planes_formation_fluid_alt`,
    `ae2:network/parts/planes_formation_fluid`,
    `ae2:network/parts/quartz_fiber_part`,
    `ae2:network/parts/panels_semi_dark_monitor`,
    `ae2:network/parts/tunnels_me`,
    `ae2:decorative/quartz_glass`,
    `ae2:decorative/quartz_vibrant_glass`,
    `ae2:materials/formationcore`,
    `ae2:materials/annihilationcore`,
    `ae2:materials/basiccard`,
    `ae2:materials/advancedcard`,
    `ae2:network/blocks/inscribers`,
    `ae2:network/blocks/crank`,
    `ae2:network/blocks/interfaces_interface`,
    `ae2:network/blocks/storage_drive`,
    `ae2:network/blocks/io_port`,
    `ae2:network/blocks/io_condenser`,
    `ae2:network/blocks/security_station`,
    `ae2:network/blocks/storage_chest`,
    `ae2:network/crafting/molecular_assembler`,
    `ae2:network/blocks/spatial_io_port`,
    `ae2:network/blocks/cell_workbench`,
    `ae2:network/blocks/energy_energy_acceptor`,
    `ae2:network/blocks/crystal_processing_charger`,
    `ae2:network/blocks/energy_vibration_chamber`,
    `ae2:network/blocks/fluid_interfaces_interface`,
    `ae2:network/cells/item_cell_housing`,
    `ae2:network/cells/fluid_cell_housing`,
    `ae2:network/cells/spatial_components`,
    `ae2:network/cells/spatial_components_0`,
    `ae2:network/cells/spatial_components_1`,
    `ae2:network/cells/item_storage_components_cell_256k_part`,
    `ae2:network/cells/item_storage_components_cell_64k_part`,
    `ae2:network/cells/item_storage_components_cell_16k_part`,
    `ae2:network/cells/item_storage_components_cell_4k_part`,
    `ae2:network/cells/item_storage_components_cell_1k_part`,
    `ae2:network/cells/fluid_storage_components_cell_64k_part`,
    `ae2:network/cells/fluid_storage_components_cell_16k_part`,
    `ae2:network/cells/fluid_storage_components_cell_4k_part`,
    `ae2:network/cells/fluid_storage_components_cell_1k_part`,
    `ae2:network/cells/view_cell`,
    `ae2:network/cells/view_cell_storage`,
    `ae2:network/cells/item_storage_cell_1k_storage`,
    `ae2:network/cells/item_storage_cell_1k`,
    `ae2:network/cells/item_storage_cell_4k_storage`,
    `ae2:network/cells/item_storage_cell_4k`,
    `ae2:network/cells/item_storage_cell_16k_storage`,
    `ae2:network/cells/item_storage_cell_16k`,
    `ae2:network/cells/item_storage_cell_64k_storage`,
    `ae2:network/cells/item_storage_cell_64k`,
    `ae2:network/cells/item_storage_cell_256k_storage`,
    `ae2:network/cells/item_storage_cell_256k`,
    `ae2:network/cells/fluid_storage_cell_1k_storage`,
    `ae2:network/cells/fluid_storage_cell_1k`,
    `ae2:network/cells/fluid_storage_cell_4k_storage`,
    `ae2:network/cells/fluid_storage_cell_4k`,
    `ae2:network/cells/fluid_storage_cell_16k_storage`,
    `ae2:network/cells/fluid_storage_cell_16k`,
    `ae2:network/cells/fluid_storage_cell_64k_storage`,
    `ae2:network/cells/fluid_storage_cell_64k`,
    `ae2:network/cells/fluid_storage_cell_256k_storage`,
    `ae2:network/cells/fluid_storage_cell_256k`,
    `ae2:network/cells/spatial_storage_cell_2_cubed`,
    `ae2:network/cells/spatial_storage_cell_2_cubed_storage`,
    `ae2:network/cells/spatial_storage_cell_16_cubed`,
    `ae2:network/cells/spatial_storage_cell_16_cubed_storage`,
    `ae2:network/cells/spatial_storage_cell_128_cubed`,
    `ae2:network/cells/spatial_storage_cell_128_cubed_storage`,

    //Ars Nouveau
    `ars_nouveau:mana_gem_block`,
    `ars_nouveau:mana_gem_2`,
    `ars_nouveau:enchanting_apparatus`,

    //Bettershears3
    `bettershears3:clay_shears2`,

    //Blue Skies
    `blue_skies:enchanting_table_compat`,

    //Better with Minecolonies - Disabled for Unfiy
    `betterwithminecolonies:create/stupid_dragon_breath`,
    `betterwithminecolonies:coral/tube_coral`,
    `betterwithminecolonies:coral/tube_fan`,

    //Bartering station
    `barteringstation:bartering_station`,

    //Botania
    `botania:dynamic/ancient_will_attach`,
    `botania:conversions/manasteel_to_nuggets`,
    `botania:conversions/elementium_to_nuggets`,
    `botania:conversions/terrasteel_to_nugget`,
    `botania:mana_infusion/mana_powder_dye`,
    `botania:mana_infusion/mana_quartz_deconstruct`,

    //Building Gadgets
    `buildinggadgets:construction_block_powder`,
    `buildinggadgets:construction_paste_powder`,

    //Chancecubes - Disabled to only get through Quest Rewards
    `chancecubes:chance_cube_crafting`,

    //Charging Gadgets
    `charginggadgets:charging_station`,

    //Chisel and bits - Disabled and added via the Tool System
    `chiselsandbits:chisel_iron`,
    `chiselsandbits:chisel_gold`,
    `chiselsandbits:chisel_diamond`,
    `chiselsandbits:chisel_netherite`,

    //Cyclic - Most default recipes are disabled as they are part of the Custom Tool system
    `cyclic:crafting/dispenser_alt`,
    `cyclic:crystal_helmet`,
    `cyclic:battery_clay`,
    `cyclic:glowing_helmet`,
    `cyclic:soulstone`,
    `cyclic:crafter`,
    `cyclic:uncrafter`,
    `cyclic:netherbrick_pickaxe`,
    `cyclic:melter`,
    `cyclic:solidifier`,
    `cyclic:sandstone_pickaxe`,
    `cyclic:emerald_pickaxe`,
    `cyclic:crystal_pickaxe`,
    `cyclic:netherbrick_shovel`,
    `cyclic:sandstone_shovel`,
    `cyclic:emerald_shovel`,
    `cyclic:crystal_shovel`,
    `cyclic:netherbrick_sword`,
    `cyclic:sandstone_sword`,
    `cyclic:emerald_sword`,
    `cyclic:crystal_sword`,
    `cyclic:netherbrick_hoe`,
    `cyclic:sandstone_hoe`,
    `cyclic:emerald_hoe`,
    `cyclic:crystal_hoe`,
    `cyclic:emerald_chestplate`,
    `cyclic:crystal_chestplate`,
    `cyclic:emerald_leggings`,
    `cyclic:crystal_leggings`,
    `cyclic:emerald_boots`,
    `cyclic:crystal_boots`,
    `cyclic:emerald_axe`,
    `cyclic:emerald_helmet`,
    `cyclic:crystal_axe`,
    `cyclic:sandstone_axe`,
    `cyclic:netherbrick_axe`,
    `cyclic:obsidian_pressure_plate`,
    `cyclic:copper_pressure_plate`,
    `cyclic:netherite_pressure_plate`,
    `cyclic:crusher`,
    `cyclic:trash`,
    `cyclic:soundproofing`,

    //Create - Disabled for Unfiy/custom tool system related stuff
    `create:mixing/andesite_alloy_from_zinc`,
    `create:crafting/materials/andesite_alloy_from_block`,
    `thermal:compat/create/smelter_create_alloy_andesite_alloy`,
    `create:washing/construction_paste`,
    `create_sa:slime_helmet_recipe`,
    `create_sa:slime_boots_recipe`,
    `create:crafting/appliances/diving_helmet`,
    `create:crafting/appliances/diving_boots`,
    `create_sa:brass_chestplate_recipe`,
    `create_sa:brass_helmet_recipe`,
    `create_sa:brass_leggings_recipe`,
    `create_sa:brass_boots_recipe`,
    `create_sa:zinc_chestplate_recipe`,
    `create_sa:zinc_helmet_recipe`,
    `create_sa:zinc_leggings_recipe`,
    `create_sa:zinc_bootss_recipe`,
    `create_sa:copper_chestplate_recipe`,
    `create_sa:copper_helmet_recipe`,
    `create_sa:copper_legging_recipe`,
    `create_sa:copper_boots_recipe`,
    `createaddition:crafting/spool`,
    `createaddition:compat/immersiveengineering/blastingfurnace_preheater`,
    `create:crafting/materials/electron_tube`,
    `create:crafting/kinetics/millstone`,
    `create:crafting/kinetics/basin`,
    `create:crafting/kinetics/empty_blaze_burner`,
    `create:crafting/kinetics/large_cogwheel`,
    `create:crafting/kinetics/large_cogwheelfrom_little`,
    `create:crafting/kinetics/mechanical_piston`,
    `create:crafting/kinetics/mechanical_press`,
    `create:crafting/schematics/schematicannon`,
    `create:crafting/materials/copper_casing`,
    `create:crafting/materials/rose_quartz`,
    `create:crafting/materials/shadow_steel_casing`,
    `create:crafting/materials/refined_radiance_casing`,
    `create:crafting/materials/andesite_casing`,
    `create:crafting/materials/brass_casing`,
    `create:materials/electron_tube`,
    `create:mechanical_crafting/crushing_wheel`,
    `create:mixing/andesite_alloy`,
    `create:crafting/materials/copper_ingot_from_decompacting`,
    `create:crafting/materials/copper_ingot_from_compacting`,
    `create:blasting/copper_ingot_from_ore`,
    `create:smelting/copper_ingot_from_ore`,
    `create:blasting/lead_ingot_compat_eidolon`,
    `create:blasting/lead_ingot_compat_thermal`,
    `create:blasting/ingot_lead_compat_mekanism`,
    `create:blasting/ingot_lead_compat_immersiveengineering`,
    `create:smelting/ingot_lead_compat_immersiveengineering`,
    `create:smelting/lead_ingot_compat_thermal`,
    `create:smelting/lead_ingot_compat_eidolon`,
    `create:smelting/ingot_lead_compat_mekanism`,
    `create_sa:brass_pickaxe_recipe`,
    `create_sa:brass_axe_recipe`,
    `create_sa:brass_sword_recipe`,
    `create_sa:brass_hoe_recipe`,
    `create_sa:copper_pickaxe_recipe`,
    `create_sa:copper_axe_recipe`,
    `create_sa:copper_hoe_recipe`,
    `create_sa:copper_sword_recipe`,
    `create_sa:zinc_pickaxe_recipe`,
    `create_sa:zinc_axe_recipe`,
    `create_sa:zinc_sword_recipe`,
    `create_sa:zinc_hoe_recipe`,
    `createaddition:crushing/diamond_ore`,
    `createaddition:compat/mekanism/rose_quartz_metallurgic_infusing`,

    //Culture delight - Disabled for Unfiy related stuff
    `culturaldelights:eggplant_crate`,

    //Decorative blocks - Disabled to prevent alternative ways to bypass the Custom recipe for torch and soul torch
    `decorative_blocks:torch_from_chandelier`,
    `decorative_blocks:soul_torch_from_soul_chandelier`,

    //Delightful - Disabled to prevent alternative ways to bypass the Custom recipe for torch and soul torch
    `delightful:torch_from_animal_oil_bottle`,

    //Doom - Recipes are disabled as they are part of the Custom Tool system
    `doom:argent_axe`,
    `doom:argent_hoe`,
    `doom:argent_shovel`,
    `doom:argent_pickaxe`,
    `doom:argent_sword`,

    //Eidolon - Disabled to prevent multiply version of the same items
    `eidolon:silver_helmet`,
    `eidolon:silver_chestplate`,
    `eidolon:silver_leggings`,
    `eidolon:silver_boots`,
    `eidolon:silver_sword`,
    `eidolon:silver_pickaxe`,
    `eidolon:silver_axe`,
    `eidolon:silver_shovel`,
    `eidolon:silver_hoe`,

    //Lootbundles - Disabled to only be able to gotten through Quest Rewards
    `lootbundles:loot_bundle`,
    `lootbundles:fragment`,

    //mekanism - Disabled to prevent two recipes(One from Mekanism and the active create)
    `mekanism:induction/cell/basic`,

    //Natures Aura
    `naturesaura:infused_iron_block`,

    //pneumaticcraft
    `pneumaticcraft:heat_frame_cooling/plastic`,

    //rebornstorage
    `rebornstorage:disks/small_item_storage_disk_from_storage_housing`,
    `rebornstorage:disks/small_item_disk`,
    `rebornstorage:disks/small_fluid_disk`,
    `rebornstorage:disks/medium_item_storage_disk_from_storage_housing`,
    `rebornstorage:disks/medium_item_disk`,
    `rebornstorage:disks/medium_fluid_disk`,
    `rebornstorage:disks/large_item_storage_disk_from_storage_housing`,
    `rebornstorage:disks/large_item_disk`,
    `rebornstorage:disks/large_fluid_disk`,
    `rebornstorage:disks/small_fluid_storage_disk_from_storage_housing`,
    `rebornstorage:disks/medium_fluid_storage_disk_from_storage_housing`,
    `rebornstorage:disks/large_fluid_storage_disk_from_storage_housing`,
    `rebornstorage:disks/larger_item_storage_disk_from_storage_housing`,
    `rebornstorage:disks/larger_fluid_storage_disk_from_storage_housing`,
    `rebornstorage:disks/larger_item_disk`,
    `rebornstorage:disks/larger_fluid_disk`,
    `rebornstorage:parts/small_fluid_disk_part`,
    `rebornstorage:parts/small_item_disk_part`,
    `rebornstorage:parts/medium_fluid_disk_part`,
    `rebornstorage:parts/medium_item_disk_part`,
    `rebornstorage:parts/large_item_disk_part`,
    `rebornstorage:parts/large_fluid_disk_part`,
    `rebornstorage:parts/larger_item_disk_part`,
    `rebornstorage:parts/larger_fluid_disk_part`,
    `rebornstorage:multiblock_cpu`,
    `rebornstorage:multiblock_storage`,
    `rebornstorage:parts/raw_super_advanced_processor`,

    //Trading Post
    `tradingpost:trading_post`,

    //Thermal
    `thermal:storage/rose_gold_nugget_from_ingot`,

    //Upgraded Aquatic
    `upgrade_aquatic:river_pressure_plate`,
    `upgrade_aquatic:driftwood_pressure_plate`,

    //Undead Unleashed
    `undead_unleashed:grave_metal_axe_crafting`,
    `undead_unleashed:grave_metal_sword_crafting`,
    `undead_unleashed:scythe_crafting`,
    `undead_unleashed:tombdigger_maul_crafting`,

    //Waystones
    `waystones:bound_scroll`,
    `waystones:return_scroll`,
    `waystones:warp_scroll`,
    `waystones:warp_stone`,
    `waystones:waystone`,
    `waystones:mossy_waystone`,
    `waystones:mossy_waystone_convert`,
    `waystones:sandy_waystone`,
    `waystones:warp_dust`,
    
    //xnet
    `xnet:controller`,
    `xnet:netcable_routing`,
    `xnet:router`,
    `xnet:wireless_router`,
    `xnet:netcable_red_dye`,
    `xnet:netcable_red`,
    `xnet:netcable_green_dye`,
    `xnet:netcable_green`,
    `xnet:netcable_blue_dye`,
    `xnet:netcable_blue`,
    `xnet:netcable_yellow`,
    `xnet:netcable_yellow_dye`,
    `xnet:connector_red_dye`,
    `xnet:connector_red`,
    `xnet:connector_green_dye`,
    `xnet:connector_green`,
    `xnet:connector_blue_dye`,
    `xnet:connector_blue`,
    `xnet:connector_yellow_dye`,
    `xnet:connector_yellow`,
    `xnet:advanced_connector_red_dye`,
    `xnet:advanced_connector_red`,
    `xnet:advanced_connector_green_dye`,
    `xnet:advanced_connector_green`,
    `xnet:advanced_connector_blue_dye`,
    `xnet:advanced_connector_blue`,
    `xnet:advanced_connector_yellow_dye`,
    `xnet:advanced_connector_yellow`,
    `xnet:advanced_connector_routing`,
    `xnet:connector_routing`
    ])
  })
})
})