PlayerEvents.loggedIn((e) => {
	if (!e.player.stages.has('starting_items')) {
		e.player.stages.add('starting_items')

		e.player.setOffHandItem('minecraft:shield')
		e.player.setHeadArmorItem('minecraft:leather_helmet')
		e.player.setChestArmorItem('minecraft:leather_chestplate')
		e.player.setLegsArmorItem('minecraft:leather_leggings')
		e.player.setFeetArmorItem('minecraft:leather_boots')
		e.player.give('4x minecraft:oak_sapling')
		e.player.give('minecraft:iron_sword')
		e.player.give('minecraft:iron_pickaxe')
		e.player.give('minecraft:iron_shovel')
		e.player.give('minecraft:iron_axe')
		e.player.give('constructionwand:iron_wand')
		e.player.give('naturescompass:naturescompass')
		e.player.give('sophisticatedbackpacks:backpack')
		e.player.give('prefab:item_moderate_house')
		e.player.give('prefab:item_starter_farm')
		e.player.give('4x minecraft:cookie')
		e.player.give('comforts:sleeping_bag_light_blue')
		e.player.give('minecraft:crafting_table')
		e.player.give('corail_woodcutter:oak_woodcutter')
	}
})
