#KubeJS Common Properties
#Tue Jul 18 11:04:32 CDT 2023
matchJsonRecipes=true
allowAsyncStreams=true
announceReload=true
serverOnly=false
hideServerScriptErrors=false
saveDevPropertiesInConfig=false
packmode=default
debugInfo=false
