ServerEvents.recipes(e => {
  e.shaped('forbidden_arcanus:soul_extractor', ['A  ', 'BBC', 'D  '], {
    A: 'minecraft:glass_bottle',
    B: '#forge:bricks/nether',
    C: '#forge:blocks/quartz',
    D: '#forge:gems/quartz'
  })
  e.shapeless('forbidden_arcanus:bat_wing', 'reliquary:bat_wing')

  removeRecipeByID(e, [
    'forbidden_arcanus:aquatic_dragon_scale',
    'forbidden_arcanus:slimec_pickaxe',
    'forbidden_arcanus:draco_arcanus_pickaxe',
    'forbidden_arcanus:draco_arcanus_axe',
    'forbidden_arcanus:draco_arcanus_sword',
    'forbidden_arcanus:draco_arcanus_hoe',
    'forbidden_arcanus:eternal_stella',
    'forbidden_arcanus:arcane_gold_ingot',
    'forbidden_arcanus:corrupti_dust',
    'forbidden_arcanus:golden_dragon_scale',
    'forbidden_arcanus:mundabitur_dust',
    'forbidden_arcanus:obsidian_ingot',
    'forbidden_arcanus:purifying_soap',
    'forbidden_arcanus:silver_dragon_scale',
    'forbidden_arcanus:bone_pickaxe',
    'forbidden_arcanus:infernum_pickaxe',
    'forbidden_arcanus:obsidian_pickaxe',
    'forbidden_arcanus:obsidian_axe',
    'forbidden_arcanus:reinforced_arcane_golden_pickaxe',
    'forbidden_arcanus:reinforced_arcane_golden_axe',
    'forbidden_arcanus:arcane_golden_pickaxe',
    'forbidden_arcanus:arcane_golden_axe',
    'forbidden_arcanus:bone_shovel',
    'forbidden_arcanus:obsidian_shovel',
    'forbidden_arcanus:reinforced_arcane_golden_shovel',
    'forbidden_arcanus:arcane_golden_shovel',
    'forbidden_arcanus:arcane_gold_chestplate',
    'forbidden_arcanus:arcane_gold_helmet',
    'forbidden_arcanus:arcane_gold_leggings',
    'forbidden_arcanus:arcane_gold_boots',
    'forbidden_arcanus:obsidian_helmet',
    'forbidden_arcanus:obsidian_shoulder_pads',
    'forbidden_arcanus:bone_sword',
    'forbidden_arcanus:obsidian_sword',
    'forbidden_arcanus:reinforced_arcane_golden_sword',
    'forbidden_arcanus:arcane_golden_sword',
    'forbidden_arcanus:bone_hoe',
    'forbidden_arcanus:obsidian_hoe',
    'forbidden_arcanus:reinforced_arcane_golden_hoe',
    'forbidden_arcanus:arcane_golden_hoe',
    'forbidden_arcanus:deorum_pressure_plate',
    'forbidden_arcanus:fungyss_pressure_plate',
    'forbidden_arcanus:cherry_pressure_plate',
    'forbidden_arcanus:edelwood_pressure_plate',
    'forbidden_arcanus:mysterywood_pressure_plate',
    'forbidden_arcanus:polished_darkstone_pressure_plate',
    'forbidden_arcanus:soul_extractor'
  ])
})
