ServerEvents.recipes(e => {
  e.shaped(Item.of('immersiveengineering:blueprint', '{blueprint:"components"}'), [' k ', 'ddd', 'ppp'], {
    k: 'ae2:printed_logic_processor',
    d: '#forge:dyes/blue',
    p: '#forge:paper'
  })

  removeRecipeByID(e, [

    'immersiveengineering:crafting/hammercrushing_aluminum',
    'immersiveengineering:crafting/raw_hammercrushing_aluminum',
    'immersiveengineering:crafting/hammercrushing_lead',
    'immersiveengineering:crafting/raw_hammercrushing_lead',
    'immersiveengineering:crafting/raw_hammercrushing_osmium',
    'immersiveengineering:crafting/hammercrushing_osmium',
    'immersiveengineering:crafting/raw_hammercrushing_nickel',
    'immersiveengineering:crafting/hammercrushing_nickel',
    'immersiveengineering:crafting/raw_hammercrushing_osmium',
    'immersiveengineering:crafting/hammercrushing_osmium',
    'immersiveengineering:crafting/raw_hammercrushing_platinum',
    'immersiveengineering:crafting/hammercrushing_platinum',
    'immersiveengineering:crafting/raw_hammercrushing_silver',
    'immersiveengineering:crafting/hammercrushing_silver',
    'immersiveengineering:crafting/raw_hammercrushing_tin',
    'immersiveengineering:crafting/hammercrushing_tin',
    'immersiveengineering:crafting/raw_hammercrushing_uranium',
    'immersiveengineering:crafting/hammercrushing_uranium',
    'immersiveengineering:crafting/raw_hammercrushing_zinc',
    'immersiveengineering:crafting/hammercrushing_zinc',
    'immersiveengineering:crafting/raw_hammercrushing_iron',
    'immersiveengineering:crafting/hammercrushing_iron',
    'immersiveengineering:crafting/raw_hammercrushing_copper',
    'immersiveengineering:crafting/hammercrushing_copper',
    'immersiveengineering:crafting/raw_hammercrushing_gold',
    'immersiveengineering:crafting/hammercrushing_gold',
    'immersiveengineering:crafting/raw_hammercrushing_osmium',
    'immersiveengineering:crafting/hammercrushing_osmium',
    'immersiveengineering:crafting/plate_ostrum_hammering',
    'immersiveengineering:crafting/plate_desh_hammering',
    'immersiveengineering:crafting/plate_calorite_hammering',
    'immersiveengineering:crafting/strip_lv',
    'immersiveengineering:crafting/strip_mv',
    'immersiveengineering:crafting/blueprint_components',
    'immersiveengineering:crafting/treated_wood_horizontal_from_packaged',
    'immersiveengineering:arcfurnace/insulating_glass',
    'immersiveengineering:crafting/component_iron',
    'immersiveengineering:crafting/component_steel',
    'immersiveengineering:crafting/blastingfurnace_preheater',
    'immersiveengineering:crafting/concrete2',
    'immersiveengineering:crafting/plate_gold_hammering',
    'immersiveengineering:crafting/plate_aluminum_hammering',
    'immersiveengineering:crafting/plate_lead_hammering',
    'immersiveengineering:crafting/plate_nickel_hammering',
    'immersiveengineering:crafting/plate_silver_hammering',
    'immersiveengineering:crafting/plate_uranium_hammering',
    'immersiveengineering:crafting/plate_steel_hammering',
    'immersiveengineering:crafting/plate_electrum_hammering',
    'immersiveengineering:crafting/plate_iron_hammering',
    'immersiveengineering:crafting/plate_copper_hammering',
    'immersiveengineering:crafting/plate_constantan_hammering',
    'immersiveengineering:crafting/storage_copper_to_ingot_copper',
    'immersiveengineering:crafting/storage_aluminum_to_ingot_aluminum',
    'immersiveengineering:crafting/storage_silver_to_ingot_silver',
    'immersiveengineering:crafting/nugget_copper_to_ingot_copper',
    'immersiveengineering:crafting/nugget_aluminum_to_ingot_aluminum',
    'immersiveengineering:crafting/nugget_silver_to_ingot_silver',
    'immersiveengineering:crafting/nugget_lead_to_ingot_lead',
    'immersiveengineering:crafting/storage_lead_to_ingot_lead',
    'immersiveengineering:crafting/nugget_lead_to_ingot_lead',
    'immersiveengineering:crafting/ingot_lead_from_blasting',
    'immersiveengineering:crafting/ingot_lead_from_dust_from_blasting',
    'immersiveengineering:crafting/ingot_lead_from_dust',
    'immersiveengineering:crafting/ingot_lead',
    'immersiveengineering:crafting/ingot_copper_from_blasting',
    'immersiveengineering:crafting/ingot_copper_from_dust_from_blasting',
    'immersiveengineering:crafting/ingot_copper_from_smelting',
    'immersiveengineering:crafting/ingot_copper_from_dust',
    'immersiveengineering:crafting/ingot_copper',
    'immersiveengineering:crusher/ore_diamond',
    'immersiveengineering:crusher/ore_emerald',
    'immersiveengineering:crusher/ore_lapis',
    'immersiveengineering:crafting/torch',
  ])
})
