
[General]
	#How much time should there be after arming a landmine before it can be triggered in ticks? 1 second = 20 ticks.
	#Requires a world reload
	#Allowed Range: 0 ~ 2400  Default: 100
	activationDelay = 100

	[General."Explosion Land Mine"]
		#Should the explosion land mine be reusable?
		#Requires a world reload
		#Allowed Values: true, false  Default: false
		explosionReusable = false
		#Should the explosion from an explosion landmine break blocks?
		#Requires a world reload
		#Allowed Values: true, false  Default: true
		explosionBreakBlocks = false
		#Should the explosion from an explosion landmine cause fire?
		#Requires a world reload
		#Allowed Values: true, false  Default: false
		explosionCausesFire = true

	[General."Potion Land Mine"]
		#Should the potion land mine be reusable?
		#Requires a world reload
		#Allowed Values: true, false  Default: true
		potionReusable = true

	[General."Launch Land Mine"]
		#Should the launch land mine be reusable?
		#Requires a world reload
		#Allowed Values: true, false  Default: true
		launchReusable = true

	[General."Teleport Land Mine"]
		#Should the teleport land mine be reusable?
		#Requires a world reload
		#Allowed Values: true, false  Default: true
		teleportReusable = true

	[General."Fire Land Mine"]
		#Should the fire land mine be reusable?
		#Requires a world reload
		#Allowed Values: true, false  Default: true
		fireReusable = true

	[General."Snow Land Mine"]
		#Should the snow land mine be reusable?
		#Requires a world reload
		#Allowed Values: true, false  Default: true
		snowReusable = true

	[General."Zombie Land Mine"]
		#Should the zombie land mine be reusable?
		#Requires a world reload
		#Allowed Values: true, false  Default: false
		zombieReusable = false

	[General."Levitation Land Mine"]
		#Should the levitation land mine be reusable?
		#Requires a world reload
		#Allowed Values: true, false  Default: true
		levitationReusable = true

	[General."Lightning Land Mine"]
		#Should the lightning land mine be reusable?
		#Requires a world reload
		#Allowed Values: true, false  Default: true
		lightningReusable = true

	[General."Arrow Land Mine"]
		#Should the arrow land mine be reusable?
		#Requires a world reload
		#Allowed Values: true, false  Default: true
		arrowsReusable = true

	[General."Fake Land Mine"]
		#Should the fake land mine be reusable?
		#Requires a world reload
		#Allowed Values: true, false  Default: true
		fakeReusable = true

