onEvent('recipes', e => {
	e.recipes.immersiveengineering.crusher('emendatusenigmatica:obsidian_dust', '#forge:obsidian', [Item.of('minecraft:obsidian').chance(0.75)])
	e.recipes.immersiveengineering.crusher('emendatusenigmatica:dimensional_dust', '#forge:chunks/dimensional', [Item.of('emendatusenigmatica:dimensional_gem').chance(0.02)])
	e.recipes.immersiveengineering.crusher('emendatusenigmatica:sulfur_dust', '#forge:chunks/sulfur', [Item.of('emendatusenigmatica:sulfur_gem').chance(0.02)])
	e.recipes.immersiveengineering.crusher('emendatusenigmatica:apatite_dust', '#forge:chunks/apatite', [Item.of('emendatusenigmatica:apatite_gem').chance(0.02)])
	e.recipes.immersiveengineering.crusher('emendatusenigmatica:cinnabar_dust', '#forge:chunks/cinnabar', [Item.of('emendatusenigmatica:cinnabar_gem').chance(0.02)])
	e.recipes.immersiveengineering.crusher('emendatusenigmatica:fluorite_dust', '#forge:chunks/fluorite', [Item.of('emendatusenigmatica:fluorite_gem').chance(0.02)])
	e.recipes.immersiveengineering.crusher('emendatusenigmatica:certus_quartz_dust', '#forge:chunks/certus_quartz', [Item.of('emendatusenigmatica:certus_quartz_gem').chance(0.02)])
	e.recipes.immersiveengineering.crusher('emendatusenigmatica:iridium_dust', '#forge:chunks/iridium', [Item.of('emendatusenigmatica:iridium_ingot').chance(0.02)])
	e.recipes.immersiveengineering.crusher('emendatusenigmatica:cobalt_dust', '#forge:chunks/cobalt', [Item.of('emendatusenigmatica:cobalt_ingot').chance(0.02)])
	e.recipes.immersiveengineering.crusher('emendatusenigmatica:zinc_dust', '#forge:chunks/zinc', [Item.of('emendatusenigmatica:zinc_ingot').chance(0.02)])
	e.recipes.immersiveengineering.crusher('emendatusenigmatica:tin_dust', '#forge:chunks/tin', [Item.of('emendatusenigmatica:tin_ingot').chance(0.02)])
	e.recipes.immersiveengineering.crusher('emendatusenigmatica:osmium_dust', '#forge:chunks/osmium', [Item.of('emendatusenigmatica:osmium_ingot').chance(0.02)])
	e.recipes.immersiveengineering.crusher('emendatusenigmatica:uranium_dust', '#forge:chunks/uranium', [Item.of('emendatusenigmatica:uranium_ingot').chance(0.02)])
	e.recipes.immersiveengineering.crusher('emendatusenigmatica:nickel_dust', '#forge:chunks/nickel', [Item.of('emendatusenigmatica:nickel_ingot').chance(0.02)])
	e.recipes.immersiveengineering.crusher('emendatusenigmatica:lead_dust', '#forge:chunks/lead', [Item.of('emendatusenigmatica:lead_ingot').chance(0.02)])
	e.recipes.immersiveengineering.crusher('emendatusenigmatica:silver_dust', '#forge:chunks/silver', [Item.of('emendatusenigmatica:silver_ingot').chance(0.02)])
	e.recipes.immersiveengineering.crusher('emendatusenigmatica:aluminum_dust', '#forge:chunks/aluminum', [Item.of('emendatusenigmatica:aluminum_ingot').chance(0.02)])
	e.recipes.immersiveengineering.crusher('emendatusenigmatica:copper_dust', '#forge:chunks/copper', [Item.of('emendatusenigmatica:copper_ingot').chance(0.02)])
	e.recipes.immersiveengineering.crusher('emendatusenigmatica:nickel_dust', '#forge:chunks/nickel', [Item.of('emendatusenigmatica:nickel_ingot').chance(0.02)])
	e.recipes.immersiveengineering.crusher('emendatusenigmatica:lapis_dust', '#forge:chunks/lapis', [Item.of('minecraft:lapis_lazuli').chance(0.02)])
	e.recipes.immersiveengineering.crusher('emendatusenigmatica:emerald_dust', '#forge:chunks/emerald', [Item.of('minecraft:emerald').chance(0.02)])
	e.recipes.immersiveengineering.crusher('emendatusenigmatica:diamond_dust', '#forge:chunks/diamond', [Item.of('minecraft:diamond').chance(0.02)])
	e.recipes.immersiveengineering.crusher('emendatusenigmatica:gold_dust', '#forge:chunks/gold', [Item.of('minecraft:gold_ingot').chance(0.02)])
	e.recipes.immersiveengineering.crusher('emendatusenigmatica:iron_dust', '#forge:chunks/iron', [Item.of('minecraft:iron_ingot').chance(0.02)])
	e.recipes.immersiveengineering.crusher('emendatusenigmatica:coal_dust', '#forge:chunks/coal', [Item.of('minecraft:coal').chance(0.04)])
	e.recipes.immersiveengineering.crusher('minecraft:redstone', '#forge:chunks/redstone', [Item.of('extendedcrafting:redstone_ingot').chance(0.02)])
	e.recipes.immersiveengineering.crusher('emendatusenigmatica:potassium_nitrate_dust', '#forge:chunks/potassium_nitrate', [Item.of('emendatusenigmatica:potassium_nitrate_gem').chance(0.02)])
	e.recipes.immersiveengineering.crusher('2x minecraft:sugar', 'minecraft:sugar_cane', [Item.of('minecraft:sugar').chance(0.1)])
	e.recipes.immersiveengineering.crusher('4x occultism:crushed_end_stone', '#forge:end_stones', [Item.of('minecraft:obsidian').chance(0.75)])
})
