onEvent('recipes', e => {
	e.recipes.immersiveengineering.metal_press('mekanism:hdpe_sheet', 'mekanism:hdpe_pellet', 'immersiveengineering:mold_plate')
	e.recipes.immersiveengineering.metal_press('emendatusenigmatica:diamond_plate', '#forge:gems/diamond', 'immersiveengineering:mold_plate')
	e.recipes.immersiveengineering.metal_press('emendatusenigmatica:emerald_plate', '#forge:gems/emerald', 'immersiveengineering:mold_plate')
	e.recipes.immersiveengineering.metal_press('emendatusenigmatica:lapis_plate', '#forge:gems/lapis', 'immersiveengineering:mold_plate')
	e.recipes.immersiveengineering.metal_press('emendatusenigmatica:signalum_plate', '#forge:ingots/signalum', 'immersiveengineering:mold_plate')
	e.recipes.immersiveengineering.metal_press('emendatusenigmatica:lumium_plate', '#forge:ingots/lumium', 'immersiveengineering:mold_plate')
	e.recipes.immersiveengineering.metal_press('emendatusenigmatica:enderium_plate', '#forge:ingots/enderium', 'immersiveengineering:mold_plate')
	e.recipes.immersiveengineering.metal_press('kubejs:compressed_iron_plate', '#forge:ingots/compressed_iron', 'immersiveengineering:mold_plate')
	e.recipes.immersiveengineering.metal_press('pneumaticcraft:compressed_iron_gear', '#forge:ingots/compressed_iron', 'immersiveengineering:mold_gear')
	e.recipes.immersiveengineering.metal_press('emendatusenigmatica:diamond_gear', '#forge:gems/diamond', 'immersiveengineering:mold_gear')
	e.recipes.immersiveengineering.metal_press('emendatusenigmatica:emerald_gear', '#forge:gems/emerald', 'immersiveengineering:mold_gear')
	e.recipes.immersiveengineering.metal_press('emendatusenigmatica:lapis_gear', '#forge:gems/lapis', 'immersiveengineering:mold_gear')
	e.recipes.immersiveengineering.metal_press('emendatusenigmatica:quartz_gear', '#forge:gems/quartz', 'immersiveengineering:mold_gear')
	e.recipes.immersiveengineering.metal_press('emendatusenigmatica:signalum_gear', '#forge:ingots/signalum', 'immersiveengineering:mold_gear')
	e.recipes.immersiveengineering.metal_press('emendatusenigmatica:lumium_gear', '#forge:ingots/lumium', 'immersiveengineering:mold_gear')
	e.recipes.immersiveengineering.metal_press('emendatusenigmatica:enderium_gear', '#forge:ingots/enderium', 'immersiveengineering:mold_gear')
});
