ServerEvents.tags('item', e => {
  //#region ADDITIONS
  //e.add('chipped:glowstone', /rechiseled:glowstone_/)
  //e.add('forge:beach_grass', 'upgrade_aquatic:beachgrass')
  e.add('forge:sheetmetals/copper', 'createdeco:copper_sheet_metal')
  //e.add('forge:blocks/quartz', [/rechiseled:quartz_block/, /chipped:quartz_block/])
  //e.add('forge:blood', ['betteranimalsplus:horseshoe_crab_blood', /iceandfire:.+_dragon_blood/, 'mythicbotany:kvasir_blood', 'twilightforest:fiery_blood'])
  //e.add('forge:bones/wither', 'tconstruct:necrotic_bone')
  //e.add('forge:bricks/nether', [/rechiseled:nether_bricks/, /chipped:nether_bricks/])
  //e.add('forge:candles', [/quark:[a-z_]*_candle/, 'eidolon:candle', 'eidolon:candlestick', 'occultism:candle_white', 'supplementaries:candelabra', 'supplementaries:candelabra_silver', 'supplementaries:candle_holder'])
  e.add('forge:cauldron', ['minecraft:cauldron', 'reliquary:apothecary_cauldron'])
  e.add('forge:chains', ['minecraft:chain', 'decorative_blocks:chain'])
  //e.add('minecraft:beds', 'undergarden:depthrock_bed')
  e.add('forge:chunks/coal', 'ironcoals:base_coal_chunk')
//  e.add('forge:clock', ['minecraft:clock', 'supplementaries:clock_block', 'create:mysterious_cuckoo_clock', 'cyclic:clock', 'create:cuckoo_clock', 'botania:cosmetic_clock_eye'])
  e.add('forge:corals', [/\w+:(?!dead)(\w+)_coral$/])
  e.add('forge:coral_blocks', [/\w+:(?!dead)(\w+)_coral_block$/])
  e.add('forge:coral_fans', [/\w+:(?!dead)(\w+)_coral_fan$/])
  e.add('forge:dead_corals', [/dead_\w+coral$/])
  e.add('forge:dead_coral_blocks', [/dead_\w+coral_block$/])
  e.add('forge:dead_coral_fans', [/dead_\w+coral_fan$/])
  //e.add('forge:end_stones', /rechiseled:end_stone/)
  //e.add('forge:furnace', [/minecraft:.+_furnace/, 'jumbofurnace:jumbo_furnace', /industrialforegoing:.+_furnace/, /engineersdecor:small_.+_furnace/, 'createaddition:furnace_burner', /ironfurnaces:.+_furnace/, 'ironfurnaces:item_spooky', 'ironfurnaces:item_xmas', 'mysticalagriculture:inferium_furnace', 'mysticalagriculture:prudentium_furnace', 'mysticalagriculture:tertium_furnace', 'thermal:machine_furnace', /atum:.+_furnace/, 'routerreborn:furnace'])
  //e.add('forge:hopper', ['minecraft:hopper', 'cyclic:hopper_fluid', 'cyclic:hopper_gold', 'naturesaura:grated_chute', 'pneumaticcraft:omnidirectional_hopper', 'pneumaticcraft:liquid_hopper', 'woodenhopper:wooden_hopper'])
  //e.add('forge:mushroom_caps', ['quark:glowshroom_block', 'undergarden:blood_mushroom_cap', 'undergarden:ink_mushroom_cap', 'undergarden:veil_mushroom_cap', 'undergarden:indigo_mushroom_cap'])
  e.add('forge:mushroom_colonies/brown', 'aquaculture:brown_shrooma')
  e.add('forge:mushroom_colonies/red', 'aquaculture:red_shrooma')
  //e.add('forge:mushroom_stems', ['quark:glowshroom_stem', 'undergarden:veil_mushroom_stalk', 'undergarden:blood_mushroom_stalk', 'undergarden:indigo_mushroom_stalk'])
  //e.add('forge:netherbricks/red', /rechiseled:red_nether_bricks/)
  //e.add('forge:netherrack', ['quark:netherrack_bricks', /rechiseled:netherack_/])
  e.add('forge:piston', ['minecraft:sticky_piston', 'minecraft:piston', 'create:mechanical_piston', 'create:sticky_mechanical_piston', 'multipiston:multipistonblock'])
  //e.add('forge:sandstone/red', /rechiseled:red_sandstone/)
  //e.add('forge:sandstone/colorless', /rechiseled:sandstone_/)
  //e.add('forge:slime_block', ['#tconstruct:slime_block', '#quark:slime_blocks'])
  //e.add('forge:tallow', ['quark:tallow', 'eidolon:tallow', 'occultism:tallow'])
  //e.add('forge:tools/bucket', ['minecraft:bucket', 'botania:open_bucket', 'naturesaura:color_changer', 'forbidden_arcanus:edelwood_bucket'])
  //e.add('forge:tools/hammer', ['emendatusenigmatica:enigmatic_hammer', 'framedblocks:framed_hammer', 'mcwroofs:roofing_hammer', 'atum:nebu_hammer', 'blue_skies:crushing_hammer', 'createaddition:overcharged_hammer', 'iceandfire:troll_weapon_hammer', 'dungeons_gear:great_hammer'])
  //e.add('forge:tools/hoes', [/minecraft:.*_hoe/, /botania:.*_hoe/, /naturesaura:.*_hoe/, /undergarden:.*_hoe/, /druidcraft:.*_hoe/, /create_stuff_additions:.*_hoe/, /blue_skies:.*_hoe/, /aiotbotania:.*_hoe/, /aiotbotania:.*_aiot/, /mysticalagriculture:.*_hoe/, /iceandfire:.*_hoe/, /atum:.*_hoe/, /aquaculture:.*_hoe/, /twilightforest:.*_hoe/, /draconicevolution:.*_hoe/, /cyclic:.*_hoe/, /appliedenergistics2:.*_hoe/, /immersiveengineering:hoe_steel/, /forbidden_arcanus:.*_hoe/])
  e.add('forge:tools/pickaxe', /blue_skies:.*_pickaxe/, /mysticalagriculture:.*_pickaxe/, /create_sa:.*_pickaxe/)
  e.add('forge:tools/wrench', ['refinedstorage:wrench'])
  e.add('forge:workbenches', ['minecraft:crafting_table', /blue_skies:\w+_crafting_table/])
  e.add('forge:workbench', ['minecraft:crafting_table', /blue_skies:\w+_crafting_table/])
  //e.add('upgrade_aquatic:driftwood_logs', 'aquaculture:driftwood')

  //let realms = ['asgard', 'vanaheim', 'alfheim', 'midgard', 'joetunheim', 'muspelheim', 'niflheim', 'nidavellir', 'helheim']
  //realms.forEach(realm => e.add(`botania:runes/${realm}`, `mythicbotany:${realm}_rune`))
  //#endregion

  //#region REMOVALS
  //e.remove('forge:string', 'undergarden:twistytwig')
  //#endregion
})
