[server]

[server.optout]
pattern_excludes = ""
pattern_includes = ""
without_clinker_bricks = false
without_slag_bricks = false
without_rebar_concrete = false
without_gas_concrete = false
without_walls = false
without_stairs = false
without_ie_concrete_wall = false
without_panzer_glass = false
without_crafting_table = false
without_lab_furnace = false
without_electrical_furnace = false
without_treated_wood_furniture = false
without_metal_furniture = false
without_windows = false
without_light_sources = false
without_ladders = false
without_chair_sitting = false
without_mob_chair_sitting = false
without_ladder_speed_boost = false
without_crafting_table_history = false
without_valves = false
without_passive_fluid_accumulator = false
without_waste_incinerator = false
without_sign_plates = false
without_floor_grating = false
without_factory_dropper = false
without_factory_hopper = false
without_factory_placer = false
without_block_breaker = false
without_solar_panel = false
without_fluid_funnel = false
without_mineral_smelter = false
without_milking_machine = false
without_tree_cutter = false
without_labeled_crate = false
without_slabs = false
without_halfslabs = false
without_poles = false
without_hsupports = false
without_recipes = false
without_fences = false

[server.miscellaneous]
with_experimental = false
without_direct_slab_pickup = false
with_creative_mode_device_drops = false

[server.tweaks]
furnace_smelting_speed_percent = 130
furnace_fuel_efficiency_percent = 100
furnace_boost_energy_consumption = 24
chair_mob_sitting_probability_percent = 10.0
chair_mob_standup_probability_percent = 1.0
with_crafting_quickmove_buttons = false
without_crafting_mouse_scrolling = false
pipevalve_max_flowrate = 1000
pipevalve_redstone_gain = 20
e_furnace_speed_percent = 200
e_furnace_power_consumption = 16
e_furnace_automatic_pulling = false
small_solar_panel_peak_production = 40
block_breaker_power_consumption = 64
block_breaker_reluctance = 17
block_breaker_min_breaking_time = 15
block_breaker_requires_power = false
tree_cuttter_energy_consumption = 64
tree_cuttter_cutting_time_needed = 60
tree_cuttter_requires_power = false
milking_machine_energy_consumption = 0
milking_machine_milking_delay = 4000
