[milestones]
heartsPerMilestone = 1
milestones = [25, 50, 100, 150, 200, 250, 300, 350, 400, 500]

[filtering]
blacklist = [
	"farmersdelight:fried_egg",
	"environmental:cherry_pie",
	"environmental:apple_pie",
	"simplefarming:apple_pie",
	"simplefarming:blueberry_pie",
	"abnormals_delight:adzuki_cake_slice",
	"abnormals_delight:banana_cake_slice",
	"abnormals_delight:cherry_pantry",
	"abnormals_delight:chocolate_cake_slice",
	"abnormals_delight:cooked_duck_fillet",
	"abnormals_delight:cooked_venison_shanks",
	"abnormals_delight:duck_fillet",
	"abnormals_delight:mint_cake_slice",
	"abnormals_delight:necromium_knife",
	"abnormals_delight:passionfruit_glazed_duck",
	"abnormals_delight:seared_venison",
	"abnormals_delight:strawberry_cake_slice",
	"abnormals_delight:vanilla_cake_slice",
	"abnormals_delight:venison_shanks",
	"abnormals_delight:willow_pantry",
	"abnormals_delight:wisteria_pantry",
	"abnormals_delight:escargot",
	"abnormals_delight:maple_cookie",
	"abnormals_delight:maple_glazed_bacon",
	"aquaculture:frog_legs_cooked",
	"aquaculture:frog_legs_raw",
	"projectvibrantjourneys:clam",
	"projectvibrantjourneys:clam_chowder",
	"projectvibrantjourneys:cooked_clam",
	"simplefarming:chocolate",
	"simplefarming:cooked_bacon",
	"simplefarming:cooked_egg",
	"simplefarming:raw_bacon"
]
