onEvent('item.tooltip', tooltip => {
  tooltip.add(['minecraft:smithing_table'], 'Can be Found Within Chest that are located in Structures throughout the World')
  tooltip.add(['routerreborn:coppercoil'], 'Can be Found Within Chest that are located in Structures throughout the World')
  tooltip.add(['enigmaticlegacy:etherium_helmet'], 'Can be Found Within Chest at stage 5 in Dungeoncrawl Dungeons throughout the World')
  tooltip.add(['enigmaticlegacy:etherium_chestplate'], 'Can be Found Within a Tower Chest in Towers throughout the World')
  tooltip.add(['enigmaticlegacy:etherium_leggings'], 'Can be Found Within a Quark MonsterBox throughout the World at a weight of 1')
  tooltip.add(['enigmaticlegacy:etherium_boots'], 'Can be Found Within a Cyclops Cave throughout the World at a weight of 1')
  tooltip.add(['inventorypets:solstice_sword'], 'Can be Found Within a Quark MonsterBox throughout the World at a weight of 1')
  tooltip.add(['enigmaticlegacy:etherium_pickaxe'], 'Can be Found Within a Witch Hut throughout the World at a weight of 1')
  tooltip.add(['enigmaticlegacy:etherium_axe'], 'Can be Found Within a Mausoleum throughout the World at a weight of 1')
  tooltip.add(['enigmaticlegacy:etherium_shovel'], 'Can be Found Within a Red Giant Mushroom throughout the World at a weight of 1')
  tooltip.add(['enigmaticlegacy:etherium_sword'], 'Can be Found Within a Illager Campsite Tent throughout the World at a weight of 1')
  tooltip.add(['enigmaticlegacy:etherium_scythe'], 'Can be Found Within a Astral Sorcery Shine Chest throughout the World at a weight of 1')
})