onEvent('recipes', e => {
	//Atum

	e.smithing(Item.of('atum:limestone_pickaxe'), Item.of('minecraft:stone_pickaxe').ignoreNBT(), 'atum:limestone_cracked')
	e.smithing(Item.of('atum:limestone_hoe'), Item.of('minecraft:stone_hoe').ignoreNBT(), 'atum:limestone_cracked')
	e.smithing(Item.of('atum:limestone_sword'), Item.of('minecraft:stone_sword').ignoreNBT(), 'atum:limestone_cracked')
	e.smithing(Item.of('atum:stoneguard_sword'), Item.of('minecraft:stone_sword').ignoreNBT(), '#forge:ingots/khnumite')
	e.smithing(Item.of('atum:stoneguard_greatsword'), Item.of('atum:stoneguard_sword').ignoreNBT(), '#forge:ingots/khnumite')
	e.smithing(Item.of('atum:desert_chest_iron'), Item.of('atum:wanderer_chest').ignoreNBT(), 'minecraft:iron_chestplate')
	e.smithing(Item.of('atum:desert_chest_gold'), Item.of('atum:wanderer_chest').ignoreNBT(), 'minecraft:golden_chestplate')
	e.smithing(Item.of('atum:desert_chest_diamond'), Item.of('atum:wanderer_chest').ignoreNBT(), 'minecraft:diamond_chestplate')
	e.smithing(Item.of('atum:desert_helmet_iron'), Item.of('atum:wanderer_helmet').ignoreNBT(), 'minecraft:iron_helmet')
	e.smithing(Item.of('atum:desert_helmet_gold'), Item.of('atum:wanderer_helmet').ignoreNBT(), 'minecraft:golden_helmet')
	e.smithing(Item.of('atum:desert_helmet_diamond'), Item.of('atum:wanderer_helmet').ignoreNBT(), 'minecraft:diamond_helmet')
	e.smithing(Item.of('atum:desert_legs_iron'), Item.of('atum:wanderer_legs').ignoreNBT(), 'minecraft:iron_leggings')
	e.smithing(Item.of('atum:desert_legs_gold'), Item.of('atum:wanderer_legs').ignoreNBT(), 'minecraft:golden_leggings')
	e.smithing(Item.of('atum:desert_legs_diamond'), Item.of('atum:wanderer_legs').ignoreNBT(), 'minecraft:diamond_leggings')
	e.smithing(Item.of('atum:desert_boots_iron'), Item.of('atum:wanderer_boots').ignoreNBT(), 'minecraft:iron_boots')
	e.smithing(Item.of('atum:desert_boots_gold'), Item.of('atum:wanderer_boots').ignoreNBT(), 'minecraft:golden_boots')
	e.smithing(Item.of('atum:desert_boots_diamond'), Item.of('atum:wanderer_boots').ignoreNBT(), 'minecraft:diamond_boots')

	// Aiot Botania

	e.smithing(Item.of('aiotbotania:livingwood_axe'), Item.of('minecraft:wooden_axe').ignoreNBT(), '#botania:livingwood')
	e.smithing(Item.of('aiotbotania:livingrock_axe'), Item.of('minecraft:stone_axe').ignoreNBT(), '#botania:livingrock')
	e.smithing(Item.of('aiotbotania:livingwood_shovel'), Item.of('minecraft:wooden_shovel').ignoreNBT(), '#botania:livingwood')
	e.smithing(Item.of('aiotbotania:livingrock_shovel'), Item.of('minecraft:stone_shovel').ignoreNBT(), '#botania:livingrock')
	e.smithing(Item.of('aiotbotania:livingwood_hoe'), Item.of('minecraft:wooden_hoe').ignoreNBT(), '#botania:livingwood')
	e.smithing(Item.of('aiotbotania:livingrock_hoe'), Item.of('minecraft:stone_hoe').ignoreNBT(), '#botania:livingrock')
	e.smithing(Item.of('aiotbotania:livingwood_sword'), Item.of('minecraft:wooden_sword').ignoreNBT(), '#botania:livingwood')
	e.smithing(Item.of('aiotbotania:livingrock_sword'), Item.of('minecraft:stone_sword').ignoreNBT(), '#botania:livingrock')
	e.smithing(Item.of('aiotbotania:livingwood_pickaxe'), Item.of('minecraft:wooden_pickaxe').ignoreNBT(), '#botania:livingwood')
	e.smithing(Item.of('aiotbotania:livingrock_pickaxe'), Item.of('minecraft:stone_pickaxe').ignoreNBT(), '#botania:livingrock')
	e.smithing(Item.of('aiotbotania:terra_hoe'), Item.of('minecraft:netherite_hoe').ignoreNBT(), '#forge:ingots/terrasteel')

	//Aquaculture

	e.smithing(Item.of('aquaculture:neptunium_pickaxe'), Item.of('minecraft:netherite_pickaxe').ignoreNBT(), '#forge:ingots/neptunium')
	e.smithing(Item.of('aquaculture:neptunium_chestplate'), Item.of('minecraft:netherite_chestplate').ignoreNBT(), '#forge:ingots/neptunium')
	e.smithing(Item.of('aquaculture:neptunium_sword'), Item.of('minecraft:netherite_sword').ignoreNBT(), '#forge:ingots/neptunium')
	e.smithing(Item.of('aquaculture:neptunium_axe'), Item.of('minecraft:netherite_axe').ignoreNBT(), '#forge:ingots/neptunium')
	e.smithing(Item.of('aquaculture:neptunium_shovel'), Item.of('minecraft:netherite_shovel').ignoreNBT(), '#forge:ingots/neptunium')
	e.smithing(Item.of('aquaculture:neptunium_hoe'), Item.of('minecraft:netherite_hoe').ignoreNBT(), '#forge:ingots/neptunium')
	e.smithing(Item.of('aquaculture:neptunium_helmet'), Item.of('minecraft:netherite_helmet').ignoreNBT(), '#forge:ingots/neptunium')
	e.smithing(Item.of('aquaculture:neptunium_leggings'), Item.of('minecraft:netherite_leggings').ignoreNBT(), '#forge:ingots/neptunium')
	e.smithing(Item.of('aquaculture:neptunium_boots'), Item.of('minecraft:netherite_boots').ignoreNBT(), '#forge:ingots/neptunium')
	e.smithing(Item.of('aquaculture:neptunium_bow'), '#forge:string', '#forge:ingots/neptunium')

	//Appliedenergistics2

	e.smithing(Item.of('appliedenergistics2:certus_quartz_axe'), Item.of('minecraft:iron_axe').ignoreNBT(), '#forge:gems/certus_quartz')
	e.smithing(Item.of('appliedenergistics2:nether_quartz_axe'), Item.of('minecraft:iron_axe').ignoreNBT(), '#forge:gems/quartz')
	e.smithing(Item.of('appliedenergistics2:certus_quartz_shovel'), Item.of('minecraft:iron_shovel').ignoreNBT(), '#forge:gems/certus_quartz')
	e.smithing(Item.of('appliedenergistics2:nether_quartz_shovel'), Item.of('minecraft:iron_shovel').ignoreNBT(), '#forge:gems/quartz')
	e.smithing(Item.of('appliedenergistics2:certus_quartz_hoe'), Item.of('minecraft:iron_hoe').ignoreNBT(), '#forge:gems/certus_quartz')
	e.smithing(Item.of('appliedenergistics2:nether_quartz_hoe'), Item.of('minecraft:iron_hoe').ignoreNBT(), '#forge:gems/quartz')
	e.smithing(Item.of('appliedenergistics2:certus_quartz_sword'), Item.of('minecraft:iron_sword').ignoreNBT(), '#forge:gems/certus_quartz')
	e.smithing(Item.of('appliedenergistics2:nether_quartz_sword'), Item.of('minecraft:iron_sword').ignoreNBT(), '#forge:gems/quartz')
	e.smithing(Item.of('appliedenergistics2:certus_quartz_pickaxe'), Item.of('minecraft:iron_pickaxe').ignoreNBT(), '#forge:gems/certus_quartz')
	e.smithing(Item.of('appliedenergistics2:nether_quartz_pickaxe'), Item.of('minecraft:iron_pickaxe').ignoreNBT(), '#forge:gems/quartz')

	//Blue Skies

	e.smithing(Item.of('blue_skies:horizonite_boots'), Item.of('minecraft:diamond_boots').ignoreNBT(), '#blue_skies:ingots/horizonite')
	e.smithing(Item.of('blue_skies:charoite_boots'), Item.of('minecraft:diamond_boots').ignoreNBT(), '#blue_skies:gems/charoite')
	e.smithing(Item.of('blue_skies:diopside_boots'), Item.of('minecraft:netherite_boots').ignoreNBT(), '#blue_skies:gems/diopside')
	e.smithing(Item.of('blue_skies:aquite_boots'), Item.of('minecraft:diamond_boots').ignoreNBT(), '#blue_skies:gems/aquite')
	e.smithing(Item.of('blue_skies:pyrope_boots'), Item.of('minecraft:iron_boots').ignoreNBT(), '#blue_skies:gems/pyrope')
	e.smithing(Item.of('blue_skies:shadow_boots'), Item.of('minecraft:golden_boots').ignoreNBT(), '#forge:ingots/shadow_steel')
	e.smithing(Item.of('blue_skies:horizonite_axe'), Item.of('minecraft:diamond_axe').ignoreNBT(), '#blue_skies:ingots/horizonite')
	e.smithing(Item.of('blue_skies:charoite_axe'), Item.of('minecraft:diamond_axe').ignoreNBT(), '#blue_skies:gems/charoite')
	e.smithing(Item.of('blue_skies:diopside_axe'), Item.of('minecraft:netherite_axe').ignoreNBT(), '#blue_skies:gems/diopside')
	e.smithing(Item.of('blue_skies:aquite_axe'), Item.of('minecraft:diamond_axe').ignoreNBT(), '#blue_skies:gems/aquite')
	e.smithing(Item.of('blue_skies:pyrope_axe'), Item.of('minecraft:iron_axe').ignoreNBT(), '#blue_skies:gems/pyrope')
	e.smithing(Item.of('blue_skies:lunar_stone_axe'), Item.of('minecraft:stone_axe').ignoreNBT(), 'blue_skies:lunar_cobblestone')
	e.smithing(Item.of('blue_skies:turquoise_stone_axe'), Item.of('minecraft:stone_axe').ignoreNBT(), 'blue_skies:turquoise_cobblestone')
	e.smithing(Item.of('blue_skies:cherry_axe'), Item.of('minecraft:wooden_axe').ignoreNBT(), 'blue_skies:cherry_planks')
	e.smithing(Item.of('blue_skies:maple_axe'), Item.of('minecraft:wooden_axe').ignoreNBT(), 'blue_skies:maple_planks')
	e.smithing(Item.of('blue_skies:frostbright_axe'), Item.of('minecraft:wooden_axe').ignoreNBT(), 'blue_skies:frostbright_planks')
	e.smithing(Item.of('blue_skies:dusk_axe'), Item.of('minecraft:wooden_axe').ignoreNBT(), 'blue_skies:dusk_planks')
	e.smithing(Item.of('blue_skies:starlit_axe'), Item.of('minecraft:wooden_axe').ignoreNBT(), 'blue_skies:starlit_planks')
	e.smithing(Item.of('blue_skies:lunar_axe'), Item.of('minecraft:wooden_axe').ignoreNBT(), 'blue_skies:lunar_planks')
	e.smithing(Item.of('blue_skies:bluebright_axe'), Item.of('minecraft:wooden_axe').ignoreNBT(), 'blue_skies:bluebright_planks')
	e.smithing(Item.of('blue_skies:horizonite_shovel'), Item.of('minecraft:diamond_shovel').ignoreNBT(), '#blue_skies:ingots/horizonite')
	e.smithing(Item.of('blue_skies:charoite_shovel'), Item.of('minecraft:diamond_shovel').ignoreNBT(), '#blue_skies:gems/charoite')
	e.smithing(Item.of('blue_skies:diopside_shovel'), Item.of('minecraft:netherite_shovel').ignoreNBT(), '#blue_skies:gems/diopside')
	e.smithing(Item.of('blue_skies:aquite_shovel'), Item.of('minecraft:diamond_shovel').ignoreNBT(), '#blue_skies:gems/aquite')
	e.smithing(Item.of('blue_skies:pyrope_shovel'), Item.of('minecraft:iron_shovel').ignoreNBT(), '#blue_skies:gems/pyrope')
	e.smithing(Item.of('blue_skies:lunar_stone_shovel'), Item.of('minecraft:stone_shovel').ignoreNBT(), 'blue_skies:lunar_cobblestone')
	e.smithing(Item.of('blue_skies:turquoise_stone_shovel'), Item.of('minecraft:stone_shovel').ignoreNBT(), 'blue_skies:turquoise_cobblestone')
	e.smithing(Item.of('blue_skies:cherry_shovel'), Item.of('minecraft:wooden_shovel').ignoreNBT(), 'blue_skies:cherry_planks')
	e.smithing(Item.of('blue_skies:maple_shovel'), Item.of('minecraft:wooden_shovel').ignoreNBT(), 'blue_skies:maple_planks')
	e.smithing(Item.of('blue_skies:frostbright_shovel'), Item.of('minecraft:wooden_shovel').ignoreNBT(), 'blue_skies:frostbright_planks')
	e.smithing(Item.of('blue_skies:dusk_shovel'), Item.of('minecraft:wooden_shovel').ignoreNBT(), 'blue_skies:dusk_planks')
	e.smithing(Item.of('blue_skies:starlit_shovel'), Item.of('minecraft:wooden_shovel').ignoreNBT(), 'blue_skies:starlit_planks')
	e.smithing(Item.of('blue_skies:lunar_shovel'), Item.of('minecraft:wooden_shovel').ignoreNBT(), 'blue_skies:lunar_planks')
	e.smithing(Item.of('blue_skies:bluebright_shovel'), Item.of('minecraft:wooden_shovel').ignoreNBT(), 'blue_skies:bluebright_planks')
	e.smithing(Item.of('blue_skies:horizonite_hoe'), Item.of('minecraft:diamond_hoe').ignoreNBT(), '#blue_skies:ingots/horizonite')
	e.smithing(Item.of('blue_skies:charoite_hoe'), Item.of('minecraft:diamond_hoe').ignoreNBT(), '#blue_skies:gems/charoite')
	e.smithing(Item.of('blue_skies:diopside_hoe'), Item.of('minecraft:netherite_hoe').ignoreNBT(), '#blue_skies:gems/diopside')
	e.smithing(Item.of('blue_skies:aquite_hoe'), Item.of('minecraft:diamond_hoe').ignoreNBT(), '#blue_skies:gems/aquite')
	e.smithing(Item.of('blue_skies:pyrope_hoe'), Item.of('minecraft:iron_hoe').ignoreNBT(), '#blue_skies:gems/pyrope')
	e.smithing(Item.of('blue_skies:lunar_stone_hoe'), Item.of('minecraft:stone_hoe').ignoreNBT(), 'blue_skies:lunar_cobblestone')
	e.smithing(Item.of('blue_skies:turquoise_stone_hoe'), Item.of('minecraft:stone_hoe').ignoreNBT(), 'blue_skies:turquoise_cobblestone')
	e.smithing(Item.of('blue_skies:cherry_hoe'), Item.of('minecraft:wooden_hoe').ignoreNBT(), 'blue_skies:cherry_planks')
	e.smithing(Item.of('blue_skies:maple_hoe'), Item.of('minecraft:wooden_hoe').ignoreNBT(), 'blue_skies:maple_planks')
	e.smithing(Item.of('blue_skies:frostbright_hoe'), Item.of('minecraft:wooden_hoe').ignoreNBT(), 'blue_skies:frostbright_planks')
	e.smithing(Item.of('blue_skies:dusk_hoe'), Item.of('minecraft:wooden_hoe').ignoreNBT(), 'blue_skies:dusk_planks')
	e.smithing(Item.of('blue_skies:starlit_hoe'), Item.of('minecraft:wooden_hoe').ignoreNBT(), 'blue_skies:starlit_planks')
	e.smithing(Item.of('blue_skies:lunar_hoe'), Item.of('minecraft:wooden_hoe').ignoreNBT(), 'blue_skies:lunar_planks')
	e.smithing(Item.of('blue_skies:bluebright_hoe'), Item.of('minecraft:wooden_hoe').ignoreNBT(), 'blue_skies:bluebright_planks')
	e.smithing(Item.of('blue_skies:horizonite_sword'), Item.of('minecraft:diamond_sword').ignoreNBT(), '#blue_skies:ingots/horizonite')
	e.smithing(Item.of('blue_skies:charoite_sword'), Item.of('minecraft:diamond_sword').ignoreNBT(), '#blue_skies:gems/charoite')
	e.smithing(Item.of('blue_skies:diopside_sword'), Item.of('minecraft:netherite_sword').ignoreNBT(), '#blue_skies:gems/diopside')
	e.smithing(Item.of('blue_skies:aquite_sword'), Item.of('minecraft:diamond_sword').ignoreNBT(), '#blue_skies:gems/aquite')
	e.smithing(Item.of('blue_skies:pyrope_sword'), Item.of('minecraft:iron_sword').ignoreNBT(), '#blue_skies:gems/pyrope')
	e.smithing(Item.of('blue_skies:lunar_stone_sword'), Item.of('minecraft:stone_sword').ignoreNBT(), 'blue_skies:lunar_cobblestone')
	e.smithing(Item.of('blue_skies:turquoise_stone_sword'), Item.of('minecraft:stone_sword').ignoreNBT(), 'blue_skies:turquoise_cobblestone')
	e.smithing(Item.of('blue_skies:cherry_sword'), Item.of('minecraft:wooden_sword').ignoreNBT(), 'blue_skies:cherry_planks')
	e.smithing(Item.of('blue_skies:maple_sword'), Item.of('minecraft:wooden_sword').ignoreNBT(), 'blue_skies:maple_planks')
	e.smithing(Item.of('blue_skies:frostbright_sword'), Item.of('minecraft:wooden_sword').ignoreNBT(), 'blue_skies:frostbright_planks')
	e.smithing(Item.of('blue_skies:dusk_sword'), Item.of('minecraft:wooden_sword').ignoreNBT(), 'blue_skies:dusk_planks')
	e.smithing(Item.of('blue_skies:starlit_sword'), Item.of('minecraft:wooden_sword').ignoreNBT(), 'blue_skies:starlit_planks')
	e.smithing(Item.of('blue_skies:lunar_sword'), Item.of('minecraft:wooden_sword').ignoreNBT(), 'blue_skies:lunar_planks')
	e.smithing(Item.of('blue_skies:bluebright_sword'), Item.of('minecraft:wooden_sword').ignoreNBT(), 'blue_skies:bluebright_planks')
	e.smithing(Item.of('blue_skies:horizonite_chestplate'), Item.of('minecraft:diamond_chestplate').ignoreNBT(), '#blue_skies:ingots/horizonite')
	e.smithing(Item.of('blue_skies:charoite_chestplate'), Item.of('minecraft:diamond_chestplate').ignoreNBT(), '#blue_skies:gems/charoite')
	e.smithing(Item.of('blue_skies:diopside_chestplate'), Item.of('minecraft:netherite_chestplate').ignoreNBT(), '#blue_skies:gems/diopside')
	e.smithing(Item.of('blue_skies:aquite_chestplate'), Item.of('minecraft:diamond_chestplate').ignoreNBT(), '#blue_skies:gems/aquite')
	e.smithing(Item.of('blue_skies:pyrope_chestplate'), Item.of('minecraft:iron_chestplate').ignoreNBT(), '#blue_skies:gems/pyrope')
	e.smithing(Item.of('blue_skies:shadow_chestplate'), Item.of('minecraft:netherite_chestplate').ignoreNBT(), '#forge:ingots/shadow_steel')
	e.smithing(Item.of('blue_skies:horizonite_helmet'), Item.of('minecraft:diamond_helmet').ignoreNBT(), '#blue_skies:ingots/horizonite')
	e.smithing(Item.of('blue_skies:charoite_helmet'), Item.of('minecraft:diamond_helmet').ignoreNBT(), '#blue_skies:gems/charoite')
	e.smithing(Item.of('blue_skies:diopside_helmet'), Item.of('minecraft:netherite_helmet').ignoreNBT(), '#blue_skies:gems/diopside')
	e.smithing(Item.of('blue_skies:aquite_helmet'), Item.of('minecraft:diamond_helmet').ignoreNBT(), '#blue_skies:gems/aquite')
	e.smithing(Item.of('blue_skies:pyrope_helmet'), Item.of('minecraft:iron_helmet').ignoreNBT(), '#blue_skies:gems/pyrope')
	e.smithing(Item.of('blue_skies:shadow_helmet'), Item.of('minecraft:netherite_helmet').ignoreNBT(), '#forge:ingots/shadow_steel')
	e.smithing(Item.of('blue_skies:horizonite_leggings'), Item.of('minecraft:diamond_leggings').ignoreNBT(), '#blue_skies:ingots/horizonite')
	e.smithing(Item.of('blue_skies:charoite_leggings'), Item.of('minecraft:diamond_leggings').ignoreNBT(), '#blue_skies:gems/charoite')
	e.smithing(Item.of('blue_skies:diopside_leggings'), Item.of('minecraft:netherite_leggings').ignoreNBT(), '#blue_skies:gems/diopside')
	e.smithing(Item.of('blue_skies:aquite_leggings'), Item.of('minecraft:diamond_leggings').ignoreNBT(), '#blue_skies:gems/aquite')
	e.smithing(Item.of('blue_skies:pyrope_leggings'), Item.of('minecraft:iron_leggings').ignoreNBT(), '#blue_skies:gems/pyrope')
	e.smithing(Item.of('blue_skies:shadow_leggings'), Item.of('minecraft:netherite_leggings').ignoreNBT(), '#forge:ingots/shadow_steel')
	e.smithing(Item.of('blue_skies:horizonite_pickaxe'), Item.of('minecraft:diamond_pickaxe').ignoreNBT(), '#blue_skies:ingots/horizonite')
	e.smithing(Item.of('blue_skies:charoite_pickaxe'), Item.of('minecraft:diamond_pickaxe').ignoreNBT(), '#blue_skies:gems/charoite')
	e.smithing(Item.of('blue_skies:diopside_pickaxe'), Item.of('minecraft:netherite_pickaxe').ignoreNBT(), '#blue_skies:gems/diopside')
	e.smithing(Item.of('blue_skies:aquite_pickaxe'), Item.of('minecraft:diamond_pickaxe').ignoreNBT(), '#blue_skies:gems/aquite')
	e.smithing(Item.of('blue_skies:pyrope_pickaxe'), Item.of('minecraft:iron_pickaxe').ignoreNBT(), '#blue_skies:gems/pyrope')
	e.smithing(Item.of('blue_skies:lunar_stone_pickaxe'), Item.of('minecraft:stone_pickaxe').ignoreNBT(), 'blue_skies:lunar_cobblestone')
	e.smithing(Item.of('blue_skies:turquoise_stone_pickaxe'), Item.of('minecraft:stone_pickaxe').ignoreNBT(), 'blue_skies:turquoise_cobblestone')
	e.smithing(Item.of('blue_skies:cherry_pickaxe'), Item.of('minecraft:wooden_pickaxe').ignoreNBT(), 'blue_skies:cherry_planks')
	e.smithing(Item.of('blue_skies:maple_pickaxe'), Item.of('minecraft:wooden_pickaxe').ignoreNBT(), 'blue_skies:maple_planks')
	e.smithing(Item.of('blue_skies:frostbright_pickaxe'), Item.of('minecraft:wooden_pickaxe').ignoreNBT(), 'blue_skies:frostbright_planks')
	e.smithing(Item.of('blue_skies:dusk_pickaxe'), Item.of('minecraft:wooden_pickaxe').ignoreNBT(), 'blue_skies:dusk_planks')
	e.smithing(Item.of('blue_skies:starlit_pickaxe'), Item.of('minecraft:wooden_pickaxe').ignoreNBT(), 'blue_skies:starlit_planks')
	e.smithing(Item.of('blue_skies:lunar_pickaxe'), Item.of('minecraft:wooden_pickaxe').ignoreNBT(), 'blue_skies:lunar_planks')
	e.smithing(Item.of('blue_skies:bluebright_pickaxe'), Item.of('minecraft:wooden_pickaxe').ignoreNBT(), 'blue_skies:bluebright_planks')

	// Botania

	e.smithing(Item.of('botania:livingwood_bow'), 'botania:mana_string', 'botania:livingwood_twig')
	e.smithing(Item.of('botania:terrasteel_boots'), Item.of('minecraft:netherite_boots').ignoreNBT(), '#forge:ingots/terrasteel')
	e.smithing(Item.of('botania:manasteel_hoe'), Item.of('minecraft:iron_hoe').ignoreNBT(), '#forge:ingots/manasteel')
	e.smithing(Item.of('botania:elementium_hoe'), Item.of('minecraft:iron_hoe').ignoreNBT(), '#forge:ingots/elementium')
	e.smithing(Item.of('botania:manasteel_pick'), Item.of('minecraft:iron_pickaxe').ignoreNBT(), '#forge:ingots/manasteel')
	e.smithing(Item.of('botania:elementium_pickaxe'), Item.of('minecraft:iron_pickaxe').ignoreNBT(), '#forge:ingots/elementium')
	e.smithing(Item.of('botania:manasteel_axe'), Item.of('minecraft:iron_axe').ignoreNBT(), '#forge:ingots/manasteel')
	e.smithing(Item.of('botania:elementium_axe'), Item.of('minecraft:iron_axe').ignoreNBT(), '#forge:ingots/elementium')
	e.smithing(Item.of('botania:manasteel_shovel'), Item.of('minecraft:iron_shovel').ignoreNBT(), '#forge:ingots/manasteel')
	e.smithing(Item.of('botania:elementium_shovel'), Item.of('minecraft:iron_shovel').ignoreNBT(), '#forge:ingots/elementium')
	e.smithing(Item.of('botania:mana_ring'), 'botania:mana_tablet', '#forge:ingots/manasteel')
	e.smithing(Item.of('botania:aura_ring'), 'botania:rune_mana', '#forge:ingots/manasteel')
	e.smithing(Item.of('botania:magnet_ring'), 'botania:lens_magnet', '#forge:ingots/manasteel')
	e.smithing(Item.of('botania:water_ring'), 'minecraft:heart_of_the_sea', '#forge:ingots/manasteel')
	e.smithing(Item.of('botania:dodge_ring'), 'botania:rune_air', '#forge:ingots/manasteel')
	e.smithing(Item.of('botania:mining_ring'), 'botania:rune_earth', '#forge:ingots/manasteel')
	e.smithing(Item.of('botania:pixie_ring'), 'botania:pixie_dust', '#forge:ingots/elementium')
	e.smithing(Item.of('botania:reach_ring'), 'botania:rune_pride', '#forge:ingots/elementium')
	e.smithing(Item.of('botania:swap_ring'), '#forge:storage_blocks/clay', '#forge:ingots/manasteel')
	e.smithing(Item.of('botania:aura_ring_greater'), '#forge:ingots/terrasteel', 'botania:aura_ring')
	e.smithing(Item.of('botania:mana_ring_greater'), '#forge:ingots/terrasteel', 'botania:mana_ring')
	e.smithing(Item.of('botania:magnet_ring_greater'), '#forge:ingots/terrasteel', 'botania:magnet_ring')
	e.smithing(Item.of('botania:manasteel_boots'), Item.of('minecraft:iron_boots').ignoreNBT(), '#forge:ingots/manasteel')
	e.smithing(Item.of('botania:elementium_boots'), Item.of('minecraft:iron_boots').ignoreNBT(), '#forge:ingots/elementium')
	e.smithing(Item.of('botania:terrasteel_leggings'), Item.of('minecraft:netherite_leggings').ignoreNBT(), '#forge:ingots/terrasteel')
	e.smithing(Item.of('botania:manasteel_leggings'), Item.of('minecraft:iron_leggings').ignoreNBT(), '#forge:ingots/manasteel')
	e.smithing(Item.of('botania:elementium_leggings'), Item.of('minecraft:iron_leggings').ignoreNBT(), '#forge:ingots/elementium')
	e.smithing(Item.of('botania:manasteel_helmet'), Item.of('minecraft:iron_helmet').ignoreNBT(), '#forge:ingots/manasteel')
	e.smithing(Item.of('botania:elementium_helmet'), Item.of('minecraft:iron_helmet').ignoreNBT(), '#forge:ingots/elementium')
	e.smithing(Item.of('botania:manasteel_chestplate'), Item.of('minecraft:iron_chestplate').ignoreNBT(), '#forge:ingots/manasteel')
	e.smithing(Item.of('botania:elementium_chestplate'), Item.of('minecraft:iron_chestplate').ignoreNBT(), '#forge:ingots/elementium')
	e.smithing(Item.of('botania:manasteel_sword'), Item.of('minecraft:iron_sword').ignoreNBT(), '#forge:ingots/manasteel')
	e.smithing(Item.of('botania:elementium_sword'), Item.of('minecraft:iron_sword').ignoreNBT(), '#forge:ingots/elementium')
	e.smithing(Item.of('botania:terrasteel_helmet'), Item.of('minecraft:netherite_helmet').ignoreNBT(), '#forge:ingots/terrasteel')
	e.smithing(Item.of('botania:terrasteel_chestplate'), Item.of('minecraft:netherite_chestplate').ignoreNBT(), '#forge:ingots/terrasteel')

	//Cyclic
	e.smithing(Item.of('cyclic:netherbrick_pickaxe'), Item.of('minecraft:iron_pickaxe').ignoreNBT(), '#forge:bricks/nether')
	e.smithing(Item.of('cyclic:sandstone_pickaxe'), Item.of('minecraft:stone_pickaxe').ignoreNBT(), '#forge:sandstone')
	e.smithing(Item.of('cyclic:emerald_pickaxe'), Item.of('minecraft:diamond_pickaxe').ignoreNBT(), '#forge:gems/emerald')
	e.smithing(Item.of('cyclic:crystal_pickaxe'), Item.of('minecraft:netherite_pickaxe').ignoreNBT(), '#forge:gems/diamond')
	e.smithing(Item.of('cyclic:netherbrick_hoe'), Item.of('minecraft:iron_hoe').ignoreNBT(), '#forge:bricks/nether')
	e.smithing(Item.of('cyclic:sandstone_hoe'), Item.of('minecraft:stone_hoe').ignoreNBT(), '#forge:sandstone')
	e.smithing(Item.of('cyclic:emerald_hoe'), Item.of('minecraft:diamond_hoe').ignoreNBT(), '#forge:gems/emerald')
	e.smithing(Item.of('cyclic:crystal_hoe'), Item.of('minecraft:netherite_hoe').ignoreNBT(), '#forge:gems/diamond')
	e.smithing(Item.of('cyclic:netherbrick_axe'), Item.of('minecraft:iron_axe').ignoreNBT(), '#forge:bricks/nether')
	e.smithing(Item.of('cyclic:sandstone_axe'), Item.of('minecraft:stone_axe').ignoreNBT(), '#forge:sandstone')
	e.smithing(Item.of('cyclic:emerald_axe'), Item.of('minecraft:diamond_axe').ignoreNBT(), '#forge:gems/emerald')
	e.smithing(Item.of('cyclic:crystal_axe'), Item.of('minecraft:netherite_axe').ignoreNBT(), '#forge:gems/diamond')
	e.smithing(Item.of('cyclic:netherbrick_shovel'), Item.of('minecraft:iron_shovel').ignoreNBT(), '#forge:bricks/nether')
	e.smithing(Item.of('cyclic:sandstone_shovel'), Item.of('minecraft:stone_shovel').ignoreNBT(), '#forge:sandstone')
	e.smithing(Item.of('cyclic:emerald_shovel'), Item.of('minecraft:diamond_shovel').ignoreNBT(), '#forge:gems/emerald')
	e.smithing(Item.of('cyclic:crystal_shovel'), Item.of('minecraft:netherite_shovel').ignoreNBT(), '#forge:gems/diamond')
	e.smithing(Item.of('cyclic:netherbrick_sword'), Item.of('minecraft:iron_sword').ignoreNBT(), '#forge:bricks/nether')
	e.smithing(Item.of('cyclic:sandstone_sword'), Item.of('minecraft:stone_sword').ignoreNBT(), '#forge:sandstone')
	e.smithing(Item.of('cyclic:emerald_sword'), Item.of('minecraft:diamond_sword').ignoreNBT(), '#forge:gems/emerald')
	e.smithing(Item.of('cyclic:crystal_sword'), Item.of('minecraft:netherite_sword').ignoreNBT(), '#forge:gems/diamond')
	e.smithing(Item.of('cyclic:emerald_chestplate'), Item.of('minecraft:diamond_chestplate').ignoreNBT(), '#forge:gems/emerald')
	e.smithing(Item.of('cyclic:crystal_chestplate'), Item.of('minecraft:netherite_chestplate').ignoreNBT(), '#forge:gems/diamond')
	e.smithing(Item.of('cyclic:emerald_helmet'), Item.of('minecraft:diamond_helmet').ignoreNBT(), '#forge:gems/emerald')
	e.smithing(Item.of('cyclic:crystal_helmet'), Item.of('minecraft:netherite_helmet').ignoreNBT(), '#forge:gems/diamond')
	e.smithing(Item.of('cyclic:emerald_leggings'), Item.of('minecraft:diamond_leggings').ignoreNBT(), '#forge:gems/emerald')
	e.smithing(Item.of('cyclic:crystal_leggings'), Item.of('minecraft:netherite_leggings').ignoreNBT(), '#forge:gems/diamond')
	e.smithing(Item.of('cyclic:emerald_boots'), Item.of('minecraft:diamond_boots').ignoreNBT(), '#forge:gems/emerald')
	e.smithing(Item.of('cyclic:crystal_boots'), Item.of('minecraft:netherite_boots').ignoreNBT(), '#forge:gems/diamond')

	//DruidCraft
	e.smithing(Item.of('druidcraft:moonstone_sword'), Item.of('minecraft:netherite_sword').ignoreNBT(), '#forge:gems/moonstone')
	e.smithing(Item.of('druidcraft:bone_sword'), Item.of('minecraft:stone_sword').ignoreNBT(), '#forge:bones')
	e.smithing(Item.of('druidcraft:moonstone_chestplate'), Item.of('minecraft:netherite_chestplate').ignoreNBT(), '#forge:gems/moonstone')
	e.smithing(Item.of('druidcraft:chitin_chestplate'), Item.of('minecraft:iron_chestplate').ignoreNBT(), 'druidcraft:chitin')
	e.smithing(Item.of('druidcraft:bone_chestplate'), Item.of('minecraft:chainmail_chestplate').ignoreNBT(), '#forge:bones')
	e.smithing(Item.of('druidcraft:moonstone_helmet'), Item.of('minecraft:netherite_helmet').ignoreNBT(), '#forge:gems/moonstone')
	e.smithing(Item.of('druidcraft:chitin_helmet'), Item.of('minecraft:iron_helmet').ignoreNBT(), 'druidcraft:chitin')
	e.smithing(Item.of('druidcraft:bone_helmet'), Item.of('minecraft:chainmail_helmet').ignoreNBT(), '#forge:bones')
	e.smithing(Item.of('druidcraft:moonstone_leggings'), Item.of('minecraft:netherite_leggings').ignoreNBT(), '#forge:gems/moonstone')
	e.smithing(Item.of('druidcraft:chitin_leggings'), Item.of('minecraft:iron_leggings').ignoreNBT(), 'druidcraft:chitin')
	e.smithing(Item.of('druidcraft:bone_leggings'), Item.of('minecraft:chainmail_leggings').ignoreNBT(), '#forge:bones')
	e.smithing(Item.of('druidcraft:moonstone_boots'), Item.of('minecraft:netherite_boots').ignoreNBT(), '#forge:gems/moonstone')
	e.smithing(Item.of('druidcraft:chitin_boots'), Item.of('minecraft:iron_boots').ignoreNBT(), 'druidcraft:chitin')
	e.smithing(Item.of('druidcraft:bone_boots'), Item.of('minecraft:chainmail_boots').ignoreNBT(), '#forge:bones')
	e.smithing(Item.of('druidcraft:bone_shield'), '#minecraft:planks', '#forge:bones')
	e.smithing(Item.of('druidcraft:chitin_shield'), '#forge:nuggets/iron', 'druidcraft:chitin')
	e.smithing(Item.of('druidcraft:moonstone_shield'), '#forge:ingots/iron', '#forge:gems/moonstone')
	e.smithing(Item.of('druidcraft:moonstone_axe'), Item.of('minecraft:netherite_axe').ignoreNBT(), '#forge:gems/moonstone')
	e.smithing(Item.of('druidcraft:bone_axe'), Item.of('minecraft:stone_axe').ignoreNBT(), '#forge:bones')
	e.smithing(Item.of('druidcraft:moonstone_shovel'), Item.of('minecraft:netherite_shovel').ignoreNBT(), '#forge:gems/moonstone')
	e.smithing(Item.of('druidcraft:bone_shovel'), Item.of('minecraft:stone_shovel').ignoreNBT(), '#forge:bones')
	e.smithing(Item.of('druidcraft:moonstone_hoe'), Item.of('minecraft:netherite_hoe').ignoreNBT(), '#forge:gems/moonstone')
	e.smithing(Item.of('druidcraft:moonstone_pickaxe'), Item.of('minecraft:netherite_pickaxe').ignoreNBT(), '#forge:gems/moonstone')
	e.smithing(Item.of('druidcraft:bone_pickaxe'), Item.of('minecraft:stone_pickaxe').ignoreNBT(), '#forge:bones')

	//Explorer's Compass
	e.smithing(Item.of('explorerscompass:explorerscompass'), 'minecraft:compass', 'minecraft:cracked_stone_bricks')

	//Forbidden Arcanus

	e.smithing(Item.of('forbidden_arcanus:infernum_pickaxe'), Item.of('minecraft:diamond_pickaxe').ignoreNBT(), 'forbidden_arcanus:obsidian_skull')
	e.smithing(Item.of('forbidden_arcanus:reinforced_arcane_golden_pickaxe'), Item.of('minecraft:netherite_pickaxe').ignoreNBT(), 'forbidden_arcanus:edelwood_stick')
	e.smithing(Item.of('forbidden_arcanus:arcane_golden_pickaxe'), Item.of('minecraft:netherite_pickaxe').ignoreNBT(), '#forge:ingots/arcane_gold')
	e.smithing(Item.of('forbidden_arcanus:slimec_pickaxe'), Item.of('minecraft:diamond_pickaxe').ignoreNBT(), 'forbidden_arcanus:golden_feather')
	e.smithing(Item.of('forbidden_arcanus:arcane_gold_leggings'), Item.of('minecraft:netherite_leggings').ignoreNBT(), '#forge:ingots/arcane_gold')
	e.smithing(Item.of('forbidden_arcanus:arcane_gold_boots'), Item.of('minecraft:netherite_boots').ignoreNBT(), '#forge:ingots/arcane_gold')
	e.smithing(Item.of('forbidden_arcanus:reinforced_arcane_golden_axe'), Item.of('minecraft:netherite_axe').ignoreNBT(), 'forbidden_arcanus:edelwood_stick')
	e.smithing(Item.of('forbidden_arcanus:arcane_golden_axe'), Item.of('minecraft:netherite_axe').ignoreNBT(), '#forge:ingots/arcane_gold')
	e.smithing(Item.of('forbidden_arcanus:reinforced_arcane_golden_shovel'), Item.of('minecraft:netherite_shovel').ignoreNBT(), 'forbidden_arcanus:edelwood_stick')
	e.smithing(Item.of('forbidden_arcanus:arcane_golden_shovel'), Item.of('minecraft:netherite_shovel').ignoreNBT(), '#forge:ingots/arcane_gold')
	e.smithing(Item.of('forbidden_arcanus:reinforced_arcane_golden_hoe'), Item.of('minecraft:netherite_hoe').ignoreNBT(), 'forbidden_arcanus:edelwood_stick')
	e.smithing(Item.of('forbidden_arcanus:arcane_golden_hoe'), Item.of('minecraft:netherite_hoe').ignoreNBT(), '#forge:ingots/arcane_gold')
	e.smithing(Item.of('forbidden_arcanus:reinforced_arcane_golden_sword'), Item.of('minecraft:netherite_sword').ignoreNBT(), 'forbidden_arcanus:edelwood_stick')
	e.smithing(Item.of('forbidden_arcanus:arcane_golden_sword'), Item.of('minecraft:netherite_sword').ignoreNBT(), '#forge:ingots/arcane_gold')
	e.smithing(Item.of('forbidden_arcanus:arcane_gold_chestplate'), Item.of('minecraft:netherite_chestplate').ignoreNBT(), '#forge:ingots/arcane_gold')
	e.smithing(Item.of('forbidden_arcanus:arcane_gold_helmet'), Item.of('minecraft:netherite_helmet').ignoreNBT(), '#forge:ingots/arcane_gold')
	e.smithing(Item.of('forbidden_arcanus:draco_arcanus_pickaxe'), Item.of('minecraft:netherite_pickaxe').ignoreNBT(), '#forge:dragon_scales')

	//Gobber Armor
	e.smithing(Item.of('gobber2:gobber2_helmet_end'), Item.of('minecraft:netherite_helmet').ignoreNBT(), 'gobber2:gobber2_ingot_end')
	e.smithing(Item.of('gobber2:gobber2_helmet_nether'), Item.of('minecraft:netherite_helmet').ignoreNBT(), 'gobber2:gobber2_ingot_nether')
	e.smithing(Item.of('gobber2:gobber2_helmet'), Item.of('minecraft:netherite_helmet').ignoreNBT(), 'gobber2:gobber2_ingot')
	e.smithing(Item.of('gobber2:gobber2_boots_end'), Item.of('minecraft:netherite_boots').ignoreNBT(), 'gobber2:gobber2_ingot_end')
	e.smithing(Item.of('gobber2:gobber2_boots_nether'), Item.of('minecraft:netherite_boots').ignoreNBT(), 'gobber2:gobber2_ingot_nether')
	e.smithing(Item.of('gobber2:gobber2_boots'), Item.of('minecraft:netherite_boots').ignoreNBT(), 'gobber2:gobber2_ingot')
	e.smithing(Item.of('gobber2:gobber2_chestplate_end'), Item.of('minecraft:netherite_chestplate').ignoreNBT(), 'gobber2:gobber2_ingot_end')
	e.smithing(Item.of('gobber2:gobber2_chestplate_nether'), Item.of('minecraft:netherite_chestplate').ignoreNBT(), 'gobber2:gobber2_ingot_nether')
	e.smithing(Item.of('gobber2:gobber2_chestplate'), Item.of('minecraft:netherite_chestplate').ignoreNBT(), 'gobber2:gobber2_ingot')
	e.smithing(Item.of('gobber2:gobber2_leggings_end'), Item.of('minecraft:netherite_leggings').ignoreNBT(), 'gobber2:gobber2_ingot_end')
	e.smithing(Item.of('gobber2:gobber2_leggings_nether'), Item.of('minecraft:netherite_leggings').ignoreNBT(), 'gobber2:gobber2_ingot_nether')
	e.smithing(Item.of('gobber2:gobber2_leggings'), Item.of('minecraft:netherite_leggings').ignoreNBT(), 'gobber2:gobber2_ingot')

	//Gobber Rings
	e.smithing(Item.of('gobber2:gobber2_ring_phoenix'), 'gobber2:gobber2_ring_nether', 'minecraft:magma_cream')

	//Gobber Tools

	e.smithing(Item.of('gobber2:gobber2_pickaxe_end'), Item.of('minecraft:netherite_pickaxe').ignoreNBT(), 'gobber2:gobber2_ingot_end')
	e.smithing(Item.of('gobber2:gobber2_pickaxe_nether'), Item.of('minecraft:netherite_pickaxe').ignoreNBT(), 'gobber2:gobber2_ingot_nether')
	e.smithing(Item.of('gobber2:gobber2_pickaxe'), Item.of('minecraft:netherite_pickaxe').ignoreNBT(), 'gobber2:gobber2_ingot')
	e.smithing(Item.of('gobber2:gobber2_paxel_stars'), 'gobber2:gobber2_paxel_end', 'gobber2:gobber2_staff_stars')
	e.smithing(Item.of('gobber2:gobber2_sword_sniper'), 'gobber2:gobber2_sword_end', 'gobber2:gobber2_staff_sniper')
	e.smithing(Item.of('gobber2:gobber2_sword_traveler'), 'gobber2:gobber2_sword_end', 'gobber2:gobber2_ring_traveler')
	e.smithing(Item.of('gobber2:gobber2_bow'), '#forge:string', 'gobber2:gobber2_rod')
	e.smithing(Item.of('gobber2:gobber2_bow_nether'), '#forge:string', 'gobber2:gobber2_rod_nether')
	e.smithing(Item.of('gobber2:gobber2_bow_end'), '#forge:string', 'gobber2:gobber2_rod_end')
	e.smithing(Item.of('gobber2:gobber2_axe_end'), Item.of('minecraft:netherite_axe').ignoreNBT(), 'gobber2:gobber2_ingot_end')
	e.smithing(Item.of('gobber2:gobber2_axe_nether'), Item.of('minecraft:netherite_axe').ignoreNBT(), 'gobber2:gobber2_ingot_nether')
	e.smithing(Item.of('gobber2:gobber2_axe'), Item.of('minecraft:netherite_axe').ignoreNBT(), 'gobber2:gobber2_ingot')
	e.smithing(Item.of('gobber2:gobber2_shovel_end'), Item.of('minecraft:netherite_shovel').ignoreNBT(), 'gobber2:gobber2_ingot_end')
	e.smithing(Item.of('gobber2:gobber2_excavator_end'), Item.of('minecraft:netherite_shovel').ignoreNBT(), 'gobber2:gobber2_rod_end')
	e.smithing(Item.of('gobber2:gobber2_shovel_nether'), Item.of('minecraft:netherite_shovel').ignoreNBT(), 'gobber2:gobber2_ingot_nether')
	e.smithing(Item.of('gobber2:gobber2_excavator_nether'), Item.of('minecraft:netherite_shovel').ignoreNBT(), 'gobber2:gobber2_rod_nether')
	e.smithing(Item.of('gobber2:gobber2_shovel'), Item.of('minecraft:netherite_shovel').ignoreNBT(), 'gobber2:gobber2_ingot')
	e.smithing(Item.of('gobber2:gobber2_excavator'), Item.of('minecraft:netherite_shovel').ignoreNBT(), 'gobber2:gobber2_rod')
	e.smithing(Item.of('gobber2:gobber2_hoe_end'), Item.of('minecraft:netherite_hoe').ignoreNBT(), 'gobber2:gobber2_ingot_end')
	e.smithing(Item.of('gobber2:gobber2_hoe_nether'), Item.of('minecraft:netherite_hoe').ignoreNBT(), 'gobber2:gobber2_ingot_nether')
	e.smithing(Item.of('gobber2:gobber2_hoe'), Item.of('minecraft:netherite_hoe').ignoreNBT(), 'gobber2:gobber2_ingot')
	e.smithing(Item.of('gobber2:gobber2_sword_end'), Item.of('minecraft:netherite_sword').ignoreNBT(), 'gobber2:gobber2_ingot_end')
	e.smithing(Item.of('gobber2:gobber2_sword_nether'), Item.of('minecraft:netherite_sword').ignoreNBT(), 'gobber2:gobber2_ingot_nether')
	e.smithing(Item.of('gobber2:gobber2_sword'), Item.of('minecraft:netherite_sword').ignoreNBT(), 'gobber2:gobber2_ingot')

	//Immersive Engineering

	e.smithing(Item.of('immersiveengineering:axe_steel'), Item.of('minecraft:iron_axe').ignoreNBT(), '#forge:ingots/steel')
	e.smithing(Item.of('immersiveengineering:shovel_steel'), Item.of('minecraft:iron_shovel').ignoreNBT(), '#forge:ingots/steel')
	e.smithing(Item.of('immersiveengineering:hoe_steel'), Item.of('minecraft:iron_hoe').ignoreNBT(), '#forge:ingots/steel')
	e.smithing(Item.of('immersiveengineering:sword_steel'), Item.of('minecraft:iron_sword').ignoreNBT(), '#forge:ingots/steel')
	e.smithing(Item.of('immersiveengineering:armor_steel_chest'), Item.of('minecraft:iron_chestplate').ignoreNBT(), '#forge:plates/steel')
	e.smithing(Item.of('immersiveengineering:armor_faraday_chest'), Item.of('minecraft:leather_chestplate').ignoreNBT(), '#forge:plates/aluminum')
	e.smithing(Item.of('immersiveengineering:armor_steel_head'), Item.of('minecraft:iron_helmet').ignoreNBT(), '#forge:plates/steel')
	e.smithing(Item.of('immersiveengineering:armor_faraday_head'), Item.of('minecraft:leather_helmet').ignoreNBT(), '#forge:plates/aluminum')
	e.smithing(Item.of('immersiveengineering:armor_steel_legs'), Item.of('minecraft:iron_leggings').ignoreNBT(), '#forge:plates/steel')
	e.smithing(Item.of('immersiveengineering:armor_faraday_legs'), Item.of('minecraft:leather_leggings').ignoreNBT(), '#forge:plates/aluminum')
	e.smithing(Item.of('immersiveengineering:armor_steel_feet'), Item.of('minecraft:iron_boots').ignoreNBT(), '#forge:plates/steel')
	e.smithing(Item.of('immersiveengineering:armor_faraday_feet'), Item.of('minecraft:leather_boots').ignoreNBT(), '#forge:plates/aluminum')
	e.smithing(Item.of('immersiveengineering:shield'), 'minecraft:shield', '#forge:treated_wood')
	e.smithing(Item.of('immersiveengineering:sword_steel'), Item.of('minecraft:iron_sword').ignoreNBT(), '#forge:ingots/steel')
	e.smithing(Item.of('immersiveengineering:pickaxe_steel'), Item.of('minecraft:iron_pickaxe').ignoreNBT(), '#forge:ingots/steel')

	//Ice and Fire Pickaxes
	e.smithing(Item.of('iceandfire:dragonsteel_lightning_pickaxe'), Item.of('minecraft:netherite_pickaxe').ignoreNBT(), '#forge:ingots/dragonsteel_lightning')
	e.smithing(Item.of('iceandfire:dragonsteel_ice_pickaxe'), Item.of('minecraft:netherite_pickaxe').ignoreNBT(), '#forge:ingots/dragonsteel_ice')
	e.smithing(Item.of('iceandfire:dragonsteel_fire_pickaxe'), Item.of('minecraft:netherite_pickaxe').ignoreNBT(), '#forge:ingots/dragonsteel_fire')
	e.smithing(Item.of('iceandfire:myrmex_jungle_pickaxe'), Item.of('minecraft:iron_pickaxe').ignoreNBT(), 'iceandfire:myrmex_jungle_chitin')
	e.smithing(Item.of('iceandfire:myrmex_desert_pickaxe'), Item.of('minecraft:iron_pickaxe').ignoreNBT(), 'iceandfire:myrmex_desert_chitin')
	e.smithing(Item.of('iceandfire:dragonbone_pickaxe'), Item.of('minecraft:netherite_pickaxe').ignoreNBT(), '#forge:bones/dragon')

	//Ice and Fire Shovel
	e.smithing(Item.of('iceandfire:dragonsteel_lightning_shovel'), Item.of('minecraft:netherite_shovel').ignoreNBT(), '#forge:ingots/dragonsteel_lightning')
	e.smithing(Item.of('iceandfire:dragonsteel_ice_shovel'), Item.of('minecraft:netherite_shovel').ignoreNBT(), '#forge:ingots/dragonsteel_ice')
	e.smithing(Item.of('iceandfire:dragonsteel_fire_shovel'), Item.of('minecraft:netherite_shovel').ignoreNBT(), '#forge:ingots/dragonsteel_fire')
	e.smithing(Item.of('iceandfire:myrmex_jungle_shovel'), Item.of('minecraft:iron_shovel').ignoreNBT(), 'iceandfire:myrmex_jungle_chitin')
	e.smithing(Item.of('iceandfire:myrmex_desert_shovel'), Item.of('minecraft:iron_shovel').ignoreNBT(), 'iceandfire:myrmex_desert_chitin')
	e.smithing(Item.of('iceandfire:dragonbone_shovel'), Item.of('minecraft:netherite_shovel').ignoreNBT(), '#forge:bones/dragon')

	//Ice and Fire Hoe
	e.smithing(Item.of('iceandfire:dragonsteel_lightning_hoe'), Item.of('minecraft:netherite_hoe').ignoreNBT(), '#forge:ingots/dragonsteel_lightning')
	e.smithing(Item.of('iceandfire:dragonsteel_ice_hoe'), Item.of('minecraft:netherite_hoe').ignoreNBT(), '#forge:ingots/dragonsteel_ice')
	e.smithing(Item.of('iceandfire:dragonsteel_fire_hoe'), Item.of('minecraft:netherite_hoe').ignoreNBT(), '#forge:ingots/dragonsteel_fire')
	e.smithing(Item.of('iceandfire:myrmex_jungle_hoe'), Item.of('minecraft:iron_hoe').ignoreNBT(), 'iceandfire:myrmex_jungle_chitin')
	e.smithing(Item.of('iceandfire:myrmex_desert_hoe'), Item.of('minecraft:iron_hoe').ignoreNBT(), 'iceandfire:myrmex_desert_chitin')
	e.smithing(Item.of('iceandfire:dragonbone_hoe'), Item.of('minecraft:netherite_hoe').ignoreNBT(), '#forge:bones/dragon')

	//Ice and Fire Axe
	e.smithing(Item.of('iceandfire:dragonsteel_lightning_axe'), Item.of('minecraft:netherite_axe').ignoreNBT(), '#forge:ingots/dragonsteel_lightning')
	e.smithing(Item.of('iceandfire:dragonsteel_ice_axe'), Item.of('minecraft:netherite_axe').ignoreNBT(), '#forge:ingots/dragonsteel_ice')
	e.smithing(Item.of('iceandfire:dragonsteel_fire_axe'), Item.of('minecraft:netherite_axe').ignoreNBT(), '#forge:ingots/dragonsteel_fire')
	e.smithing(Item.of('iceandfire:myrmex_jungle_axe'), Item.of('minecraft:iron_axe').ignoreNBT(), 'iceandfire:myrmex_jungle_chitin')
	e.smithing(Item.of('iceandfire:myrmex_desert_axe'), Item.of('minecraft:iron_axe').ignoreNBT(), 'iceandfire:myrmex_desert_chitin')
	e.smithing(Item.of('iceandfire:dragonbone_axe'), Item.of('minecraft:netherite_axe').ignoreNBT(), '#forge:bones/dragon')

	//Ice and Fire Sword
	e.smithing(Item.of('iceandfire:dragonsteel_lightning_sword'), Item.of('minecraft:netherite_sword').ignoreNBT(), '#forge:ingots/dragonsteel_lightning')
	e.smithing(Item.of('iceandfire:dragonsteel_ice_sword'), Item.of('minecraft:netherite_sword').ignoreNBT(), '#forge:ingots/dragonsteel_ice')
	e.smithing(Item.of('iceandfire:dragonsteel_fire_sword'), Item.of('minecraft:netherite_sword').ignoreNBT(), '#forge:ingots/dragonsteel_fire')
	e.smithing(Item.of('iceandfire:myrmex_jungle_sword'), Item.of('minecraft:iron_sword').ignoreNBT(), 'iceandfire:myrmex_jungle_chitin')
	e.smithing(Item.of('iceandfire:myrmex_desert_sword'), Item.of('minecraft:iron_sword').ignoreNBT(), 'iceandfire:myrmex_desert_chitin')
	e.smithing(Item.of('iceandfire:dragonbone_sword'), Item.of('minecraft:netherite_sword').ignoreNBT(), '#forge:bones/dragon')
	e.smithing(Item.of('iceandfire:dragonbone_sword_lightning'), 'iceandfire:dragonbone_sword', 'iceandfire:lightning_dragon_blood')
	e.smithing(Item.of('iceandfire:dragonbone_sword_ice'), 'iceandfire:dragonbone_sword', 'iceandfire:ice_dragon_blood')
	e.smithing(Item.of('iceandfire:dragonbone_sword_fire'), 'iceandfire:dragonbone_sword', 'iceandfire:fire_dragon_blood')
	e.smithing(Item.of('iceandfire:hippogryph_sword'), Item.of('minecraft:netherite_sword').ignoreNBT(), 'iceandfire:hippogryph_talon')
	e.smithing(Item.of('iceandfire:dragonbone_bow'), '#forge:string', '#forge:bones/wither')

	//Ice and Fire Armor
	e.smithing(Item.of('iceandfire:dragonsteel_lightning_boots'), Item.of('minecraft:netherite_boots').ignoreNBT(), '#forge:ingots/dragonsteel_lightning')
	e.smithing(Item.of('iceandfire:dragonsteel_ice_boots'), Item.of('minecraft:netherite_boots').ignoreNBT(), '#forge:ingots/dragonsteel_ice')
	e.smithing(Item.of('iceandfire:dragonsteel_fire_boots'), Item.of('minecraft:netherite_boots').ignoreNBT(), '#forge:ingots/dragonsteel_fire')
	e.smithing(Item.of('iceandfire:myrmex_jungle_boots'), Item.of('minecraft:iron_boots').ignoreNBT(), 'iceandfire:myrmex_jungle_chitin')
	e.smithing(Item.of('iceandfire:myrmex_desert_boots'), Item.of('minecraft:iron_boots').ignoreNBT(), 'iceandfire:myrmex_desert_chitin')
	e.smithing(Item.of('iceandfire:dragonsteel_lightning_leggings'), Item.of('minecraft:netherite_leggings').ignoreNBT(), '#forge:ingots/dragonsteel_lightning')
	e.smithing(Item.of('iceandfire:dragonsteel_ice_leggings'), Item.of('minecraft:netherite_leggings').ignoreNBT(), '#forge:ingots/dragonsteel_ice')
	e.smithing(Item.of('iceandfire:dragonsteel_fire_leggings'), Item.of('minecraft:netherite_leggings').ignoreNBT(), '#forge:ingots/dragonsteel_fire')
	e.smithing(Item.of('iceandfire:myrmex_jungle_leggings'), Item.of('minecraft:iron_leggings').ignoreNBT(), 'iceandfire:myrmex_jungle_chitin')
	e.smithing(Item.of('iceandfire:myrmex_desert_leggings'), Item.of('minecraft:iron_leggings').ignoreNBT(), 'iceandfire:myrmex_desert_chitin')
	e.smithing(Item.of('iceandfire:dragonsteel_lightning_chestplate'), Item.of('minecraft:netherite_chestplate').ignoreNBT(), '#forge:ingots/dragonsteel_lightning')
	e.smithing(Item.of('iceandfire:dragonsteel_ice_chestplate'), Item.of('minecraft:netherite_chestplate').ignoreNBT(), '#forge:ingots/dragonsteel_ice')
	e.smithing(Item.of('iceandfire:dragonsteel_fire_chestplate'), Item.of('minecraft:netherite_chestplate').ignoreNBT(), '#forge:ingots/dragonsteel_fire')
	e.smithing(Item.of('iceandfire:myrmex_jungle_chestplate'), Item.of('minecraft:iron_chestplate').ignoreNBT(), 'iceandfire:myrmex_jungle_chitin')
	e.smithing(Item.of('iceandfire:myrmex_desert_chestplate'), Item.of('minecraft:iron_chestplate').ignoreNBT(), 'iceandfire:myrmex_desert_chitin')
	e.smithing(Item.of('iceandfire:dragonsteel_lightning_helmet'), Item.of('minecraft:netherite_helmet').ignoreNBT(), '#forge:ingots/dragonsteel_lightning')
	e.smithing(Item.of('iceandfire:dragonsteel_ice_helmet'), Item.of('minecraft:netherite_helmet').ignoreNBT(), '#forge:ingots/dragonsteel_ice')
	e.smithing(Item.of('iceandfire:dragonsteel_fire_helmet'), Item.of('minecraft:netherite_helmet').ignoreNBT(), '#forge:ingots/dragonsteel_fire')
	e.smithing(Item.of('iceandfire:myrmex_jungle_helmet'), Item.of('minecraft:iron_helmet').ignoreNBT(), 'iceandfire:myrmex_jungle_chitin')
	e.smithing(Item.of('iceandfire:myrmex_desert_helmet'), Item.of('minecraft:iron_helmet').ignoreNBT(), 'iceandfire:myrmex_desert_chitin')

	//Minecraft

	e.smithing(Item.of('minecraft:stone_axe'), Item.of('minecraft:wooden_axe').ignoreNBT(), '#forge:stone')
	e.smithing(Item.of('minecraft:stone_pickaxe'), Item.of('minecraft:wooden_pickaxe').ignoreNBT(), '#forge:stone')
	e.smithing(Item.of('minecraft:stone_shovel'), Item.of('minecraft:wooden_shovel').ignoreNBT(), '#forge:stone')
	e.smithing(Item.of('minecraft:stone_sword'), Item.of('minecraft:wooden_sword').ignoreNBT(), '#forge:stone')
	e.smithing(Item.of('minecraft:stone_hoe'), Item.of('minecraft:wooden_hoe').ignoreNBT(), '#forge:stone')
	e.smithing(Item.of('minecraft:iron_axe'), Item.of('minecraft:stone_axe').ignoreNBT(), '#forge:ingots/iron')
	e.smithing(Item.of('minecraft:iron_pickaxe'), Item.of('minecraft:stone_pickaxe').ignoreNBT(), '#forge:ingots/iron')
	e.smithing(Item.of('minecraft:iron_shovel'), Item.of('minecraft:stone_shovel').ignoreNBT(), '#forge:ingots/iron')
	e.smithing(Item.of('minecraft:iron_sword'), Item.of('minecraft:stone_sword').ignoreNBT(), '#forge:ingots/iron')
	e.smithing(Item.of('minecraft:iron_hoe'), Item.of('minecraft:stone_hoe').ignoreNBT(), '#forge:ingots/iron')
	e.smithing(Item.of('minecraft:golden_axe'), Item.of('minecraft:iron_axe').ignoreNBT(), '#forge:ingots/gold')
	e.smithing(Item.of('minecraft:golden_pickaxe'), Item.of('minecraft:iron_pickaxe').ignoreNBT(), '#forge:ingots/gold')
	e.smithing(Item.of('minecraft:golden_shovel'), Item.of('minecraft:iron_shovel').ignoreNBT(), '#forge:ingots/gold')
	e.smithing(Item.of('minecraft:golden_sword'), Item.of('minecraft:iron_sword').ignoreNBT(), '#forge:ingots/gold')
	e.smithing(Item.of('minecraft:golden_hoe'), Item.of('minecraft:iron_hoe').ignoreNBT(), '#forge:ingots/gold')
	e.smithing(Item.of('minecraft:diamond_axe'), Item.of('minecraft:golden_axe').ignoreNBT(), '#forge:gems/diamond')
	e.smithing(Item.of('minecraft:diamond_pickaxe'), Item.of('minecraft:golden_pickaxe').ignoreNBT(), '#forge:gems/diamond')
	e.smithing(Item.of('minecraft:diamond_shovel'), Item.of('minecraft:golden_shovel').ignoreNBT(), '#forge:gems/diamond')
	e.smithing(Item.of('minecraft:diamond_sword'), Item.of('minecraft:golden_sword').ignoreNBT(), '#forge:gems/diamond')
	e.smithing(Item.of('minecraft:diamond_hoe'), Item.of('minecraft:golden_hoe').ignoreNBT(), '#forge:gems/diamond')
	//Minecraft Armor
	e.smithing(Item.of('minecraft:diamond_helmet'), Item.of('minecraft:golden_helmet').ignoreNBT(), '#forge:gems/diamond')
	e.smithing(Item.of('minecraft:diamond_chestplate'), Item.of('minecraft:golden_chestplate').ignoreNBT(), '#forge:gems/diamond')
	e.smithing(Item.of('minecraft:diamond_leggings'), Item.of('minecraft:golden_leggings').ignoreNBT(), '#forge:gems/diamond')
	e.smithing(Item.of('minecraft:diamond_boots'), Item.of('minecraft:golden_boots').ignoreNBT(), '#forge:gems/diamond')
	e.smithing(Item.of('minecraft:golden_helmet'), Item.of('minecraft:iron_helmet').ignoreNBT(), '#forge:ingots/gold')
	e.smithing(Item.of('minecraft:golden_chestplate'), Item.of('minecraft:iron_chestplate').ignoreNBT(), '#forge:ingots/gold')
	e.smithing(Item.of('minecraft:golden_leggings'), Item.of('minecraft:iron_leggings').ignoreNBT(), '#forge:ingots/gold')
	e.smithing(Item.of('minecraft:golden_boots'), Item.of('minecraft:iron_boots').ignoreNBT(), '#forge:ingots/gold')
	e.smithing(Item.of('minecraft:iron_helmet'), Item.of('minecraft:leather_helmet').ignoreNBT(), '#forge:ingots/iron')
	e.smithing(Item.of('minecraft:iron_chestplate'), Item.of('minecraft:leather_chestplate').ignoreNBT(), '#forge:ingots/iron')
	e.smithing(Item.of('minecraft:iron_leggings'), Item.of('minecraft:leather_leggings').ignoreNBT(), '#forge:ingots/iron')
	e.smithing(Item.of('minecraft:iron_boots'), Item.of('minecraft:leather_boots').ignoreNBT(), '#forge:ingots/iron')
	//Minecraft Misc
	e.smithing(Item.of('minecraft:shield'), '#minecraft:planks', '#forge:ingots/iron')
	e.smithing(Item.of('minecraft:compass'), '#forge:plates/iron', 'extendedcrafting:redstone_ingot')
	e.smithing(Item.of('minecraft:bow'), '#forge:rods/wooden', '#forge:string')
	e.smithing(Item.of('minecraft:crossbow'), 'minecraft:tripwire_hook', '#forge:ingots/iron')

	//Mystical Agriculture Furnace

	e.smithing(Item.of('mysticalagriculture:inferium_furnace'), '#forge:furnace', 'mysticalagriculture:inferium_block')
	e.smithing(Item.of('mysticalagriculture:prudentium_furnace'), 'mysticalagriculture:inferium_furnace', 'mysticalagriculture:prudentium_block')
	e.smithing(Item.of('mysticalagriculture:tertium_furnace'), 'mysticalagriculture:prudentium_furnace', 'mysticalagriculture:tertium_block')
	e.smithing(Item.of('mysticalagriculture:imperium_furnace'), 'mysticalagriculture:tertium_furnace', 'mysticalagriculture:imperium_block')
	e.smithing(Item.of('mysticalagriculture:supremium_furnace'), 'mysticalagriculture:imperium_furnace', 'mysticalagriculture:supremium_block')

	//Mystical Agriculture helmet

	e.smithing(Item.of('mysticalagriculture:inferium_helmet'), Item.of('minecraft:diamond_helmet').ignoreNBT(), 'mysticalagriculture:inferium_gemstone')
	e.smithing(Item.of('mysticalagriculture:prudentium_helmet'), Item.of('mysticalagriculture:inferium_helmet').ignoreNBT(), 'mysticalagriculture:prudentium_gemstone')
	e.smithing(Item.of('mysticalagriculture:tertium_helmet'), Item.of('mysticalagriculture:prudentium_helmet').ignoreNBT(), 'mysticalagriculture:tertium_gemstone')
	e.smithing(Item.of('mysticalagriculture:imperium_helmet'), Item.of('mysticalagriculture:tertium_helmet').ignoreNBT(), 'mysticalagriculture:imperium_gemstone')
	e.smithing(Item.of('mysticalagriculture:supremium_helmet'), Item.of('mysticalagriculture:imperium_helmet').ignoreNBT(), 'mysticalagriculture:supremium_gemstone')

	//Mystical Agriculture Chestplates

	e.smithing(Item.of('mysticalagriculture:inferium_chestplate'), Item.of('minecraft:diamond_chestplate').ignoreNBT(), 'mysticalagriculture:inferium_gemstone')
	e.smithing(Item.of('mysticalagriculture:supremium_chestplate'), Item.of('mysticalagriculture:imperium_chestplate').ignoreNBT(), 'mysticalagriculture:supremium_gemstone')
	e.smithing(Item.of('mysticalagriculture:imperium_chestplate'), Item.of('mysticalagriculture:tertium_chestplate').ignoreNBT(), 'mysticalagriculture:imperium_gemstone')
	e.smithing(Item.of('mysticalagriculture:tertium_chestplate'), Item.of('mysticalagriculture:prudentium_chestplate').ignoreNBT(), 'mysticalagriculture:tertium_gemstone')
	e.smithing(Item.of('mysticalagriculture:prudentium_chestplate'), Item.of('mysticalagriculture:inferium_chestplate').ignoreNBT(), 'mysticalagriculture:prudentium_gemstone')

	//Mystical Agriculture Leggings

	e.smithing(Item.of('mysticalagriculture:inferium_leggings'), Item.of('minecraft:diamond_leggings').ignoreNBT(), 'mysticalagriculture:inferium_gemstone')
	e.smithing(Item.of('mysticalagriculture:prudentium_leggings'), Item.of('mysticalagriculture:inferium_leggings').ignoreNBT(), 'mysticalagriculture:prudentium_gemstone')
	e.smithing(Item.of('mysticalagriculture:tertium_leggings'), Item.of('mysticalagriculture:prudentium_leggings').ignoreNBT(), 'mysticalagriculture:tertium_gemstone')
	e.smithing(Item.of('mysticalagriculture:imperium_leggings'), Item.of('mysticalagriculture:tertium_leggings').ignoreNBT(), 'mysticalagriculture:imperium_gemstone')
	e.smithing(Item.of('mysticalagriculture:supremium_leggings'), Item.of('mysticalagriculture:imperium_leggings').ignoreNBT(), 'mysticalagriculture:supremium_gemstone')

	//Mystical Agriculture Boots

	e.smithing(Item.of('mysticalagriculture:inferium_boots'), Item.of('minecraft:diamond_boots').ignoreNBT(), 'mysticalagriculture:inferium_gemstone')
	e.smithing(Item.of('mysticalagriculture:prudentium_boots'), Item.of('mysticalagriculture:inferium_boots').ignoreNBT(), 'mysticalagriculture:prudentium_gemstone')
	e.smithing(Item.of('mysticalagriculture:tertium_boots'), Item.of('mysticalagriculture:prudentium_boots').ignoreNBT(), 'mysticalagriculture:tertium_gemstone')
	e.smithing(Item.of('mysticalagriculture:imperium_boots'), Item.of('mysticalagriculture:tertium_boots').ignoreNBT(), 'mysticalagriculture:imperium_gemstone')
	e.smithing(Item.of('mysticalagriculture:supremium_boots'), Item.of('mysticalagriculture:imperium_boots').ignoreNBT(), 'mysticalagriculture:supremium_gemstone')

	//Mystical Agriculture Tools

	e.smithing(Item.of('mysticalagriculture:inferium_axe'), Item.of('minecraft:diamond_axe').ignoreNBT(), 'mysticalagriculture:inferium_gemstone')
	e.smithing(Item.of('mysticalagriculture:inferium_pickaxe'), Item.of('minecraft:diamond_pickaxe').ignoreNBT(), 'mysticalagriculture:inferium_gemstone')
	e.smithing(Item.of('mysticalagriculture:prudentium_pickaxe'), Item.of('mysticalagriculture:inferium_pickaxe').ignoreNBT(), 'mysticalagriculture:prudentium_gemstone')
	e.smithing(Item.of('mysticalagriculture:tertium_pickaxe'), Item.of('mysticalagriculture:prudentium_pickaxe').ignoreNBT(), 'mysticalagriculture:tertium_gemstone')
	e.smithing(Item.of('mysticalagriculture:imperium_pickaxe'), Item.of('mysticalagriculture:tertium_pickaxe').ignoreNBT(), 'mysticalagriculture:imperium_gemstone')
	e.smithing(Item.of('mysticalagriculture:supremium_pickaxe'), Item.of('mysticalagriculture:imperium_pickaxe').ignoreNBT(), 'mysticalagriculture:supremium_gemstone')
	e.smithing(Item.of('mysticalagriculture:inferium_shovel'), Item.of('minecraft:diamond_shovel').ignoreNBT(), 'mysticalagriculture:inferium_gemstone')
	e.smithing(Item.of('mysticalagriculture:prudentium_shovel'), Item.of('mysticalagriculture:inferium_shovel').ignoreNBT(), 'mysticalagriculture:prudentium_gemstone')
	e.smithing(Item.of('mysticalagriculture:inferium_hoe'), Item.of('minecraft:diamond_hoe').ignoreNBT(), 'mysticalagriculture:inferium_gemstone')
	e.smithing(Item.of('mysticalagriculture:inferium_sword'), Item.of('minecraft:diamond_sword').ignoreNBT(), 'mysticalagriculture:inferium_gemstone')

	//Modular Routers
	e.smithing(Item.of('modularrouters:breaker_module', '{modularrouters:{ModuleFilter:{},Direction:"NONE"}}'), 'modularrouters:blank_module', '#forge:tools/pickaxe')
	e.smithing(Item.of('modularrouters:extruder_module_1', '{modularrouters:{ModuleFilter:{},Direction:"NONE"}}'), 'modularrouters:breaker_module', 'modularrouters:blank_module')

	//Nature's Aura

	e.smithing(Item.of('naturesaura:infused_iron_axe'), Item.of('minecraft:iron_axe').ignoreNBT(), 'naturesaura:infused_iron')
	e.smithing(Item.of('naturesaura:sky_axe'), Item.of('minecraft:diamond_axe').ignoreNBT(), 'naturesaura:sky_ingot')
	e.smithing(Item.of('naturesaura:infused_iron_sword'), Item.of('minecraft:iron_sword').ignoreNBT(), 'naturesaura:infused_iron')
	e.smithing(Item.of('naturesaura:sky_sword'), Item.of('minecraft:diamond_sword').ignoreNBT(), 'naturesaura:sky_ingot')
	e.smithing(Item.of('naturesaura:infused_iron_hoe'), Item.of('minecraft:iron_hoe').ignoreNBT(), 'naturesaura:infused_iron')
	e.smithing(Item.of('naturesaura:sky_hoe'), Item.of('minecraft:diamond_hoe').ignoreNBT(), 'naturesaura:sky_ingot')
	e.smithing(Item.of('naturesaura:infused_iron_chest'), Item.of('minecraft:iron_chestplate').ignoreNBT(), 'naturesaura:infused_iron')
	e.smithing(Item.of('naturesaura:sky_chest'), Item.of('minecraft:diamond_chestplate').ignoreNBT(), 'naturesaura:sky_ingot')
	e.smithing(Item.of('naturesaura:infused_iron_helmet'), Item.of('minecraft:iron_helmet').ignoreNBT(), 'naturesaura:infused_iron')
	e.smithing(Item.of('naturesaura:sky_helmet'), Item.of('minecraft:diamond_helmet').ignoreNBT(), 'naturesaura:sky_ingot')
	e.smithing(Item.of('naturesaura:infused_iron_pants'), Item.of('minecraft:iron_leggings').ignoreNBT(), 'naturesaura:infused_iron')
	e.smithing(Item.of('naturesaura:sky_pants'), Item.of('minecraft:diamond_leggings').ignoreNBT(), 'naturesaura:sky_ingot')
	e.smithing(Item.of('naturesaura:infused_iron_shoes'), Item.of('minecraft:iron_boots').ignoreNBT(), 'naturesaura:infused_iron')
	e.smithing(Item.of('naturesaura:sky_shoes'), Item.of('minecraft:diamond_boots').ignoreNBT(), 'naturesaura:sky_ingot')
	e.smithing(Item.of('naturesaura:infused_iron_shovel'), Item.of('minecraft:iron_shovel').ignoreNBT(), 'naturesaura:infused_iron')
	e.smithing(Item.of('naturesaura:sky_shovel'), Item.of('minecraft:diamond_shovel').ignoreNBT(), 'naturesaura:sky_ingot')
	e.smithing(Item.of('naturesaura:infused_iron_pickaxe'), Item.of('minecraft:iron_pickaxe').ignoreNBT(), 'naturesaura:infused_iron')
	e.smithing(Item.of('naturesaura:sky_pickaxe'), Item.of('minecraft:diamond_pickaxe').ignoreNBT(), 'naturesaura:sky_ingot')

	//Nature's Compass

	e.smithing(Item.of('naturescompass:naturescompass'), 'minecraft:compass', '#minecraft:saplings')

	//Occultism

	e.smithing(Item.of('occultism:iesnium_pickaxe'), Item.of('minecraft:diamond_pickaxe').ignoreNBT(), '#forge:ingots/iesnium')

	//Pneumaticcraft
	e.smithing(Item.of('pneumaticcraft:compressed_iron_boots'), Item.of('minecraft:iron_boots').ignoreNBT(), 'kubejs:compressed_iron_plate')
	e.smithing(Item.of('pneumaticcraft:compressed_iron_leggings'), Item.of('minecraft:iron_leggings').ignoreNBT(), 'kubejs:compressed_iron_plate')
	e.smithing(Item.of('pneumaticcraft:compressed_iron_helmet'), Item.of('minecraft:iron_helmet').ignoreNBT(), 'kubejs:compressed_iron_plate')
	e.smithing(Item.of('pneumaticcraft:compressed_iron_chestplate'), Item.of('minecraft:iron_chestplate').ignoreNBT(), 'kubejs:compressed_iron_plate')

	//PSI
	e.smithing(Item.of('psi:psimetal_pickaxe'), Item.of('minecraft:diamond_pickaxe').ignoreNBT(), '#forge:gems/psigem')
	e.smithing(Item.of('psipherals:psimetal_bow'), '#forge:string', '#forge:gems/psigem')
	e.smithing(Item.of('psi:psimetal_exosuit_boots'), Item.of('minecraft:diamond_boots').ignoreNBT(), '#forge:gems/psigem')
	e.smithing(Item.of('psi:psimetal_exosuit_leggings'), Item.of('minecraft:diamond_leggings').ignoreNBT(), '#forge:gems/psigem')
	e.smithing(Item.of('psi:psimetal_exosuit_helmet'), Item.of('minecraft:diamond_helmet').ignoreNBT(), '#forge:gems/psigem')
	e.smithing(Item.of('psi:psimetal_exosuit_chestplate'), Item.of('minecraft:diamond_chestplate').ignoreNBT(), '#forge:gems/psigem')
	e.smithing(Item.of('psi:psimetal_sword'), Item.of('minecraft:diamond_sword').ignoreNBT(), '#forge:gems/psigem')
	e.smithing(Item.of('psi:psimetal_shovel'), Item.of('minecraft:diamond_shovel').ignoreNBT(), '#forge:gems/psigem')
	e.smithing(Item.of('psi:psimetal_axe'), Item.of('minecraft:diamond_axe').ignoreNBT(), '#forge:gems/psigem')

	//Twilight Forest

	e.smithing(Item.of('twilightforest:ironwood_hoe'), Item.of('minecraft:iron_hoe').ignoreNBT(), '#forge:ingots/ironwood')
	e.smithing(Item.of('twilightforest:steeleaf_hoe'), Item.of('minecraft:diamond_hoe').ignoreNBT(), '#forge:ingots/steeleaf')
	e.smithing(Item.of('twilightforest:ironwood_hoe'), Item.of('minecraft:iron_hoe').ignoreNBT(), '#forge:ingots/ironwood')
	e.smithing(Item.of('twilightforest:steeleaf_hoe'), Item.of('minecraft:diamond_hoe').ignoreNBT(), '#forge:ingots/steeleaf')
	e.smithing(Item.of('twilightforest:ironwood_sword'), Item.of('minecraft:iron_sword').ignoreNBT(), '#forge:ingots/ironwood')
	e.smithing(Item.of('twilightforest:steeleaf_sword'), Item.of('minecraft:diamond_sword').ignoreNBT(), '#forge:ingots/steeleaf')
	e.smithing(Item.of('twilightforest:knightmetal_sword'), Item.of('minecraft:diamond_sword').ignoreNBT(), '#forge:ingots/knightmetal')
	e.smithing(Item.of('twilightforest:fiery_sword'), Item.of('minecraft:netherite_sword').ignoreNBT(), '#forge:ingots/fiery')
	e.smithing(Item.of('twilightforest:ironwood_chestplate'), Item.of('minecraft:iron_chestplate').ignoreNBT(), '#forge:ingots/ironwood')
	e.smithing(Item.of('twilightforest:steeleaf_chestplate'), Item.of('minecraft:diamond_chestplate').ignoreNBT(), '#forge:ingots/steeleaf')
	e.smithing(Item.of('twilightforest:fiery_chestplate'), Item.of('minecraft:netherite_chestplate').ignoreNBT(), '#forge:ingots/fiery')
	e.smithing(Item.of('twilightforest:knightmetal_chestplate'), Item.of('minecraft:netherite_chestplate').ignoreNBT(), '#forge:ingots/knightmetal')
	e.smithing(Item.of('twilightforest:ironwood_helmet'), Item.of('minecraft:iron_helmet').ignoreNBT(), '#forge:ingots/ironwood')
	e.smithing(Item.of('twilightforest:steeleaf_helmet'), Item.of('minecraft:diamond_helmet').ignoreNBT(), '#forge:ingots/steeleaf')
	e.smithing(Item.of('twilightforest:fiery_helmet'), Item.of('minecraft:netherite_helmet').ignoreNBT(), '#forge:ingots/fiery')
	e.smithing(Item.of('twilightforest:knightmetal_helmet'), Item.of('minecraft:netherite_helmet').ignoreNBT(), '#forge:ingots/knightmetal')
	e.smithing(Item.of('twilightforest:ironwood_leggings'), Item.of('minecraft:iron_leggings').ignoreNBT(), '#forge:ingots/ironwood')
	e.smithing(Item.of('twilightforest:steeleaf_leggings'), Item.of('minecraft:diamond_leggings').ignoreNBT(), '#forge:ingots/steeleaf')
	e.smithing(Item.of('twilightforest:fiery_leggings'), Item.of('minecraft:netherite_leggings').ignoreNBT(), '#forge:ingots/fiery')
	e.smithing(Item.of('twilightforest:knightmetal_leggings'), Item.of('minecraft:diamond_leggings').ignoreNBT(), '#forge:ingots/knightmetal')
	e.smithing(Item.of('twilightforest:ironwood_boots'), Item.of('minecraft:iron_boots').ignoreNBT(), '#forge:ingots/ironwood')
	e.smithing(Item.of('twilightforest:steeleaf_boots'), Item.of('minecraft:diamond_boots').ignoreNBT(), '#forge:ingots/steeleaf')
	e.smithing(Item.of('twilightforest:fiery_boots'), Item.of('minecraft:netherite_boots').ignoreNBT(), '#forge:ingots/fiery')
	e.smithing(Item.of('twilightforest:knightmetal_boots'), Item.of('minecraft:diamond_boots').ignoreNBT(), '#forge:ingots/knightmetal')
	e.smithing(Item.of('twilightforest:knightmetal_shield'), Item.of('#twilightforest:towerwood').ignoreNBT(), '#forge:ingots/knightmetal')
	e.smithing(Item.of('twilightforest:ironwood_axe'), Item.of('minecraft:iron_axe').ignoreNBT(), '#forge:ingots/ironwood')
	e.smithing(Item.of('twilightforest:steeleaf_axe'), Item.of('minecraft:diamond_axe').ignoreNBT(), '#forge:ingots/steeleaf')
	e.smithing(Item.of('twilightforest:knightmetal_axe'), Item.of('minecraft:netherite_axe').ignoreNBT(), '#forge:ingots/knightmetal')
	e.smithing(Item.of('twilightforest:ironwood_shovel'), Item.of('minecraft:iron_shovel').ignoreNBT(), '#forge:ingots/ironwood')
	e.smithing(Item.of('twilightforest:steeleaf_shovel'), Item.of('minecraft:diamond_shovel').ignoreNBT(), '#forge:ingots/steeleaf')
	e.smithing(Item.of('twilightforest:giant_pickaxe'), 'twilightforest:giant_cobblestone', 'twilightforest:giant_log')
	e.smithing(Item.of('twilightforest:knightmetal_pickaxe'), Item.of('minecraft:diamond_pickaxe').ignoreNBT(), '#forge:ingots/knightmetal')
	e.smithing(Item.of('twilightforest:steeleaf_pickaxe'), Item.of('minecraft:diamond_pickaxe').ignoreNBT(), '#forge:ingots/steeleaf')
	e.smithing(Item.of('twilightforest:fiery_pickaxe'), Item.of('minecraft:netherite_pickaxe').ignoreNBT(), '#forge:ingots/fiery')
	e.smithing(Item.of('twilightforest:ironwood_pickaxe'), Item.of('minecraft:iron_pickaxe').ignoreNBT(), '#forge:ingots/ironwood')

	//Undergrden

	e.smithing(Item.of('undergarden:cloggrum_pickaxe'), Item.of('minecraft:stone_pickaxe').ignoreNBT(), '#forge:ingots/cloggrum')
	e.smithing(Item.of('undergarden:froststeel_pickaxe'), Item.of('minecraft:iron_pickaxe').ignoreNBT(), '#forge:ingots/froststeel')
	e.smithing(Item.of('undergarden:utheric_pickaxe'), Item.of('minecraft:diamond_pickaxe').ignoreNBT(), '#forge:ingots/utherium')
	e.smithing(Item.of('undergarden:cloggrum_hoe'), Item.of('minecraft:stone_hoe').ignoreNBT(), '#forge:ingots/cloggrum')
	e.smithing(Item.of('undergarden:froststeel_hoe'), Item.of('minecraft:iron_hoe').ignoreNBT(), '#forge:ingots/froststeel')
	e.smithing(Item.of('undergarden:utheric_hoe'), Item.of('minecraft:diamond_hoe').ignoreNBT(), '#forge:ingots/utherium')
	e.smithing(Item.of('undergarden:cloggrum_sword'), Item.of('minecraft:stone_sword').ignoreNBT(), '#forge:ingots/cloggrum')
	e.smithing(Item.of('undergarden:froststeel_sword'), Item.of('minecraft:iron_sword').ignoreNBT(), '#forge:ingots/froststeel')
	e.smithing(Item.of('undergarden:utheric_sword'), Item.of('minecraft:diamond_sword').ignoreNBT(), '#forge:ingots/utherium')
	e.smithing(Item.of('undergarden:cloggrum_chestplate'), Item.of('minecraft:iron_chestplate').ignoreNBT(), '#forge:ingots/cloggrum')
	e.smithing(Item.of('undergarden:froststeel_chestplate'), Item.of('minecraft:iron_chestplate').ignoreNBT(), '#forge:ingots/froststeel')
	e.smithing(Item.of('undergarden:utheric_chestplate'), Item.of('minecraft:netherite_chestplate').ignoreNBT(), '#forge:ingots/utherium')
	e.smithing(Item.of('undergarden:masticated_chestplate'), Item.of('minecraft:iron_chestplate').ignoreNBT(), 'undergarden:masticator_scales')
	e.smithing(Item.of('undergarden:cloggrum_helmet'), Item.of('minecraft:iron_helmet').ignoreNBT(), '#forge:ingots/cloggrum')
	e.smithing(Item.of('undergarden:froststeel_helmet'), Item.of('minecraft:iron_helmet').ignoreNBT(), '#forge:ingots/froststeel')
	e.smithing(Item.of('undergarden:utheric_helmet'), Item.of('minecraft:netherite_helmet').ignoreNBT(), '#forge:ingots/utherium')
	e.smithing(Item.of('undergarden:cloggrum_leggings'), Item.of('minecraft:iron_leggings').ignoreNBT(), '#forge:ingots/cloggrum')
	e.smithing(Item.of('undergarden:froststeel_leggings'), Item.of('minecraft:iron_leggings').ignoreNBT(), '#forge:ingots/froststeel')
	e.smithing(Item.of('undergarden:utheric_leggings'), Item.of('minecraft:netherite_leggings').ignoreNBT(), '#forge:ingots/utherium')
	e.smithing(Item.of('undergarden:cloggrum_boots'), Item.of('minecraft:iron_boots').ignoreNBT(), '#forge:ingots/cloggrum')
	e.smithing(Item.of('undergarden:froststeel_boots'), Item.of('minecraft:iron_boots').ignoreNBT(), '#forge:ingots/froststeel')
	e.smithing(Item.of('undergarden:utheric_boots'), Item.of('minecraft:netherite_boots').ignoreNBT(), '#forge:ingots/utherium')
	e.smithing(Item.of('undergarden:cloggrum_shield'), '#minecraft:planks', '#forge:ingots/cloggrum')
	e.smithing(Item.of('undergarden:cloggrum_axe'), Item.of('minecraft:stone_axe').ignoreNBT(), '#forge:ingots/cloggrum')
	e.smithing(Item.of('undergarden:froststeel_axe'), Item.of('minecraft:iron_axe').ignoreNBT(), '#forge:ingots/froststeel')
	e.smithing(Item.of('undergarden:utheric_axe'), Item.of('minecraft:diamond_axe').ignoreNBT(), '#forge:ingots/utherium')
	e.smithing(Item.of('undergarden:cloggrum_shovel'), Item.of('minecraft:stone_shovel').ignoreNBT(), '#forge:ingots/cloggrum')
	e.smithing(Item.of('undergarden:froststeel_shovel'), Item.of('minecraft:iron_shovel').ignoreNBT(), '#forge:ingots/froststeel')
	e.smithing(Item.of('undergarden:utheric_shovel'), Item.of('minecraft:diamond_shovel').ignoreNBT(), '#forge:ingots/utherium')
})
