onEvent('recipes', e => {
	e.recipes.thermal.pulverizer(['emendatusenigmatica:coke_dust'], '#forge:coal_coke').experience(0.2)
	e.recipes.thermal.pulverizer(['9x emendatusenigmatica:coke_dust'], '#forge:storage_blocks/coal_coke').experience(0.2)
	e.recipes.thermal.pulverizer(['emendatusenigmatica:steel_dust'], '#forge:ingots/steel').experience(0.2)
	e.recipes.thermal.pulverizer(['9x emendatusenigmatica:steel_dust'], '#forge:storage_blocks/steel').experience(0.2)
	e.recipes.thermal.pulverizer(['emendatusenigmatica:charcoal_dust'], 'minecraft:charcoal').experience(0.2)
	e.recipes.thermal.pulverizer(['9x emendatusenigmatica:charcoal_dust'], '#forge:storage_blocks/charcoal').experience(0.2)
	e.recipes.thermal.pulverizer(['emendatusenigmatica:coal_dust'], 'minecraft:coal').experience(0.2)
	e.recipes.thermal.pulverizer(['9x emendatusenigmatica:coal_dust'], '#forge:storage_blocks/coal').experience(0.2)
	e.recipes.thermal.pulverizer(['mekanism:dust_netherite'], '#forge:ingots/netherite').experience(0.2)
	e.recipes.thermal.pulverizer(['9x mekanism:dust_netherite'], '#forge:storage_blocks/netherite').experience(0.2)
	e.recipes.thermal.pulverizer(['mekanism:dust_refined_obsidian'], '#forge:ingots/refined_obsidian').experience(0.2)
	e.recipes.thermal.pulverizer(['9x mekanism:dust_refined_obsidian'], '#forge:storage_blocks/refined_obsidian').experience(0.2)

	e.recipes.thermal.pulverizer(['2x emendatusenigmatica:certus_quartz_dust'], '#appliedenergistics2:crystals/certus').experience(0.2)
	e.recipes.thermal.pulverizer(['2x emendatusenigmatica:fluix_dust'], '#appliedenergistics2:crystals/fluix').experience(0.2)
	e.recipes.thermal.pulverizer(['botania:pixie_dust'], 'botania:mana_pearl').experience(0.2)
	e.recipes.thermal.pulverizer(['extendedcrafting:black_iron_slate'], 'extendedcrafting:black_iron_ingot').experience(0.2)
	e.recipes.thermal.pulverizer(['2x minecraft:sugar', Item.of('minecraft:sugar').chance(0.1)], 'minecraft:sugar_cane').experience(0.1)
	e.recipes.thermal.pulverizer(['2x minecraft:netherite_scrap'], '#forge:ores/netherite').experience(0.2)
	e.recipes.thermal.pulverizer(['4x emendatusenigmatica:obsidian_dust'], '#forge:obsidian').experience(0.2)
	e.recipes.thermal.pulverizer(['4x occultism:crushed_end_stone'], '#forge:end_stones').experience(0.2)
	e.recipes.thermal.pulverizer(['minecraft:prismarine_crystals'], '#forge:dusts/prismarine').experience(0.2)
	e.recipes.thermal.pulverizer(['psi:psidust'], '#forge:dusts/redstone').experience(0.2)
	e.recipes.thermal.pulverizer([Item.of('emendatusenigmatica:silicon_gem').chance(0.5), Item.of('emendatusenigmatica:silicon_gem').chance(0.25)], 'create:limesand').experience(0.2)
	e.recipes.thermal.pulverizer(['create:wheat_flour', Item.of('create:wheat_flour').chance(0.25)], '#forge:grain').experience(0.2)
	e.recipes.thermal.pulverizer(['3x minecraft:blaze_powder', Item.of('emendatusenigmatica:sulfur_dust').chance(0.25)], '#forge:rods/blaze').experience(0.2)
})
