onEvent('recipes', e => {
	e.recipes.create.mixing(Fluid.of('immersiveengineering:concrete', 500), ['#forge:clay', '#forge:gravel', '#forge:sand', '#forge:sand', Fluid.of('minecraft:water', 500)])
	e.recipes.create.mixing(Fluid.of('immersiveengineering:concrete', 750), ['#forge:clay', '#forge:gravel', '#forge:slag', '#forge:slag', Fluid.of('minecraft:water', 750)])

	e.recipes.create.mixing('2x appliedenergistics2:quartz_fiber', ['#thermal:glass/hardened', '#forge:dusts/quartz', '#forge:dusts/certus_quartz', 'computercraft:cable']).heated()
	e.recipes.create.mixing('2x appliedenergistics2:quartz_glass', ['thermal:obsidian_glass', '#forge:dusts/certus_quartz', '#forge:dusts/quartz']).heated()
	e.recipes.create.mixing('2x appliedenergistics2:quartz_vibrant_glass', ['#forge:ingots/refined_glowstone', 'appliedenergistics2:quartz_glass']).heated()
	e.recipes.create.mixing('buildinggadgets:construction_block_powder', ['#forge:dusts/lapis', '#forge:sand', '#forge:clay']).heated()
	e.recipes.create.mixing('create:rose_quartz', ['#forge:gems/quartz', '#forge:dusts/redstone']).heated()
	e.recipes.create.mixing('emendatusenigmatica:steel_ingot', ['#forge:charcoal', '#forge:dusts/iron']).heated()
	e.recipes.create.mixing('2x eidolon:pewter_ingot', ['#forge:ingots/iron', '#forge:ingots/lead']).heated()
	e.recipes.create.mixing('extendedcrafting:black_iron_ingot', ['#forge:ingots/compressed_iron', '#forge:dyes/black']).heated()
	e.recipes.create.mixing('extendedcrafting:ender_ingot', ['#forge:ingots/enderium', '#forge:ingots/compressed_iron']).heated()
	e.recipes.create.mixing('extendedcrafting:redstone_ingot', ['#forge:dusts/redstone', '#forge:ingots/iron']).heated()
	e.recipes.create.mixing('fluxnetworks:flux_dust', ['#forge:dusts/redstone', '#forge:dusts/obsidian']).heated()
	e.recipes.create.mixing('forbidden_arcanus:arcane_gold_ingot', ['forbidden_arcanus:mundabitur_dust', '#forge:ingots/gold', '#forge:charcoal', '#forge:charcoal', '#forge:charcoal', 'forbidden_arcanus:mundabitur_dust', '#forge:dusts/arcane_crystal', '#forge:charcoal']).heated()
	e.recipes.create.mixing('4x forbidden_arcanus:corrupti_dust', ['#forge:crops/nether_wart', '#forge:dusts/arcane_crystal', '#forge:nuggets/ender_pearl', '#forge:ingots/obsidian', 'minecraft:blaze_powder']).heated()
	e.recipes.create.mixing('4x forbidden_arcanus:mundabitur_dust', ['minecraft:bone_meal', 'minecraft:phantom_membrane', '#forge:gunpowder', '#forge:dusts/arcane_crystal', '#forge:dusts/redstone', 'minecraft:blaze_powder']).heated()
	e.recipes.create.mixing('forbidden_arcanus:obsidian_ingot', ['#forge:obsidian', 'create:andesite_alloy']).heated()
	e.recipes.create.mixing('greater_eye:greater_eye', ['minecraft:ender_eye', '#forge:gems/diamond', '#forge:gems/emerald']).heated()
	e.recipes.create.mixing('greater_eye:greater_eye_end', ['greater_eye:greater_eye', 'minecraft:chorus_fruit']).heated()
	e.recipes.create.mixing('greater_eye:greater_eye_nether', ['greater_eye:greater_eye', '#forge:gems/quartz']).heated()
	e.recipes.create.mixing('immersiveengineering:concrete', ['minecraft:light_gray_concrete_powder', 'buildinggadgets:construction_block_powder', Fluid.of('minecraft:water', 250)]).heated()
	e.recipes.create.mixing('2x immersiveengineering:insulating_glass', ['#forge:dyes/green', '#forge:dusts/iron', '#forge:sand']).heated()
	e.recipes.create.mixing('4x immersiveengineering:treated_wood_horizontal', ['#minecraft:planks', '#minecraft:planks', '#minecraft:planks', '#minecraft:planks', { fluidTag: 'forge:creosote', amount: 500 }]).heated()
	e.recipes.create.mixing('12x immersivepetroleum:asphalt', ['#forge:gems/bitumen', '#forge:gravel', '#forge:sand', '#forge:sand', Fluid.of('minecraft:water', 500)]).heated()
	e.recipes.create.mixing('2x ironcoals:emerald_coal', ['#forge:gems/emerald', 'ironcoals:diamond_coal']).heated()
	e.recipes.create.mixing('2x ironcoals:diamond_coal', ['#forge:gems/diamond', 'ironcoals:gold_coal']).heated()
	e.recipes.create.mixing('2x ironcoals:gold_coal', ['#forge:ingots/gold', 'ironcoals:iron_coal']).heated()
	e.recipes.create.mixing('2x ironcoals:iron_coal', ['#forge:ingots/iron', 'minecraft:coal']).heated()
	e.recipes.create.mixing('mysticalagriculture:prosperity_gemstone', ['mysticalagriculture:prosperity_shard', 'mysticalagriculture:prosperity_shard', '#forge:gems/diamond']).heated()
	e.recipes.create.mixing('mysticalagriculture:soulium_gemstone', ['mysticalagriculture:soulium_dust', 'mysticalagriculture:soulium_dust', 'mysticalagriculture:prosperity_gemstone']).heated()
	e.recipes.create.mixing('mysticalagriculture:inferium_gemstone', ['mysticalagriculture:inferium_essence', 'mysticalagriculture:inferium_essence', 'mysticalagriculture:prosperity_gemstone']).heated()
	e.recipes.create.mixing('mysticalagriculture:prudentium_gemstone', ['mysticalagriculture:prudentium_essence', 'mysticalagriculture:prudentium_essence', 'mysticalagriculture:prosperity_gemstone']).heated()
	e.recipes.create.mixing('mysticalagradditions:inferium_coal', ['mysticalagriculture:inferium_essence', 'mysticalagriculture:inferium_essence', '#minecraft:coals']).heated()
	e.recipes.create.mixing('mysticalagradditions:prudentium_coal', ['mysticalagriculture:prudentium_essence', 'mysticalagriculture:prudentium_essence', 'mysticalagradditions:inferium_coal']).heated()
	e.recipes.create.mixing('mysticalagriculture:soulium_ingot', ['mysticalagriculture:prosperity_ingot', 'mysticalagriculture:soulium_dust', 'mysticalagriculture:soulium_dust']).heated()
	e.recipes.create.mixing('2x mysticalagriculture:prosperity_ingot', ['forbidden_arcanus:purifying_soap', 'mysticalagriculture:prosperity_shard', 'mysticalagriculture:prosperity_shard']).heated()
	e.recipes.create.mixing('mysticalagriculture:inferium_ingot', ['mysticalagriculture:prosperity_ingot', 'mysticalagriculture:inferium_essence', 'mysticalagriculture:inferium_essence']).heated()
	e.recipes.create.mixing('mysticalagriculture:prudentium_ingot', ['mysticalagriculture:prosperity_ingot', 'mysticalagriculture:prudentium_essence', 'mysticalagriculture:prudentium_essence']).heated()
	e.recipes.create.mixing('mysticalagriculture:inferium_watering_can', ['mysticalagriculture:mystical_fertilizer', 'mysticalagriculture:mystical_fertilizer', 'mysticalagriculture:mystical_fertilizer', 'mysticalagriculture:mystical_fertilizer', 'mysticalagriculture:inferium_ingot', 'mysticalagriculture:inferium_ingot', 'mysticalagriculture:inferium_ingot', 'mysticalagriculture:inferium_ingot', 'mysticalagriculture:watering_can']).heated()
	e.recipes.create.mixing('mysticalagriculture:prudentium_watering_can', ['mysticalagriculture:mystical_fertilizer', 'mysticalagriculture:mystical_fertilizer', 'mysticalagriculture:mystical_fertilizer', 'mysticalagriculture:mystical_fertilizer', 'mysticalagriculture:prudentium_ingot', 'mysticalagriculture:prudentium_ingot', 'mysticalagriculture:prudentium_ingot', 'mysticalagriculture:prudentium_ingot', 'mysticalagriculture:inferium_watering_can']).heated()
	e.recipes.create.mixing('mysticalagradditions:inferium_apple', ['mysticalagriculture:inferium_essence', 'mysticalagriculture:inferium_essence', 'mysticalagriculture:inferium_essence', 'mysticalagriculture:inferium_essence', 'minecraft:golden_apple']).heated()
	e.recipes.create.mixing('mysticalagradditions:prudentium_apple', ['mysticalagriculture:prudentium_essence', 'mysticalagriculture:prudentium_essence', 'mysticalagriculture:prudentium_essence', 'mysticalagriculture:prudentium_essence', 'mysticalagradditions:inferium_apple']).heated()
	e.recipes.create.mixing('mysticalagradditions:tertium_apple', ['mysticalagriculture:tertium_essence', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:tertium_essence', 'mysticalagradditions:prudentium_apple']).heated()
	e.recipes.create.mixing('2x mysticalagriculture:inferium_farmland', ['mysticalagriculture:inferium_essence', '#forge:hoes', '#forge:dirt']).heated()
	e.recipes.create.mixing('2x mysticalagriculture:prudentium_farmland', ['mysticalagriculture:prudentium_essence', '#forge:hoes', 'mysticalagriculture:inferium_farmland']).heated()
	e.recipes.create.mixing('2x mysticalagriculture:tertium_farmland', ['mysticalagriculture:tertium_essence', '#forge:hoes', 'mysticalagriculture:prudentium_farmland']).heated()
	e.recipes.create.mixing('2x mysticalagriculture:prudentium_essence', ['mysticalagriculture:inferium_essence', 'mysticalagriculture:inferium_essence', 'mysticalagriculture:inferium_essence', 'mysticalagriculture:inferium_essence', 'matc:inferium_crystal']).heated()
	e.recipes.create.mixing('2x mysticalagriculture:tertium_essence', ['mysticalagriculture:prudentium_essence', 'mysticalagriculture:prudentium_essence', 'mysticalagriculture:prudentium_essence', 'mysticalagriculture:prudentium_essence', 'matc:prudentium_crystal']).heated()
	e.recipes.create.mixing('minecraft:ender_eye', ['#forge:ender_pearls', '#forge:dusts/blaze']).heated()
	e.recipes.create.mixing('thermal:rubber', [Fluid.of('industrialforegoing:latex_fluid', 100), '#forge:slimeballs']).heated()
	e.recipes.create.mixing('4x waystones:warp_dust', ['#forge:ender_pearls', '#forge:dyes/purple'])

	e.recipes.create.mixing('appliedenergistics2:annihilation_core', ['#forge:gems/quartz', '#forge:dusts/fluix', 'appliedenergistics2:logic_processor']).superheated()
	e.recipes.create.mixing('appliedenergistics2:formation_core', ['#forge:gems/certus_quartz', '#forge:dusts/fluix', 'appliedenergistics2:logic_processor']).superheated()
	e.recipes.create.mixing('extendedcrafting:enhanced_ender_ingot', ['#forge:ingots/enderium', '#forge:ingots/enderium', '#forge:ingots/enderium', '#forge:ingots/enderium', 'extendedcrafting:ender_star']).superheated()
	e.recipes.create.mixing('extendedcrafting:the_ultimate_ingot', ['extendedcrafting:black_iron_ingot', 'extendedcrafting:black_iron_ingot', 'extendedcrafting:black_iron_ingot', 'extendedcrafting:black_iron_ingot', 'extendedcrafting:redstone_ingot', 'extendedcrafting:redstone_ingot', 'extendedcrafting:redstone_ingot', 'extendedcrafting:redstone_ingot', 'extendedcrafting:ender_ingot', 'extendedcrafting:ender_ingot', 'extendedcrafting:ender_ingot', 'extendedcrafting:ender_ingot', 'extendedcrafting:enhanced_ender_ingot', 'extendedcrafting:enhanced_ender_ingot', 'extendedcrafting:enhanced_ender_ingot', 'extendedcrafting:enhanced_ender_ingot', 'extendedcrafting:crystaltine_ingot', 'extendedcrafting:crystaltine_ingot', 'extendedcrafting:crystaltine_ingot', 'extendedcrafting:crystaltine_ingot']).superheated()
	e.recipes.create.mixing('forbidden_arcanus:aquatic_dragon_scale', ['#forge:dusts/prismarine', '#forge:gems/prismarine', '#forge:dusts/arcane_crystal', 'forbidden_arcanus:dragon_scale']).superheated()
	e.recipes.create.mixing('forbidden_arcanus:golden_dragon_scale', ['#forge:dusts/arcane_crystal', '#forge:dusts/arcane_crystal', '#forge:dusts/arcane_crystal', '#forge:dusts/arcane_crystal', '#forge:ingots/gold', '#forge:ingots/gold', '#forge:ingots/gold', 'forbidden_arcanus:dragon_scale']).superheated()
	e.recipes.create.mixing('forbidden_arcanus:purifying_soap', ['#forge:slimeballs', '#forge:gems/prismarine', '#minecraft:small_flowers', '#forge:dusts/arcane_crystal', 'forbidden_arcanus:wax']).superheated()
	e.recipes.create.mixing('forbidden_arcanus:silver_dragon_scale', ['#forge:dusts/arcane_crystal', '#forge:dusts/arcane_crystal', '#forge:dusts/arcane_crystal', '#forge:dusts/arcane_crystal', '#forge:ingots/silver', '#forge:ingots/silver', '#forge:ingots/silver', 'forbidden_arcanus:dragon_scale']).superheated()
	e.recipes.create.mixing('2x gobber2:gobber2_ingot', ['forbidden_arcanus:purifying_soap', 'astralsorcery:starmetal_ingot', 'doom:argent_energy', 'gobber2:gobber2_glob']).superheated()
	e.recipes.create.mixing('2x gobber2:gobber2_ingot_end', ['gobber2:gobber2_glob_end', 'gobber2:gobber2_ingot_nether', 'gobber2:gobber2_ingot_nether', 'minecraft:chorus_flower']).superheated()
	e.recipes.create.mixing('2x gobber2:gobber2_ingot_nether', ['gobber2:gobber2_glob_nether', 'gobber2:gobber2_ingot', 'gobber2:gobber2_ingot', '#forge:ingots/netherite_scrap']).superheated()
	e.recipes.create.mixing('mysticalagriculture:tertium_ingot', ['mysticalagriculture:prudentium_ingot', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:tertium_essence']).superheated()
	e.recipes.create.mixing('mysticalagriculture:imperium_ingot', ['mysticalagriculture:tertium_ingot', 'mysticalagriculture:imperium_essence', 'mysticalagriculture:imperium_essence']).superheated()
	e.recipes.create.mixing('mysticalagriculture:supremium_ingot', ['mysticalagriculture:imperium_ingot', 'mysticalagriculture:supremium_essence', 'mysticalagriculture:supremium_essence']).superheated()
	e.recipes.create.mixing('mysticalagradditions:insanium_ingot', ['mysticalagriculture:supremium_ingot', 'mysticalagradditions:insanium_essence', 'mysticalagradditions:insanium_essence']).superheated()
	e.recipes.create.mixing('mysticalagradditions:imperium_apple', ['mysticalagriculture:imperium_essence', 'mysticalagriculture:imperium_essence', 'mysticalagriculture:imperium_essence', 'mysticalagriculture:imperium_essence', 'mysticalagradditions:tertium_apple']).superheated()
	e.recipes.create.mixing('mysticalagradditions:supremium_apple', ['mysticalagriculture:supremium_essence', 'mysticalagriculture:supremium_essence', 'mysticalagriculture:supremium_essence', 'mysticalagriculture:supremium_essence', 'mysticalagradditions:imperium_apple']).superheated()
	e.recipes.create.mixing('mysticalagradditions:insanium_apple', ['mysticalagradditions:insanium_essence', 'mysticalagradditions:insanium_essence', 'mysticalagradditions:insanium_essence', 'mysticalagradditions:insanium_essence', 'mysticalagradditions:supremium_apple']).superheated()
	e.recipes.create.mixing('mysticalagriculture:tertium_gemstone', ['mysticalagriculture:tertium_essence', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:prudentium_gemstone']).superheated()
	e.recipes.create.mixing('mysticalagriculture:imperium_gemstone', ['mysticalagriculture:imperium_essence', 'mysticalagriculture:imperium_essence', 'mysticalagriculture:tertium_gemstone']).superheated()
	e.recipes.create.mixing('mysticalagriculture:supremium_gemstone', ['mysticalagriculture:supremium_essence', 'mysticalagriculture:supremium_essence', 'mysticalagriculture:imperium_gemstone']).superheated()
	e.recipes.create.mixing('mysticalagradditions:insanium_gemstone', ['mysticalagradditions:insanium_essence', 'mysticalagradditions:insanium_essence', 'mysticalagriculture:supremium_gemstone']).superheated()
	e.recipes.create.mixing('mysticalagradditions:tertium_coal', ['mysticalagriculture:tertium_essence', 'mysticalagriculture:tertium_essence', 'mysticalagradditions:prudentium_coal']).superheated()
	e.recipes.create.mixing('mysticalagradditions:imperium_coal', ['mysticalagriculture:imperium_essence', 'mysticalagriculture:imperium_essence', 'mysticalagradditions:tertium_coal']).superheated()
	e.recipes.create.mixing('mysticalagradditions:supremium_coal', ['mysticalagriculture:supremium_essence', 'mysticalagriculture:supremium_essence', 'mysticalagradditions:imperium_coal']).superheated()
	e.recipes.create.mixing('mysticalagradditions:insanium_coal', ['mysticalagradditions:insanium_essence', 'mysticalagradditions:insanium_essence', 'mysticalagradditions:supremium_coal']).superheated()
	e.recipes.create.mixing('mysticalagriculture:tertium_watering_can', ['mysticalagriculture:mystical_fertilizer', 'mysticalagriculture:mystical_fertilizer', 'mysticalagriculture:mystical_fertilizer', 'mysticalagriculture:mystical_fertilizer', 'mysticalagriculture:tertium_ingot', 'mysticalagriculture:tertium_ingot', 'mysticalagriculture:tertium_ingot', 'mysticalagriculture:tertium_ingot', 'mysticalagriculture:prudentium_watering_can']).superheated()
	e.recipes.create.mixing('mysticalagriculture:imperium_watering_can', ['mysticalagriculture:mystical_fertilizer', 'mysticalagriculture:mystical_fertilizer', 'mysticalagriculture:mystical_fertilizer', 'mysticalagriculture:mystical_fertilizer', 'mysticalagriculture:imperium_ingot', 'mysticalagriculture:imperium_ingot', 'mysticalagriculture:imperium_ingot', 'mysticalagriculture:imperium_ingot', 'mysticalagriculture:tertium_watering_can']).superheated()
	e.recipes.create.mixing('mysticalagriculture:supremium_watering_can', ['mysticalagriculture:mystical_fertilizer', 'mysticalagriculture:mystical_fertilizer', 'mysticalagriculture:mystical_fertilizer', 'mysticalagriculture:mystical_fertilizer', 'mysticalagriculture:supremium_ingot', 'mysticalagriculture:supremium_ingot', 'mysticalagriculture:supremium_ingot', 'mysticalagriculture:supremium_ingot', 'mysticalagriculture:imperium_watering_can']).superheated()
	e.recipes.create.mixing('mysticalagriculture:imperium_farmland', ['mysticalagriculture:imperium_essence', '#forge:hoes', '#forge:dirt']).superheated()
	e.recipes.create.mixing('2x mysticalagriculture:supremium_farmland', ['mysticalagriculture:supremium_essence', '#forge:hoes', 'mysticalagriculture:imperium_farmland']).superheated()
	e.recipes.create.mixing('2x mysticalagradditions:insanium_farmland', ['mysticalagradditions:insanium_essence', '#forge:hoes', 'mysticalagriculture:supremium_farmland']).superheated()
	e.recipes.create.mixing('2x mysticalagriculture:imperium_essence', ['mysticalagriculture:tertium_essence', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:tertium_essence', 'matc:tertium_crystal']).superheated()
	e.recipes.create.mixing('2x mysticalagriculture:supremium_essence', ['mysticalagriculture:imperium_essence', 'mysticalagriculture:imperium_essence', 'mysticalagriculture:imperium_essence', 'mysticalagriculture:imperium_essence', 'matc:imperium_crystal']).superheated()
	e.recipes.create.mixing('2x mysticalagradditions:insanium_essence', ['mysticalagriculture:supremium_essence', 'mysticalagriculture:supremium_essence', 'mysticalagriculture:supremium_essence', 'mysticalagriculture:supremium_essence', 'matc:supremium_crystal']).superheated()
	e.recipes.create.mixing('4x refinedstorage:quartz_enriched_iron', ['#forge:gems/silicon', '#forge:gems/silicon', 'extendedcrafting:black_iron_ingot']).superheated()
	e.recipes.create.mixing('refinedstorage:processor_binding', ['immersiveengineering:hemp_fiber', 'immersiveengineering:hemp_fiber', 'bloodmagic:reagentbinding', 'mysticalagriculture:pink_slime_essence', 'mysticalagriculture:pink_slime_essence']).superheated()
	e.recipes.create.mixing('refinedstorage:construction_core', ['refinedstorage:basic_processor', '#forge:dusts/glowstone']).superheated()
	e.recipes.create.mixing('refinedstorage:destruction_core', ['refinedstorage:basic_processor', '#forge:gems/quartz']).superheated()
	e.recipes.create.mixing('refinedstorage:raw_improved_processor', ['immersiveengineering:wirecoil_electrum', '#forge:gems/silicon', 'extendedcrafting:redstone_catalyst', 'refinedstorage:processor_binding', 'immersiveengineering:wirecoil_electrum']).superheated()
	e.recipes.create.mixing('refinedstorage:raw_basic_processor', ['extendedcrafting:black_iron_ingot', '#forge:gems/silicon', 'extendedcrafting:redstone_catalyst', 'refinedstorage:processor_binding']).superheated()
	e.recipes.create.mixing('refinedstorage:raw_advanced_processor', ['#forge:gears/diamond', '#forge:gems/silicon', 'extendedcrafting:redstone_catalyst', 'refinedstorage:processor_binding']).superheated()
	e.recipes.create.mixing('extradisks:raw_withering_processor', ['#forge:nether_stars', '#forge:gems/silicon', 'extendedcrafting:redstone_catalyst', 'refinedstorage:processor_binding']).superheated()
	e.recipes.create.mixing('extrastorage:raw_neural_processor', ['#forge:workbenches', '#forge:gems/quartz', '#forge:obsidian', 'refinedstorage:processor_binding']).superheated()
	e.recipes.create.mixing('2x thermal:enderium_glass', ['thermal:obsidian_glass', 'thermal:obsidian_glass', '#forge:ingots/enderium']).superheated()
	e.recipes.create.mixing('2x thermal:lumium_glass', ['thermal:obsidian_glass', 'thermal:obsidian_glass', '#forge:ingots/lumium']).superheated()
	e.recipes.create.mixing('2x thermal:signalum_glass', ['thermal:obsidian_glass', 'thermal:obsidian_glass', '#forge:ingots/signalum']).superheated()
	e.recipes.create.mixing('thermal:obsidian_glass', ['immersiveengineering:insulating_glass', 'create:polished_rose_quartz', '#forge:ingots/obsidian']).superheated()
})

