JEIEvents.hideItems( e => {
  let colors = ['cyan', 'purple', 'blue', 'brown', 'green', 'red', 'black', 'white', 'orange', 'magenta', 'light_blue', 'yellow', 'lime', 'pink', 'gray', 'light_gray']

  let itemsToHide = [
    /.*spawn_egg.*/,
    /^ae2:.+_ore$/,
    'ae2:iron_dust',
    'ae2:gold_dust',
    'ae2:encoded_pattern',
    /^aquaculture:.+_bucket$/,

    'ars_nouveau:bucket_of_mana',
    /^ars_nouveau:.+_se$/,

    /^astralsorcery:.+_(ore|bucket)$/,
    'astralsorcery:glow_flower',
    /^atum:.+_ore$/,
    /^alexsmobs:.*_bucket$/,
    /^alexsmobs:.*_egg$/,
    /^alexsmobs:leafcutter_.+/,
    /^bigreactors:.+(ore|bucket)$/,
    /^bloodmagic:.+_bucket$/,
    /^blue_skies:.+_ore$/,
    /^blue_skies:ventium_.+_bucket$/,
    /^betteranimalsplus:.*_bucket$/,

    /^cfm:(?!.*spruce).+_(table|chair|cabinet|desk|blinds|fence|gate|crate|bench|mail_box|hedge|counter|drawer|sink_light|sink_dark)$/,
    /^cfm:(?!.*white).+_(sofa|cooler|grill|counter|fence|gate|drawer|kitchen_sink)$/,
    /^morecfm:(?!.*spruce).+_(table|chair|cabinet|desk|blinds|fence|gate|crate|bench|mail_box|hedge|counter|drawer|sink_light|sink_dark)$/,
    /^morecfm:(?!.*white).+_(sofa|cooler|grill|counter|fence|gate|drawer|kitchen_sink)$/,

    '@chipped',

    /^create:(zinc)_(ingot|nugget|block)$/,
    /^create:(brass)_(ingot|nugget|block)$/,
    /^create:(copper)_(ingot|nugget|block|sheet_meta)$/,
    /^create:.+_(ore|bucket|sheet)$/,
    /^createdeco:(copper)_(ingot|nugget)$/,
    'createdeco:gold_sheet_metal',
    'createdeco:iron_sheet_metal',
    'createdeco:zinc_sheet',
    'create:powdered_obsidian',
    /^steampowered:(cast_iron)_(ingot|sheet)$/,
    /^steampowered:(steel)_(ingot|sheet)$/,
    /^steampowered:(bronze)_(sheet)$/,
    'createaddition:diamond_grit',
    'createaddition:copper_wire',
    'createaddition:seed_oil_bucket',
    /^createaddition:.+_rod$/,

    /^cyclic:.*_bucket$/,
    'cyclic:uncrafter',
    'croptopia:salt_ore',

    /^doggytalents:dog_bed$/,
    /^draconicevolution:.+_ore$/,
    /^eidolon:(lead)_(ore|ingot|nugget|block)$/,

    /^environmental:.+_bucket$/,
    /^forbidden_arcanus:.+_bucket$/,
    /^ftbquests:.+/,
    /^gobber2:.+_ore$/,
    /^hexerei:.+_bucket$/,

    /^immersive(engineering|petroleum):.+_bucket$/,
    /^immersiveengineering:(ore|dust|stick|plate|storage|nugget|ingot)_.+/,
    'immersiveengineering:coke',
    'immersiveengineering:coal_coke',
    'immersiveengineering:slag',
    /^immersiveposts:(stick)_(copper|gold|lead|silver|nickel|constantan|electrum|uranium)$/,

    /^industrialforegoing:.+_bucket$/,
    /^ironfurnaces:augment_.+/,
    'libraryferret:fake_iron_block',
    'libraryferret:fake_gold_block',
    'libraryferret:fake_emerald_block',
    'libraryferret:fake_diamond_block',
    'libraryferret:fake_netherite_block',
    /^materialis:molten_.+_bucket$/,

    /^mcwbridges:(?!.*spruce).+_(log_bridge_middle|bridge|bridge_pier|bridge_stair)$/,
    /^mcwdoors:(?!.*spruce).+_door$/,
    /^mcwfences:(?!.*spruce).+_(fence|gate|wall)$/,
    /^mcwfencesbop:.+_(fence|gate|wall)$/,
    /^mcwfurnitures:(?!.*spruce).+_(wardrobe|bookshelf|cupboard|drawer|desk|table|chair|counter)$/,
    /^mcwlights:(?!.*spruce).+_(lamp|torch|ceiling_light)$/,
    /^mcwroofs:(?!.*spruce).+_(awning|roof)$/,
    /^mcwroofs:gutter_(?!.*base).+/,
    /^mcwwindows:(?!.*spruce).+_(window|window2|parapet|blinds)$/,

    /^mekanism:.+_(ore|bucket)$/,
    /^mekanism:(dust|ingot|nugget)_.+/,
    /^mekanism:(block)_(copper)$/,
    /^mekanism:(block)_(steel)$/,
    /^mekanism:(block)_(uranium)$/,
    /^mekanism:(block)_(lead)$/,
    /^mekanism:(block)_(osmium)$/,
    /^mekanism:(block)_(bronze)$/,
    'mekanism:creative_chemical_tank',
    'mekanism:creative_fluid_tank',
    'mekanism:uranium_hexafluoride_bucket',
    'mekanism:uranium_oxide_bucket',
    /^mekanismgenerators:.+_bucket$/,

    /^minecraft:.+_(ore|bucket)$/,
    /^minecraft:infested_.+/,
    'minecraft:bedrock',
    'minecraft:end_portal_frame',
    'minecraft:chorus_plant',
    'minecraft:chipped_anvil',
    'minecraft:damaged_anvil',
    'minecraft:ender_chest',

    /^minecolonies:.+egg/,
    /^mysticalagradditions:.+_(ore|bucket)$/,
    /^mysticalagriculture:.+_ore$/,
    'mysticalagriculture:infusion_crystal',
    /^mythicbotany:.+_ore$/,

    /^occultism:(copper|silver)_(ore|ingot|nugget|dust|block)$/,
    /^occultism:(obsidian|iron|gold)_dust$/,
    'occultism:lighted_air',
    /^pneumaticcraft:.+_bucket$/,

    'prefab:block_compressed_dirt',
    'prefab:block_double_compressed_dirt',


    /^quark:.+_ore$/,
    /^quark:ancient_tome$/,
    /^quark:backpack$/,
    /^quark:.+_bucket$/,
    /^quark:.+_pouch$/,
    /^quark:.+_shard$/,
    /^quark:.+_crystal_cluster$/,
    /^quark:.+_leaves$/,
    'quark:magnet',
    'quark:pipe',
    'quark:soul_compass',
    'quark:bottled_cloud',
    'quark:matrix_enchanter',
    'quark:chorus_weeds',
    'quark:chorus_twist',
    'quark:crate',
    'quark:bonded_ravager_hide',
    'quark:ravager_hide',
    'quark:music_disc_endermosh',
    'quark:abacus',
    'quark:glowcelium',

    '@rechiseled',
    /^rftoolsbase:dimensionalshard_.+/,
    /^routerreborn:(copper)_(ingot|nugget|ore)$/,

    /^structurize:.+timber_frame$/,
    /^structurize:.+shingle$/,
    /^structurize:.+shingle_slab$/,

    /supplementaries:bamboo_spikes_tipped/,
    /^sushigocrafting:.+_bucket$/,
    /^tconstruct:.+_(ore|bucket)$/,
    /^tconstruct:(copper)_(ingot|nugget|block)$/,
    /^tconstruct:(cobalt)_(ingot|nugget|block)$/,

    /^thermal:.+_(ore|bucket)$/,
    /^thermal:(apatite|cinnabar|niter|sulfur|coal_coke)_block$/,
    /^thermal:(iron|gold|lapis|diamond|emerald|quartz|copper|tin|lead|silver|nickel|bronze|electrum|invar|constantan|signalum|lumium|enderium)_(block|ingot|nugget|dust|gear|plate)$/,

    'tombstone:grave_key',
    'tombstone:ghostly_shape',
    'tombstone:preservation',
    'tombstone:unstable_intangibleness',
    'tombstone:diversion',
    'tombstone:feather_fall',
    'tombstone:purification',
    'tombstone:true_sight',
    'tombstone:prayer',
    'tombstone:reach',
    'tombstone:lighting_aquatic_liferesistance',
    'tombstone:frost_resistance',
    'tombstone:bone_shield',
    'tombstone:bait',
    'tombstone:aquatic_life',

    /^twilightforest:force_field_.+/,
    /^twilightforest:boss_spawner_.+/,
    /^twilightforest:shader_bag_.+/,
    /^twilightforest:castle_door_.+/,
    /^twilightforest:castle_brick_.+/,
    /^twilightforest:fake_.+/,
    /^twilightforest:giant_.+/,
    /^twilightforest:.+_miniature_structure$/,
    /^twilightforest:.+door$/,
    /^twilightforest:.+_leaves$/,
    /^twilightforest:.+_trophy$/,
    /^twilightforest:.+_core$/,
    /^twilightforest:.+_cloud$/,
    'twilightforest:uncrafting_table',
    'twilightforest:cube_of_annihilation',
    'twilightforest:moon_dial',
    'twilightforest:cinder_furnace',
    'twilightforest:cinder_log',
    'twilightforest:cinder_wood',
    'twilightforest:slider',
    'twilightforest:hedge',
    'twilightforest:root',
    'twilightforest:liveroot_block',
    'twilightforest:moss_patch',
    'twilightforest:mayapple',
    'twilightforest:clover_patch',
    'twilightforest:fiddlehead',
    'twilightforest:mushgloom',
    'twilightforest:torchberry_plant',
    'twilightforest:root_strand',
    'twilightforest:firefly',
    'twilightforest:cicada',
    'twilightforest:moonworm',
    'twilightforest:ore_meter',
    'twilightforest:magic_map',
    'twilightforest:maze_map',
    'twilightforest:ore_map',
    'twilightforest:liveroot',
    'twilightforest:transformation_powder',
    'twilightforest:maze_wafer',
    'twilightforest:tower_key',
    'twilightforest:brown_thorns',
    'twilightforest:green_thorns',
    'twilightforest:burnt_thorns',
    'twilightforest:thorn_rose',
    'twilightforest:cube_talisman',
    'twilightforest:keepsake_casket',
    'twilightforest:huge_waterlily',
    'twilightforest:huge_lilypad',
    'twilightforest:auroralized_glass',
    'twilightforest:trollsteinn',
    'twilightforest:aurora_block',
    'twilightforest:trollvidr',
    'twilightforest:unripe_trollber',
    'twilightforest:aurora_block',
    'twilightforest:huge_mushgloom',
    'twilightforest:huge_mushgloom_stem',
    'twilightforest:uberous_soil',
    'twilightforest:huge_stalk',
    'twilightforest:trollber',
    'twilightforest:deadrock',
    'twilightforest:deadrock_cracked',
    'twilightforest:deadrock_weathered',
    'twilightforest:stone_twist',
    'twilightforest:stone_twist_thin',
    'twilightforest:mazestone',
    'twilightforest:underbrick_floor',

    /^undergarden:.+_bucket$/,
    /^upgrade_aquatic:.+_bucket$/,
    'upgrade_aquatic:embedded_ammonite',

    /^reliquary:bullets\/neutral_bullet$/,
    /^reliquary:magazines\/neutral_magazine$/
  ]

  itemsToHide.forEach(i => e.hide(i))
  colors.forEach(c => { if (c != 'light_blue') e.hide(`/^refinedstorage:${c}_.+/`) })
})

JEIEvents.hideFluids( e => e.hideAll())
